### ISSUE TITLE
Possible to download sector information from yahoo finance?

### ISSUE THREAD

**Issue by twiecki** [pydata/pandas-datareader#103]
Yahoo finance does give you information on sector and industry: http://finance.yahoo.com/q/pr?s=AAPL+Profile

Is it possible to access that data through `pandas-datareader`?

**Comment by sinhrks** [comment]
Currently no, I think. Adding ``Options('aapl').get_profile()`` and parse "Details" table should be useful?

**Comment by twiecki** [comment]
I installed master but there's no `.get_profile()`

**Comment by sinhrks** [comment]
Ah, I meant a method being added to meet the request.

**Comment by twiecki** [comment]
@sinhrks Ah, yeah that would certainly work.

**Comment by davidastephens** [comment]
@twiecki 

Have a look at https://github.com/davidastephens/pandas-finance, I added a profile, sector, industry and employee property to the Equity object.

**Comment by twiecki** [comment]
@davidastephens Thanks, that's really helpful. Any reason to have 2 packages that do similar things or is there a way to merge the two?

**Comment by davidastephens** [comment]
There was some discussion in #117 about this.  The pandas-finance package is planned to be more a high level api for finance related code rather than just data reading.  This package is more for time-series / bulk data downloading.  Certainly this particular feature has some overlap across the packages.  I'm happy merge it into datareader people think it fits better here.

**Comment by twiecki** [comment]
@davidastephens I'm not directly involved in either of the two projects so take this as you may. While the division makes sense to me, pandas-finance is merely a thin wrapper on top of pandas-datareader, and because it's just a couple of lines it might make sense to include the API here. pandas-datareader only reads financial data so the target audience is very close.

Irrespective of that, the place where you do parse and load individual data is `profile`. That could certainly be submitted to pandas-datareader which would also keep the abstraction coherent.

**Comment by bashtage** [comment]
Yahoo has been deprecated.

**Comment by satvikjadhav** [comment]
> @twiecki
> 
> Have a look at https://github.com/davidastephens/pandas-finance, I added profile, sector, industry and employees properties to the Equity object.

Is there any way to get stocks from different regions? For example, I am trying to get a Japanese stock from the Tokyo Stock Exchange. Is that possible? If so, how? 
Thank you.
