### ISSUE TITLE
Additional data for yahoo finance data reader

### ISSUE THREAD

**Issue by ccsv** [pydata/pandas-datareader#111]
Can additional data be added to the `Datareader` other than OHLC and volume data. 

Data such as can be obtained:
- Dividend information (dates, yield, ex-dividend date...etc)
- EPS
- Market cap
- Price to book ratio
- P/E ratio
- Financial information such as quarter earnings.

The yahoo API supports streaming some of these through special tags as seen here: https://greenido.wordpress.com/2009/12/22/yahoo-finance-hidden-api/

This can be done in request but it would be nice if the Datareader had some option to scrape this information.

Thoughts?

**Comment by twiecki** [comment]
+1

**Comment by femtotrader** [comment]
See also http://www.myhow2.net/wp/2013/07/python-how-to-look-up-stock-price-using-yahoo-stock-data-service/

I think original version come from http://www.gummy-stuff.org/Yahoo-data.htm

We should be aware of this !

**Comment by aabdelfattah** [comment]
+1

**Comment by rsvp** [comment]
As of November 2017, even **getting closing prices is problematic.**
For a current overview, see https://github.com/rsvp/fecon235/issues/7 
also for alternative solutions.

**Comment by bashtage** [comment]
Yahoo has been deprecated.
