### ISSUE TITLE
Receives yahoo historical csv data in zip form, so read_csv fails for zipped data

### ISSUE THREAD

**Issue by skadiran** [pydata/pandas-datareader#112]
For some reason, urlopen returns data from yahoo in a zip form. this could be due to internet service providers adding additional headers in the request to bump up bandwith. Because of this compressed data received from yahoo, the read csv function in data.py fails. It might be worth adding a check before read_csv if the data received is in zip (gzip) form and unzip it before reading? Please advice.

**Comment by guy1nj** [comment]
To fix this locally, following work around worked ok for me,

in _utils.py, the function, _retry_read_url is modified as, 

    with urlopen(url) as resp:
                if resp.info().get('Content-Encoding') == 'gzip':
                        buf = StringIO( resp.read())
                        f = gzip.GzipFile(fileobj=buf)
                        data = f.read()
                else:
                        lines = resp.read()

**Comment by bashtage** [comment]
This API is deprecated.
