### ISSUE TITLE
unable to do 'conda install' win-32

### ISSUE THREAD

**Issue by eugbel** [pydata/pandas-datareader#113]
Hi, 

C:\dev>conda install pandas-datareader
Fetching package metadata: ....
Error: No packages found in current win-32 channels matching: pandas-datareader

Would it be possible to add it? Thank you...

**Comment by jreback** [comment]
these will be built when the next version of anaconda is out (next week or after I think)

**Comment by bashtage** [comment]
Assuming you have pandas, just

```
pip install pandas-datareader
```

or 

```
pip install git+git://github.com/pydata/pandas-datareader.git
```

to get master.

There is no binary component to datareader.

**Comment by davidastephens** [comment]
@eugbel - closing, please reopen if it still doesn't work.
