### ISSUE TITLE
pandas_datareader or pandas-datareader, pick one single spelling

### ISSUE THREAD

**Issue by adrivsh** [pydata/pandas-datareader#118]
The fact that there are two different spellings for this package has caused me some confusion

My suggestion is to go with "pandas_datareader", as this is the spelling that works with python (import pandas-datareader is not valid syntax). This means that this git repo as well as all the documentation should refer to the package as "pandas_datareader".

Even if renaming this repo is messy, I do suggest to make the changes in the documentation here http://pandas.pydata.org/pandas-docs/stable/remote_data.html

**Comment by twiecki** [comment]
I actually start to wonder if pandas should be in the same. Except for where the library is from, pandas has no bearing. It's a library for loading timeseries data it seems.

**Comment by bashtage** [comment]
It is a downstream project from pandas, and the association benefits
exposure. This naming convention is common in other parts of Python such as
django-SUBPROJECT
