### ISSUE TITLE
REL: Release 0.2.1

### ISSUE THREAD

**Issue by davidastephens** [pydata/pandas-datareader#123]
Will do a release this week to get the ability to use request sessions on the pypi version.  

Anyone feel like writing some docs for it? 

@femtotrader ?

**Comment by femtotrader** [comment]
I don't feel really confortable at writing doc as my mother tongue is not english.

Moreover I think we need to rewrite `wb.py` before releasing (because it's better to support caching on all data reader)

**Comment by davidastephens** [comment]
I think @sinhrks took care of that in #121.

Feel free to take a stab at it and I can edit it if you have time.  I've never used requests sessions or the requests cache.

**Comment by femtotrader** [comment]
Yes you are write but we should also have sessing passed to other function in `wb.py`

**Comment by femtotrader** [comment]
This PR is a first try for a doc https://github.com/pydata/pandas-datareader/pull/126

**Comment by davidastephens** [comment]
All good for a release tomorrow?

**Comment by femtotrader** [comment]
I think that's ok.
