### ISSUE TITLE
Treasury returns

### ISSUE THREAD

**Issue by twiecki** [pydata/pandas-datareader#125]
To my knowledge, pandas-datareader does not support loading of US treasury returns from the federal reserve. These are implemented in zipline: https://github.com/quantopian/zipline/blob/master/zipline/data/treasuries.py

Is there interest in adding these to `pandas-datareader`? What's the preferred style?

**Comment by twiecki** [comment]
It seem treasury yields can be loaded already via FRED:
`web.DataReader("DGS3MO", "fred", start, end)`

**Comment by westurner** [comment]
There's also https://github.com/npezolano/PyTreasuryDirect

https://github.com/npezolano/PyTreasuryDirect/blob/master/pytreasurydirect/pytreasurydirect.py
