### ISSUE TITLE
Missing ga support?

### ISSUE THREAD

**Issue by iceanfire** [pydata/pandas-datareader#127]
Just want to confirm that this library doesn't have GA support as the previous pandas.io did?

**Comment by davidastephens** [comment]
It does not.  There was some discussion in pydata/pandas#8961in which people were generally supportive of moving ga over, but for some reason it didn't make it in the package.

**Comment by jreback** [comment]
this was discontinued in pandas as it was not tested / had a champion - prob much better off being a separate package entirely

**Comment by femtotrader** [comment]
This project https://github.com/debrouwere/google-analytics seems to support Pandas DataFrames export. Maybe we should close this issue ?

**Comment by bashtage** [comment]
Closing in favor of other project.
