### ISSUE TITLE
Missing `0.2.1` tag, and pypi tarball missing test data

### ISSUE THREAD

**Issue by cournape** [pydata/pandas-datareader#140]
I see issues w/ the tarball on pypi:
1. pypi has version `0.2.1`, but I don't see the corresponding tag here
2. some sdmx data are missing from the tarball.

Without the tag, it is hard to fix this in a PR ;)

**Comment by davidastephens** [comment]
My bad - added a v0.2.1 tag.

**Comment by davidastephens** [comment]
@cournape Is this fixed now?
