### ISSUE TITLE
reading options data from Google Finance

### ISSUE THREAD

**Issue by gliptak** [pydata/pandas-datareader#148]
In https://github.com/pydata/pandas/issues/5404 we discussed a possible use of PhantomJS for this parsing. Would this extra dependency be acceptable under the ```pandas-datareader``` umbrella? Thanks

**Comment by davidastephens** [comment]
We could make it an optional dependency for downloading google finance options data.   I use PhantomJS for other webscraping that I do, although its somewhat harder to install (no pip / distutils installation).

Is there any reason why we'd want to do this instead of just using Yahoo?

**Comment by gliptak** [comment]
The benefit is having another data source.

I just found out that Google offers a `direct` JSON download as
http://www.google.com/finance/option_chain?q=AAPL&expd=31&expm=12&expy=2015&output=json

(http://stackoverflow.com/questions/9649052/finance-historical-options-data-with-strikes-etc-on-google-finance-api)

**Comment by gliptak** [comment]
In addition, PhantomJS removed Python support, so now http://jeanphix.me/Ghost.py/ is the recommended engine ...

**Comment by davidastephens** [comment]
JSON download looks good - that should be an easy add.

**Comment by gliptak** [comment]
https://github.com/pydata/pandas-datareader/pull/183

**Comment by gliptak** [comment]
https://github.com/pydata/pandas-datareader/issues/37

**Comment by gliptak** [comment]
Implemented.
