### ISSUE TITLE
Strike prices > 1k are returned as strings

### ISSUE THREAD

**Issue by aisthesis** [pydata/pandas-datareader#168]
When trying to pull call strikes from Yahoo! Finance, I'm getting for 'GOOGL' as strike:

    minputstrike = straddle['strike'] - straddle['price']
        TypeError: unsupported operand type(s) for -: 'str' and 'float'

When I print out the value for straddle['strike'], which is the df pulled from yahoo finance, I get: `1,040.00`. It looks like the comma from Yahoo is not allowing casting as float.

**Comment by femtotrader** [comment]
Here is a quick way to reproduce:

```python
from pandas_datareader import data, w
opt = data.Options("GOOG", "yahoo")
opt.calls180119.index.levels[0] + 0.5
```

it raises

```python
TypeError: Can't convert 'float' object to str implicitly
```

We might have a look at
http://stackoverflow.com/questions/6633523/how-can-i-convert-a-string-with-dot-and-comma-into-a-float-number-in-python

There is two way to fix this
- replace ',' by ''
- use locale (`locale.atof`)

We ever have some problems with locale see https://github.com/pydata/pandas-datareader/issues/63

This issue could be an occasion to fix it!

Maybe we should use a context manager to save user local, set user locale to english and performs string to number conversion and then go back to user local.

I'm aware that's not the easiest way to fix this issue but that's probably the cleanest.

**Comment by aisthesis** [comment]
While I haven't looked at the code that initially creates the options DataFrame, I don't see how it could be otherwise than having strike be a string in the early stages of the creation process. I would think the easiest (and adequately performant) way to do it would be just to strip commas out of the string before attempting to convert to float.

If `valstr` is guaranteed to be a string, then you could do maybe something like `float(valstr.replace(',', ''))`. Since the performance bottleneck on all of this is going to be data transfer by wire plus yahoo's internal process of getting it from their databases, that's probably performant enough. But I'm all for it, if there's a way that is faster.

**Comment by gliptak** [comment]
In the Google options processing, I decided to process as ```float(row['p'].replace(',', ''))```
https://github.com/pydata/pandas-datareader/pull/183
