### ISSUE TITLE
Yahoo returning: pandas_datareader._utils.RemoteDataError: Unable to read URL:

### ISSUE THREAD

**Issue by canivel** [pydata/pandas-datareader#170]
I always use the call to the service like this:

```
import datetime as dt
import pandas_datareader.data as web

start_date = dt.datetime(2008,1,1)
end_date = dt.datetime(2009,1,1)
web.DataReader('GOOG', 'yahoo', start_date, end_date)
```

Today I'm getting: 

> pandas_datareader._utils.RemoteDataError: Unable to read URL: http://ichart.finance.yahoo.com/table.csv

Is yahoo off?

from google finance it comes ok.

Thanks

**Comment by canivel** [comment]
I tried in two different networks still getting the same error, so it's no a network block

**Comment by femtotrader** [comment]
It works fine on my side.

Feel free to reopen if you still facing this issue.

**Comment by unijoy** [comment]
`startDate = datetime.datetime(2016, 8, 15)
endDate = datetime.datetime(2016, 8, 17)
tt = web.DataReader("SHA:600936", 'google', startDate, endDate)`


`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/pandas_datareader/data.py", line 105, in DataReader
    session=session).read()
  File "/usr/lib/python2.7/site-packages/pandas_datareader/base.py", line 173, in read
    df = self._read_one_data(self.url, params=self._get_params(self.symbols))
  File "/usr/lib/python2.7/site-packages/pandas_datareader/base.py", line 80, in _read_one_data
    out = self._read_url_as_StringIO(url, params=params)
  File "/usr/lib/python2.7/site-packages/pandas_datareader/base.py", line 91, in _read_url_as_StringIO
    response = self._get_response(url, params=params)
  File "/usr/lib/python2.7/site-packages/pandas_datareader/base.py", line 117, in _get_response
    raise RemoteDataError('Unable to read URL: {0}'.format(url))
pandas_datareader._utils.RemoteDataError: Unable to read URL: http://www.google.com/finance/historical`


not working for me

**Comment by femtotrader** [comment]
Hello,

Please use 3 backquotes for code in GitHub https://help.github.com/articles/creating-and-highlighting-code-blocks/
Please use latest master see https://github.com/pydata/pandas-datareader/issues/223#issuecomment-239853627

Kind regards

**Comment by tjgerot** [comment]
Looks like another user has encountered this error:

http://stackoverflow.com/questions/42333827/error-scraping-data-from-yahoo-finance

**Comment by tavito** [comment]
It started working again! I did not have to do anything about it. Thank you!

**Comment by jefftham** [comment]
NO. it happens again. Both yahoo and google is NOT working now.

**Comment by cptbrkfst** [comment]
Hey everyone,

So I was looking into this, and came up with the hackiest solution ever. BRK-B and BF-B were listed on wikipedia as BRK.B and BF.B, respectively. A lot of people were scraping the ticker list directly from Wikipedia, so I edited the names to line up with Yahoo and everything is working for me now!

**Comment by arkilis** [comment]
Still not working. The issue happens occasionally.

**Comment by SutharMukesh** [comment]
did anyone get any solution?

I've created a script to download historical data for a bunch of stocks.
the for loop just breaks in between with this error. 

RemoteDataError: Unable to read URL: https://query1.finance.yahoo.com/v7/finance/download/BAC?period1=1427826600&period2=1522693800&interval=1d&crumb=b2hWv%5Cu002F6x.l2&events=history

agreed to @arkilis

**Comment by aldsouza4** [comment]
Facing this problem in 2021 july Now

**Comment by KatieMarsh** [comment]
how long does it usually take to get back to working again?

**Comment by lefteyecct** [comment]
can't believe it worked ever?

**Comment by lefteyecct** [comment]
![image](https://user-images.githubusercontent.com/72097215/124271340-41e1d180-db35-11eb-8bbd-e2facb773f09.png)

**Comment by AndrianAru** [comment]
The following version should still work
```
from datetime import datetime
import yfinance as yf
import pandas_datareader.data as pdr
import pandas as pd

yf.pdr_override()

start_date = datetime.strptime('2011-01-01', '%Y-%m-%d')
end_date = datetime.strptime('2020-01-01', '%Y-%m-%d')

sp500 = pdr.DataReader("^GSPC", 'yahoo', start, end)['Adj Close']
```

**Comment by TheR3njithR** [comment]
its still down :(

**Comment by abdulvaseem123** [comment]
How much time does it take still down!!!!!!!!!!!!!

**Comment by maximilianreisinger** [comment]
Still down right??

**Comment by abdulvaseem123** [comment]
Yes, Still Down

**Comment by TheR3njithR** [comment]
seems like the wait is forever

**Comment by akhil14shukla** [comment]
mine is still down!!

**Comment by lefteyecct** [comment]
I download the dataset from yahoo finance as a workaround if this helps anyone here

**Comment by gho21** [comment]
still getting the error

**Comment by NewCodingStudent** [comment]
Does anyone know how to write AndrianAru's code to CSV? Thank you!

I tried this, but it didn't work...

sp500[["Adj Close"]].to_csv (r'C:\Users\j\export_dataframe.csv')

**Comment by gho21** [comment]
```
pdr.get_data_yahoo("^GSPC", start, end)['Adj Close'].to_csv('GSPC.csv')
```

**Comment by NewCodingStudent** [comment]
Thank you AndrianAru & gho21. It worked!

**Comment by abdulvaseem123** [comment]
kindly please let me know if anyone able to extract todays data from yf ??

**Comment by PhilEats** [comment]
As AndrianAru & gho21 pointed out before, you can try using this. In my case everything worked fine with this codeline:

```
import yfinance as yf
import pandas_datareader.data as pdr

yf.pdr_override()

ticker = 'TSLA'
start_date = '01-01-2010'
end_date = '03-07-2021'


def download_data(symbol, source, start_date, end_date):
    start = datetime.strptime(start_date, '%d-%m-%Y')
    end = datetime.strptime(end_date, '%d-%m-%Y')
    df = pdr.get_data_yahoo(symbol, data_source=source, start=start, end=end)
    return df
```

**Comment by jcsvpn** [comment]
Pulling data for baba
Error:  Unable to read URL 

getting this error from yesterday. Can anyone help me?

**Comment by burkart-analytics** [comment]
Try the AndrianAru  solution (the problem is the date format):

import yfinance as yf
import pandas_datareader.data as pdr

yf.pdr_override()

start_date = '01-01-2010'
end_date = '03-07-2021'

start = datetime.strptime(start_date, '%d-%m-%Y')
end = datetime.strptime(end_date, '%d-%m-%Y')
df = pdr.get_data_yahoo('AAPL', data_source='yahoo', start=start, end=end)
df

**Comment by Johnnyttw** [comment]
> Try the AndrianAru solution (the problem is the date format):
> 
> import yfinance as yf
> import pandas_datareader.data as pdr
> 
> yf.pdr_override()
> 
> start_date = '01-01-2010'
> end_date = '03-07-2021'
> 
> start = datetime.strptime(start_date, '%d-%m-%Y')
> end = datetime.strptime(end_date, '%d-%m-%Y')
> df = pdr.get_data_yahoo('AAPL', data_source='yahoo', start=start, end=end)
> df

TKS a lot. it can work.

**Comment by echoround** [comment]
> Try the AndrianAru solution (the problem is the date format):
> 
> import yfinance as yf
> import pandas_datareader.data as pdr
> 
> yf.pdr_override()
> 
> start_date = '01-01-2010'
> end_date = '03-07-2021'
> 
> start = datetime.strptime(start_date, '%d-%m-%Y')
> end = datetime.strptime(end_date, '%d-%m-%Y')
> df = pdr.get_data_yahoo('AAPL', data_source='yahoo', start=start, end=end)
> df

Had exact same issue as above and this seems to work! Right now, at least

**Comment by ashraf999** [comment]
I am getting the same error. Is this service down now?

**Comment by akhil14shukla** [comment]
Code by AndrianAru is working fine. Try with that one!

**Comment by aldsouza4** [comment]
hope AndrianAru's code dosent stop working too
i made a website out of this http://stock-toolkit.herokuapp.com/ 
do check it if u got the time 
ps its for indian stocks only

**Comment by ithotline** [comment]
Code by AndrianAru did not work for me - Below code did thoug:

import yfinance as yf

import pandas as pd

data = yf.download("Ticker_Symbol", period ="1d")

**Comment by burkart-analytics** [comment]
@ithotline try the code below, because without the "tail" its returning two lines, I test it in google colab and works fine 

data = yf.download("AAPL", period ="1d").tail(1)

**Comment by datatalking** [comment]
Please read the stack trace... <p id="message-2">Our engineers are working quickly to resolve the issue.</p>

**Comment by abdulvaseem123** [comment]
yfinance is not working for me. Is it working for anyone??

**Comment by BajajAryan310** [comment]
Yes, it is working for me

**Comment by abdulvaseem123** [comment]
I am getting this error, kindly please help me why is this error

Exception in thread Thread-6:
Traceback (most recent call last):
  File "c:\users\eigennet llc\appdata\local\programs\python\python37\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "c:\users\eigennet llc\appdata\local\programs\python\python37\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\eigennet llc\appdata\local\programs\python\python37\lib\site-packages\multitasking\__init__.py", line 102, in _run_via_pool
    return callee(*args, **kwargs)
  File "c:\users\eigennet llc\appdata\local\programs\python\python37\lib\site-packages\yfinance\multi.py", line 167, in _download_one_threaded
    actions, period, interval, prepost, proxy, rounding)
  File "c:\users\eigennet llc\appdata\local\programs\python\python37\lib\site-packages\yfinance\multi.py", line 182, in _download_one
    rounding=rounding, many=True)
  File "c:\users\eigennet llc\appdata\local\programs\python\python37\lib\site-packages\yfinance\base.py", line 156, in history
    data = data.json()
  File "c:\users\eigennet llc\appdata\local\programs\python\python37\lib\site-packages\requests\models.py", line 900, in json
    return complexjson.loads(self.text, **kwargs)
  File "c:\users\eigennet llc\appdata\local\programs\python\python37\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "c:\users\eigennet llc\appdata\local\programs\python\python37\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "c:\users\eigennet llc\appdata\local\programs\python\python37\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by aldsouza4** [comment]
Yfinance not working for me too

**Comment by aldsouza4** [comment]
> Please read the stack trace... <p id="message-2">Our engineers are working quickly to resolve the issue.</p>

U talking about yfinance or yahoo finance ?

**Comment by ardaozdemir** [comment]
> Try the AndrianAru solution (the problem is the date format):
> 
> import yfinance as yf
> import pandas_datareader.data as pdr
> 
> yf.pdr_override()
> 
> start_date = '01-01-2010'
> end_date = '03-07-2021'
> 
> start = datetime.strptime(start_date, '%d-%m-%Y')
> end = datetime.strptime(end_date, '%d-%m-%Y')
> df = pdr.get_data_yahoo('AAPL', data_source='yahoo', start=start, end=end)
> df

It was working until today, but it doesn't work now. Is it the same for you?

**Comment by Johnnyttw** [comment]
> > Try the AndrianAru solution (the problem is the date format):
> > import yfinance as yf
> > import pandas_datareader.data as pdr
> > yf.pdr_override()
> > start_date = '01-01-2010'
> > end_date = '03-07-2021'
> > start = datetime.strptime(start_date, '%d-%m-%Y')
> > end = datetime.strptime(end_date, '%d-%m-%Y')
> > df = pdr.get_data_yahoo('AAPL', data_source='yahoo', start=start, end=end)
> > df
> 
> It was working until today, but it doesn't work now. Is it the same for you?

bad news, as same as me, what's going on?

**Comment by rizkiyansyah** [comment]
> Try the AndrianAru solution (the problem is the date format):
> 
> import yfinance as yf
> import pandas_datareader.data as pdr
> 
> yf.pdr_override()
> 
> start_date = '01-01-2010'
> end_date = '03-07-2021'
> 
> start = datetime.strptime(start_date, '%d-%m-%Y')
> end = datetime.strptime(end_date, '%d-%m-%Y')
> df = pdr.get_data_yahoo('AAPL', data_source='yahoo', start=start, end=end)
> df


raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by dustinpeng** [comment]
> > Try the AndrianAru solution (the problem is the date format):
> > import yfinance as yf
> > import pandas_datareader.data as pdr
> > yf.pdr_override()
> > start_date = '01-01-2010'
> > end_date = '03-07-2021'
> > start = datetime.strptime(start_date, '%d-%m-%Y')
> > end = datetime.strptime(end_date, '%d-%m-%Y')
> > df = pdr.get_data_yahoo('AAPL', data_source='yahoo', start=start, end=end)
> > df
> 
> raise JSONDecodeError("Expecting value", s, err.value) from None
> json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

same issue as rizkiyansyah

**Comment by dustinpeng** [comment]
solved by pip install yfinance --upgrade
Upgrade yfinance to 0.1.63

**Comment by Johnnyttw** [comment]
> solved by pip install yfinance --upgrade
> Upgrade yfinance to 0.1.63

yes, it can work. TKS a lot

**Comment by theGadgetplayer** [comment]
I have tried all suggestions, still down on my side :(

Pls Help

**Comment by bashtage** [comment]
What version are you using?  Run

```
pip uninstall pandas-datareader -y
# Again, to be sure
pip uninstall pandas-datareader -y
pip install pandas-datareader -U
```

**Comment by aldsouza4** [comment]
> I have tried all suggestions, still down on my side :(
> 
> Pls Help

Send your code here I'll try to help

**Comment by aldsouza4** [comment]
> What version are you using?  Run
> 
> ```
> pip uninstall pandas-datareader -y
> # Again, to be sure
> pip uninstall pandas-datareader -y
> pip install pandas-datareader -U
> ```
> 

Pandas_datareader don't work anymore. ... That's done fam

**Comment by bashtage** [comment]
0.10.0 was released yesterday with support for Yahoo fixed.

**Comment by theGadgetplayer** [comment]
> What version are you using? Run
> 
> ```
> pip uninstall pandas-datareader -y
> # Again, to be sure
> pip uninstall pandas-datareader -y
> pip install pandas-datareader -U
> ```

Thanks, that seems to have fixed the problem :D appreciate the help
