### ISSUE TITLE
dependencies (html5lib) 

### ISSUE THREAD

**Issue by DaveBackus** [pydata/pandas-datareader#171]
I suspect this is a naive suggestion, but here's the issue.  I'm teaching a course to newbies (data + python) that uses the datareader a lot.  We started with Anaconda, which includes pandas, then installed datareader with conda.  

**It didn't work because we didn't have html5lib installed.**  Which was easy to fix once we figured it out.  But would it make sense to add a check?  The code already gives a message referring to html5lib, but it's buried in the traceback.  There are probably similar dependencies elsewhere that might get similar treatment.   

The context here is that this is a terrific tool and I can see it used by lots of people, including many who are not experienced coders.  

**Specifics.**  This refers to the Yahoo options module.  

``` python
import pandas_datareader.yahoo.options as yho

ticker = 'amzn'
otk = yho.Options(ticker)

cols = [0, 1, 2, 7]
ops = otk.get_all_data()[cols]
```

**Comment by femtotrader** [comment]
`lxml` is an optional dependency for Pandas DataReader but is required for Yahoo Options
see https://github.com/pydata/pandas-datareader/blob/master/pandas_datareader/yahoo/options.py#L665

Maybe we should
- either improve `setup.py` to be more explicit about it (`extras_require` might help - see https://pythonhosted.org/setuptools/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies)
- or add `lxml` to dependencies

We have to weight the pros and cons of each solution

**Comment by bashtage** [comment]
This is now a requirement.
