### ISSUE TITLE
REL: 0.3.0

### ISSUE THREAD

**Issue by davidastephens** [pydata/pandas-datareader#173]
- [ ] Move tests for Python 2.6 and 3.3 to allowed failures
- [ ] Remove Python 2.6 and 3.3 workarounds

**Comment by femtotrader** [comment]
Maybe we should put in doc a table with current status of each data source.
We should probably also define maintainer(s) per data source

|Data source name|Status|Maintainers|
| ----------- |------ | -----|
|yahoo|||
|yahoo-actions|||
|yahoo-dividends|||
|yahoo-dividends|||
|google|||
|fred|||
|famafrench|||
|oecd|||
|eurostat|||
|edgar-index|||
|yahoo-options|Broken #212||
|google-options|||

**Comment by femtotrader** [comment]
Any news about this ?

@sinhrks @davidastephens

**Comment by sinhrks** [comment]
+1 for releasing 0.3, adding pandas 0.19.0 support.

**Comment by davidastephens** [comment]
Any objections to a new release?  A lot of things are broken with the previous release, so people can't use pip.  I'm happy to deal with putting it together.

**Comment by gfyoung** [comment]
@jreback : `0.3.0` was released back in January.  Not sure why this is still open.
