### ISSUE TITLE
Google Quote shouldn't return a DataFrame and should be documented

### ISSUE THREAD

**Issue by femtotrader** [pydata/pandas-datareader#184]
Hello,

```
In [3]: pdr.get_quote_google(['MSFT', 'F'])
Out[3]:
          0
MSFT  51.30
F     12.47
```

Google Quote shouldn't return a DataFrame but either a Series or a dict

Moreover some doc is necessary.

Pinging @gliptak 

Kind regards

**Comment by femtotrader** [comment]
`GoogleQuotesReader` should also be available through `DataReader` function

maybe we should use `google-quote` as `data_source`

**Comment by gliptak** [comment]
@femtotrader Added docs with https://github.com/pydata/pandas-datareader/pull/188

**Comment by gliptak** [comment]
Implemented.

**Comment by femtotrader** [comment]
Thanks @gliptak for this also.
I'm closing this issue as your PR is merged.
