### ISSUE TITLE
ENH: Google Finance Intraday DataReader

### ISSUE THREAD

**Issue by femtotrader** [pydata/pandas-datareader#185]
Hello,

A Google Finance Intraday DataReader might be an interesting feature.

See https://github.com/quantopian/zipline/issues/215#issuecomment-189955990
and an implementation https://github.com/femtotrader/pandas_datareaders_unofficial/blob/master/pandas_datareaders_unofficial/datareaders/google_finance_intraday.py which should be slightly modified.

Kind regards

**Comment by femtotrader** [comment]
Work In Progress

I'm working on this here:
https://github.com/femtotrader/pandas-datareader/tree/google_intraday

**Comment by bashtage** [comment]
As of v0.7.0 Google finance and Morningstar have been immediately deprecated due to large changes in their API and no stable replacement.
