### ISSUE TITLE
How to get Shanghai Exchange Stock data from google finance through pandas-datareader

### ISSUE THREAD

**Issue by extremewaysback** [pydata/pandas-datareader#194]
How to parse Shanghai Exchange Stock Code into google finance ticker and get the data.

Like:

<pre><code>
from pandas_datareader import data
from datetime import date, timedelta

today=date.today()
previous=today-timedelta(10)
goog=data.DataReader("AAPL", 'google', previous, today)
</code></pre>

But using code of Shanghai Exchange Stock instead of "AAPL" don't work for [SHA:600610](https://www.google.com/finance?q=600610&ei=4u0KV4HuBYua0ATn06jIAQ):

```
goog=data.DataReader("600610", 'google', previous, today)
```

**Comment by zezhou** [comment]
I use [Tushare](https://github.com/waditu/tushare) to get Shanghai Exchange Stock data instead of pandas-datareader.

**Comment by extremewaysback** [comment]
@zezhou Thanks

**Comment by bashtage** [comment]
As of v0.7.0 Google finance and Morningstar have been immediately deprecated due to large changes in their API and no stable replacement.

**Comment by hack-r** [comment]
Related... https://opendata.stackexchange.com/questions/13318/open-shanghai-stock-exchange-data-api  .... maybe someday we can have this data?
