### ISSUE TITLE
Unable to get SGX stocks quote

### ISSUE THREAD

**Issue by bkcollection** [pydata/pandas-datareader#195]
I found that some of the stock exchanges is not supported for datareader. Example, SInagpore. Any fix for it? 
``query = web.DataReader(("SGX:BLA"), 'google', start, now)` return such error`

`IOError: after 3 tries, Google did not return a 200 for url 'http://www.google.com/finance/historical?q=SGX%3ABLA&startdate=Jan+01%2C+2015&enddate=Apr+20%2C+2016&output=csv`

It works for IDX indonesia
`query = web.DataReader(("IDX:CASS"), 'google', start, now)`

**Comment by dcgithubaccount** [comment]
why can't you use yahoo to get sgx data?

`f = web.DataReader('A17U.SI', 'yahoo', start, end)`

**Comment by bashtage** [comment]
As of v0.7.0 Google finance and Morningstar have been immediately deprecated due to large changes in their API and no stable replacement.
