### ISSUE TITLE
Docs bug

### ISSUE THREAD

**Issue by andportnoy** [pydata/pandas-datareader#197]
The [usage examples](http://pandas-datareader.readthedocs.org/en/latest/remote_data.html#yahoo-finance-options) for Yahoo Finance options contain a couple errors.

**Comment by femtotrader** [comment]
Thanks for reporting this issue.
But I think it's a duplicate of https://github.com/pydata/pandas-datareader/issues/150

**Comment by andportnoy** [comment]
Oh, that's right. I'll see if I can replicate the error.

**Comment by femtotrader** [comment]
Thanks
