### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by femtotrader** [pydata/pandas-datareader#2]
I want to use [Sourcegraph code search and code review](https://sourcegraph.com) with pandas-datareader. A project maintainer needs to enable it to set up a webhook so the code is up-to-date there.

Could you please enable pandas-datareader on @Sourcegraph by going to https://sourcegraph.com/github.com/pydata/pandas-datareader and clicking on Settings? (It should only take 15 seconds.)

Thank you!

**Comment by jorisvandenbossche** [comment]
@femtotrader you are added as a contributor to this repo, so I think you can do it yourself?

**Comment by femtotrader** [comment]
Sorry but I get the following message on Sourcegraph
https://sourcegraph.com/github.com/pydata/pandas-datareader/.settings

    Only repository admins can view or edit settings.
    Ask the owner to enable this repository.

**Comment by jorisvandenbossche** [comment]
ah, ok, then @jreback will have to do it

**Comment by jreback** [comment]
done

**Comment by femtotrader** [comment]
Thanks
