### ISSUE TITLE
Fama French Factors keys should be descriptive

### ISSUE THREAD

**Issue by MichaelWS** [pydata/pandas-datareader#20]
web.DataReader('F-F_Momentum_Factor', 'famafrench') returns a dict of 1,2 pointing to monthly, annual data.  
I believe the dicts should indicate about the data.
https://github.com/pydata/pandas/issues/8842

**Comment by jreback** [comment]
can u add a link to the oandad issue as well thxs

**Comment by davidastephens** [comment]
I believe this was fixed with #56, please reopen if not.
