### ISSUE TITLE
COMPAT: pandas private API

### ISSUE THREAD

**Issue by jreback** [pydata/pandas-datareader#202]
So making some changes here that could potentially break some of the de-facto private API: https://github.com/pydata/pandas/pull/13147

IOW if doing:

```
from pandas.core import common as pdcom

pdcom.is_categorical()
```

for example. This _wont'_ break now as I left it in the namespace, but we are migrating to 
``pandas.api` for these types of things. However we won't be able to issue a deprecation warning probably to the next version.

**Comment by gfyoung** [comment]
Update: #13147 has been merged, though in the interests of backwards compatibility, I don't imagine much can be done on this end unless we want to add some not-so-nice `try-except` blocks.

**Comment by bashtage** [comment]
This doesn't appear to be an issue.
