### ISSUE TITLE
ME breakpoints in fama french factors library

### ISSUE THREAD

**Issue by MichaelWS** [pydata/pandas-datareader#21]
ME_breakpoints.zip is not read because it is a different format.  

ME breakpoints includes the breakpoints between the deciles of market cap.   For example, what is the 5%, 10%, etc.
http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/data_library.html#Breakpoints

**Comment by davidastephens** [comment]
@MichaelWS  Does this work now? Closing this issue, reopen if still broken.

**Comment by MichaelWS** [comment]
No, how do we want to add a test for this?
The format is different from the rest and needs a PR to fix it.

**Comment by MichaelWS** [comment]
I am happy to handle this.  How would we test for web?

**Comment by davidastephens** [comment]
@MichaelWS is this still a problem? #116 did some work on Fama French.

**Comment by MichaelWS** [comment]
This is resolved. #116 fixed it
