### ISSUE TITLE
Add FXCM Speculative Sentiment Index

### ISSUE THREAD

**Issue by femtotrader** [pydata/pandas-datareader#221]
This data source could be add to pandas-datareader according @BryanFletcher from FXCM
see https://github.com/quantopian/zipline/issues/1285#issuecomment-237350801

``` python
import requests
import pandas as pd
pd.set_option("max_rows", 10)

def _sanitize_dates(start, end):
    start = pd.to_datetime(start)
    end = pd.to_datetime(end)
    return start, end

def _init_session(session):
    if session is None:
        session = requests.Session()
    return session

def split_pair(s, sep="/"):
    if len(s) == 6:
        return sep.join([s[:3], s[3:]])
    else:
        return s

try:
    from StringIO import StringIO
except ImportError:
    from io import StringIO

def get_fxcm_ssi(start=None, end=None, normalize=False, session=None):
    url = "https://apiwiki.fxcorporate.com/api/daily.csv"
    session = _init_session(session)
    start, end = _sanitize_dates(start, end)
    response = session.get(url)

    df_ssi_raw = pd.read_csv(StringIO(response.text), parse_dates=[[0,1]])
    df_ssi_raw = df_ssi_raw.rename(columns={
        "DATE_TIME": "Date",
        "SYMBOL": "Symbol"
    })
    df_ssi_raw["Symbol"] = df_ssi_raw["Symbol"].map(split_pair)
    # ssi_by_symbol = df_ssi_raw.set_index(["Symbol", "Date"])["SSI"]  # time series
    # ssi_by_date = df_ssi_raw.set_index(["Date", "Symbol"])["SSI"]  # time series
    df_ssi = df_ssi_raw.pivot(index="Date", columns="Symbol", values="SSI")
    if normalize:
        df_ssi.index = df_ssi.index.normalize()
    return df_ssi[start:end]

import requests_cache  # for caching
import datetime
expire_after = datetime.timedelta(days=1)
session = requests_cache.CachedSession(cache_name='cache', backend='sqlite', expire_after=expire_after)
start = "2016-01-01"
end = "2016-06-01"
df_ssi = get_fxcm_ssi(start, end)
```

`df_ssi` looks like

```
Symbol      AUD/USD  EUR/USD  GBP/USD  NZD/USD  USD/CAD  USD/CHF  USD/JPY
Date
2016-01-01  -1.3124  -1.1838   2.7333  -1.7949  -2.7234   1.8630   2.0529
2016-01-04   1.0547  -1.1104   2.7149  -1.5447  -3.7721   1.7051   1.9443
2016-01-05   1.1124   1.0868   2.7776  -1.3370  -3.8327   1.5645   2.3811
2016-01-06   1.3319  -1.1358   2.8503  -1.2270  -3.7842   1.6419   2.2386
2016-01-07   1.4622  -1.5113   2.6541  -1.1674  -3.2204   1.8510   2.4686
...             ...      ...      ...      ...      ...      ...      ...
2016-05-26   1.7355   1.0449  -1.1944   1.1629   1.1983   1.4582   1.5325
2016-05-27   2.1557   1.2165  -1.0554   1.4155   1.2583   1.5920   1.4802
2016-05-30   1.9767   1.0322  -1.0148   1.2816   1.2602   1.6619   1.4379
2016-05-31   1.7567   1.1336   1.2780   1.0425   1.1192   1.5844   1.5711
2016-06-01   1.8669  -1.1108   1.4929  -1.1369   1.1869   1.4772   2.0247

[109 rows x 7 columns]
```

**Comment by femtotrader** [comment]
With https://github.com/pydata/pandas-datareader/issues/222 we can for example plot SSI and rates for a given pair

```python
import matplotlib.pyplot as plt
start = "2016-01-01"
end = "2016-06-01"
df_ssi = get_fxcm_ssi(start, end, normalize=True)
df_rates = get_oanda_currency_historical_rates(start, end, session=session)
pair = "EUR/USD"
pd.concat([df_ssi[pair], df_rates[pair]], axis=1).plot(subplots=True, legend=False)
plt.show()
```

![capture d ecran 2016-08-04 a 13 27 58](https://cloud.githubusercontent.com/assets/5049737/17400282/512d8946-5a47-11e6-91cb-9295607c7cab.png)

**Comment by femtotrader** [comment]
Unfortunately it doesn't seems to be updated daily.
Today last row is `7/28/2016,17:00,USDJPY,1.562`
Any idea why @BryanFletcher ?

**Comment by BryanFletcher** [comment]
Hi,

Here's an updated link: https://apiwiki.fxcorporate.com/api/daily_103116.csv


________________________________

**Comment by femtotrader** [comment]
Today I try to download yesterday data

https://apiwiki.fxcorporate.com/api/daily_110616.csv

but it doesn't seems to be updated on a regular daily basis.

**Comment by BryanFletcher** [comment]
Hi,

Currently, the only source of free real-time/historical SSI data would be via the following FXCM app, which was designed for the FXCM Trading Station, or real-time directly from DailyFX:

https://www.fxcmapps.com/apps/speculative-sentiment-index/
https://www.dailyfx.com/sentiment


Best regards,


Bryan Fletcher
Product Manager
Algorithmic Trading
Direct: (972) 535-9020
Email: bfletcher@fxcm.com<mailto:bfletcher@fxcm.com>


[fxcm]
________________________________
Trading forex/CFD's on margin carries a high level of risk and may not be suitable for all investors as you could sustain losses in excess of deposits. Leverage can work against you. Be aware and fully understand all risks associated with the market and trading. Prior to trading any products offered by Forex Capital Markets, LLC<https://www.fxcm.com/legal/trading-execution-risks/>, Forex Capital Markets Limited<https://www.fxcm.com/uk/legal/trading-execution-risks/>, inclusive of all EU branches, FXCM Australia Pty. Limited<https://www.forextrading.com.au/legal/trading-execution-risks/>, any affiliates of aforementioned firms, or other firms within the FXCM group of companies [collectively the “FXCM Group”], carefully consider your financial situation and experience level. If you decide to trade products offered by FXCM Australia Pty. Limited (“FXCM AU”) (AFSL 309763), you must read and understand the Financial Services Guide<http://docs.fxcorporate.com/financial-services-guide-au.pdf>, Product Disclosure Statement<https://www.forextrading.com.au/legal/product-disclosure-statements/>, and Terms of Business<http://docs.fxcorporate.com/tob_au_en.pdf>. The FXCM Group may provide general commentary which is not intended as investment advice and must not be construed as such. Seek advice from a separate financial advisor. The FXCM Group assumes no liability for errors, inaccuracies or omissions; does not warrant the accuracy, completeness of information, text, graphics, links or other items contained within these materials. Read and understand the Terms and Conditions on the FXCM Group’s websites prior to taking further action.

The FXCM Group is headquartered at 55 Water Street, 50th Floor, New York, NY 10041 USA. Forex Capital Markets, LLC ("FXCM LLC") is a registered Futures Commission Merchant and Retail Foreign Exchange Dealer with the Commodity Futures Trading Commission and is a member of the National Futures Association, NFA # 0308179. Forex Capital Markets Limited (“FXCM LTD”) is authorised and regulated in the UK by the Financial Conduct Authority. Registration number 217689. Registered in England and Wales with Companies House company number 04072877. FXCM Australia Pty. Limited (“FXCM AU”) is regulated by the Australian Securities and Investments Commission, AFSL 309763. FXCM AU ACN: 121934432. FXCM LLC is an Authorised Representative (Rep. No 402307) of FXCM AU. FXCM Markets Limited ("FXCM Markets") is an operating subsidiary within the FXCM Group. FXCM Markets is not regulated and not subject to the regulatory oversight that govern other FXCM Group entities, which includes but is not limited to, Commodity Futures Trading Commission, National Futures Association, Financial Conduct Authority, and the Australian Securities and Investments Commission. FXCM Global Services, LLC is an operating subsidiary within the FXCM Group. FXCM Global Services, LLC is not regulated and not subject to regulatory oversight.
________________________________

**Comment by femtotrader** [comment]
Thanks @BryanFletcher 
So I'm closing.
Feel free to reopen if access to this data is changing.
