### ISSUE TITLE
Oanda currency historical rates

### ISSUE THREAD

**Issue by femtotrader** [pydata/pandas-datareader#222]
Oanda currency historical rates could also be an interesting data source.

Here is some code:

```python
import requests
import pandas as pd
pd.set_option("max_rows", 10)
import pandas.compat as compat


def _sanitize_dates(start, end):
    start = pd.to_datetime(start)
    end = pd.to_datetime(end)
    return start, end

def _init_session(session):
    if session is None:
        session = requests.Session()
    return session

try:
    from StringIO import StringIO
except ImportError:
    from io import StringIO

def reverse_pair(s, sep="/"):
    lst = s.split(sep)
    return sep.join([lst[1], lst[0]])

def get_oanda_currency_historical_rates(start, end, quote_currency="USD", base_currency=None, reversed=True, session=None):
    session = _init_session(session)
    start, end = _sanitize_dates(start, end)

    url = "http://www.oanda.com/currency/historical-rates/download"
    bam = "bid"  # "ask", "mid"

    if base_currency is None:
        base_currency = ["EUR", "GBP", "AUD", "NZD", "CAD", "CHF"]
    elif isinstance(base_currency, compat.string_types):
        base_currency = [base_currency]

    params = {
        "quote_currency": quote_currency,
        "start_date": start.strftime("%Y-%m-%d"),
        "end_date": end.strftime("%Y-%m-%d"),
        "period": "daily",
        "display": "absolute",
        "rate": 0,
        "data_range": "c",
        "price": bam,
        "view": "table",
        "download": "csv"
    }
    for i, _base_currency in enumerate(base_currency):
        params["base_currency_%d" % i] = _base_currency

    response = session.get(url, params=params)
    skiprows = 4
    skipfooter = 4
    usecols = range(len(base_currency) + 1)
    df = pd.read_csv(StringIO(response.text), parse_dates=[0], skiprows=skiprows, skipfooter=skipfooter, usecols=usecols, engine='python')
    df = df.rename(columns={
        "End Date": "Date",
    })
    df = df.set_index("Date")
    df = df[::-1]
    if reversed:
        df.columns = pd.Index(df.columns.map(reverse_pair))
        df = 1 / df
    if len(base_currency) == 1:
        return df.iloc[:, 0]
    else:
        return df

import requests_cache  # for caching
import datetime
expire_after = datetime.timedelta(days=1)
session = requests_cache.CachedSession(cache_name='cache', backend='sqlite', expire_after=expire_after)
start = "2016-01-01"
end = "2016-06-01"
df_rates = get_oanda_currency_historical_rates(start, end, session=session)
```

`df_rates` looks like

```
             EUR/USD   GBP/USD   AUD/USD   NZD/USD   CAD/USD   CHF/USD
Date
2016-01-01  1.087090  1.473989  0.729469  0.683789  0.723019  1.000440
2016-01-02  1.087090  1.473989  0.729469  0.683789  0.723019  1.000440
2016-01-03  1.087090  1.473989  0.729469  0.683789  0.723019  1.000440
2016-01-04  1.086730  1.473481  0.721740  0.676801  0.719124  1.000490
2016-01-05  1.078760  1.469430  0.717901  0.672219  0.717283  0.994471
...              ...       ...       ...       ...       ...       ...
2016-05-28  1.111669  1.462630  0.718799  0.669842  0.767849  1.005591
2016-05-29  1.111669  1.462630  0.718799  0.669842  0.767849  1.005591
2016-05-30  1.112479  1.461999  0.717772  0.669492  0.765667  1.006472
2016-05-31  1.114269  1.461021  0.723061  0.673519  0.765732  1.008146
2016-06-01  1.115170  1.445410  0.725679  0.679948  0.764672  1.008929

[153 rows x 6 columns]
```

**Comment by davidandreoletti** [comment]
@femtotrader Looks like you already have the reader implemented (or partially implemented). However looking pandas-datareader, I don't see it. 

a) What's left to do to get this data source into pandas-datareader ?

**Comment by femtotrader** [comment]
Firstly I would like to know if some other people are interested by such data source.

Secondly, my code uses an imperative and non object approach... this is quite different from other datareader in pandas-datareader as I don't use class. (It looks like code that was written in pre pandas-datareader era (when it was part of `data.py` in [pandas](https://github.com/pydata/pandas) )

My opinion is that we should keep things simple and so I don't think we should make an inherited class for this... but that's just my opinion... and we have to measure pros and cons of each solution.

Pinging @sinhrks

**Comment by sinhrks** [comment]
i don't think OO impl is mandatory if it doesn't have a lot of common parts with existing one.

**Comment by praveenvaddimgunta** [comment]
ParserError: ',' expected after '"'. Error could possibly be due to parsing errors in the skipped footer rows (the skipfooter keyword is only applied after Python's csv library has parsed all rows).

**Comment by praveenvaddimgunta** [comment]
Hi,

When I am using pandas-datareader to fetch the Oanda currency historical rate using the following code 

from pandas_datareader.oanda import get_oanda_currency_historical_rates
start, end = "2016-01-01", "2016-06-01"
quote_currency = "USD"
base_currency = ["EUR", "GBP", "JPY"]
df_rates = get_oanda_currency_historical_rates(
            start, end,
            quote_currency=quote_currency,
            base_currency=base_currency
        )
print(df_rates)

I am getting the following error
**ParserError**: ',' expected after '"'. Error could possibly be due to parsing errors in the skipped footer rows (the skipfooter keyword is only applied after Python's csv library has parsed all rows).
