### ISSUE TITLE
EDGAR not implemented

### ISSUE THREAD

**Issue by rontho1992** [pydata/pandas-datareader#223]
I'm trying to pull in the full data from Edgar using 

```
import pandas_datareader.data as pdr
df = pdr.DataReader("daily", "edgar-index")
```

and getting the following error:

```
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
<ipython-input-228-98f3555ccfb0> in <module>()
----> 1 pdr.DataReader("full", "edgar-index")

C:\Anaconda2\envs\rodeo\lib\site-packages\pandas_datareader\data.pyc in DataReader(name, data_source, start, end, retry_count, pause, session)
    125     else:
    126         raise NotImplementedError(
--> 127                 "data_source=%r is not implemented" % data_source)
    128 
    129 

NotImplementedError: data_source='edgar-index' is not implemented
```

Thanks

**Comment by femtotrader** [comment]
Hi @rontho1992 

Are you sure you are using latest master version ?

I suggest to uninstall your version

`conda uninstall pandas-datareader`

or 

`pip uninstall pandas-datareader`

insure that it was uninstalled correctly by running ipython

`import pandas_datareader` might raises `ImportError`

and install

`pip install git+https://github.com/pydata/pandas-datareader.git`

**Comment by rontho1992** [comment]
Thanks @femtotrader looks like I was using an outdated version.

**Comment by pinktoadette** [comment]
doesn't work. im having the same issues too; uninstalled and installed.

**Comment by PLAYER69** [comment]
I'm having the same issue. 

import pandas_datareader.data as web
start = dt.datetime(2015, 1, 1)
end = dt.datetime.now()
df = web.DataReader("TSLA", 'morningstar', start, end)

NotImplementedError: data_source='morningstar' is not implemented

I have done uninstall and install of Datareader but same issue

**Comment by hanumancode** [comment]
If you're having an issue with "data_source='morningstar' is not implemented" try this to resolve it:

pip install git+https://github.com/pydata/pandas-datareader.git

**Comment by Elvissmf** [comment]
Estou tentando usar esse procedimento porem tenho o seguinte erro

content-type: text/html; charset=utf-8); cannot detect archive format

ERROR: Cannot determine archive format of C:

Consegue me ajudar
