### ISSUE TITLE
CUSIP lookup

### ISSUE THREAD

**Issue by twiecki** [pydata/pandas-datareader#225]
I think Yahoo supports lookup by CUSIP number. Any chance pandas-datareader would support that?

**Comment by femtotrader** [comment]
According Wikipedia CUSIP article https://en.wikipedia.org/wiki/CUSIP

- Apple Inc.: 037833100
- Cisco Systems: 17275R102
- Google Inc.: 38259P508
- Microsoft Corporation: 594918104
- Oracle Corporation: 68389X105

Pandas DataReader use API calls like

http://ichart.finance.yahoo.com/table.csv?e=2&c=2010&d=8&b=1&g=d&a=0&f=2016&ignore=.csv&s=AAPL

but changing such a call to 

http://ichart.finance.yahoo.com/table.csv?e=2&c=2010&d=8&b=1&g=d&a=0&f=2016&ignore=.csv&s=037833100

raises a 404 page error.

but maybe that's a different parameter than "s".

Any idea ?

**Comment by twiecki** [comment]
Hm, yeah, I thought I had found an API but doesn't seem to work after all, alas.
