### ISSUE TITLE
Google CSV API Deprecated

### ISSUE THREAD

**Issue by davidastephens** [pydata/pandas-datareader#23]
It looks like Google has dropped their finance API.

https://developers.google.com/finance/?csw=1

``` python
import pandas.io.data as web
web.DataReader('gs','google')

IOError: after 3 tries, Google did not return a 200 for url 'http://www.google.com/finance/historical?q=gs&startdate=Jan+01%2C+2010&enddate=Mar+24%2C+2015&output=csv'
```

Anyone else having this issue? Tests that use Google in pandas-datareader are failing now.   We may have to remove Google finance support.

**Comment by chrish42** [comment]
I've run into the same problem trying to run all the tests. The link for downloading Google Finance data to csv (after setting a date range on the web page) looks like this:

http://www.google.com/finance/historical?cid=663137&startdate=Apr+15%2C+2014&enddate=Apr+14%2C+2015&num=30&ei=LD8tVbGfGszLigKAx4HADQ&output=csv

The ei parameter is actually not required (the URL still works without it), but the cid one is. I assume that cid one relates to the ticker name.

**Comment by chrish42** [comment]
Simply substituting "NYSE%3AGS" for "GS" in the old URL (http://www.google.com/finance/historical?q=GS&startdate=Jan+01%2C+2010&enddate=Apr+14%2C+2015&output=csv) makes thing works again. It looks like Google Finance now refuses to guess from which stock market a ticker is.

**Comment by chrish42** [comment]
Going to the following URL (https://www.google.com/finance?q=gs&output=json) returns something JSON-ish (although it does not validate), that contains information about the exchange(s) for this search query.

This could be used to make the old queries work with the new code, at the code of an additional query. If there is no "exchange + :" before the ticker, do a search query. If there is more than one result returned, raise an exception. If there is only one, use that exchange in the data download URL.

**Comment by hayd** [comment]
Is this fixed now? I can run the above without warnings.

**Comment by davidastephens** [comment]
It doesn't work for me.  I think its because I'm in Canada, it does work if I specify NYSE%3AGS.
