### ISSUE TITLE
get_components_yahoo raising eroors

### ISSUE THREAD

**Issue by jingdayan** [pydata/pandas-datareader#238]
When I run the following codes 
`from pandas_datareader import data`
`data.get_components_yahoo('^DJI')`
I always get an error 'AssertionError: 3 columns passed, passed data had 1 columns'.  Could anyone tell me why?

**Comment by gfyoung** [comment]
Still a problem on `master`.  Appears that the data returned is in an invalid format for `pandas` `DataFrame`.

**Comment by bashtage** [comment]
Yahoo has been deprecated.
