### ISSUE TITLE
Google historical prices not working for Canadian (TSE) stocks

### ISSUE THREAD

**Issue by doncristobal** [pydata/pandas-datareader#239]
``` python
import pandas_datareader.data as web

# This request for historical price data from Google Finance for a US stock works just fine:
result = web.DataReader('AAPL', 'google', start='1970-01-01')

# But for Canadian (TSE) stocks, it fails with: pandas_datareader._utils.RemoteDataError: Unable to read URL: http://www.google.com/finance/historical
result = web.DataReader('TSE:AZR', 'google', start='1970-01-01')
```

The problem is that pandas_datareader calls Google Finance with the parameter `"output=csv"`. The parameter `output=csv` is however not supported for all stock exchanges, apparently, as also pointed out in this stackoverflow post:

"However, this `format=csv` option does not work for a few stock exchanges." (http://stackoverflow.com/questions/11516633/how-to-work-with-google-finance)

Potential solution: The data is available, just not in CSV format, as can be seen here:
https://www.google.com/finance/historical?q=tse:azr&startdate=Sep%2016%2C%201970&start=0&num=9999
Parsing the page is certainly possible, even though I haven't quite found out yet how you can show more than 200 dates on one page. Currently it looks like you would have to parse several pages, which looks not very attractive.

**Comment by bashtage** [comment]
As of v0.7.0 Google finance and Morningstar have been immediately deprecated due to large changes in their API and no stable replacement.
