### ISSUE TITLE
Dead link in World Bank API doc

### ISSUE THREAD

**Issue by adrivsh** [pydata/pandas-datareader#240]
This page

http://pandas.pydata.org/pandas-docs/stable/remote_data.html#country-codes

has a link "as well as dynamic World Bank exceptions to the ISO standards" to "http://data.worldbank.org/node/18". That latter page does not exist. I suggest changing to:  "https://datahelpdesk.worldbank.org/knowledgebase/articles/898590-api-country-queries"

Sorry, I cannot and will not propose a pull request for this.

**Comment by femtotrader** [comment]
Thanks @adrivsh
