### ISSUE TITLE
ticker for index

### ISSUE THREAD

**Issue by ben388** [pydata/pandas-datareader#242]
Hi all,

I can not get the any index via datareader. 

the following URL request has returns in Chrome.
https://www.google.com/finance/historical?q=.inx

but call DataReader with ( ".INX", ...) has the following error:

 .INX Failed to get data
Unable to read URL: http://www.google.com/finance/historical

Hope you can help.

Thanks

**Comment by femtotrader** [comment]
Hi,

Please install latest development version https://github.com/pydata/pandas-datareader/issues/243

You might see more easily what kind of problem it is (thanks to https://github.com/pydata/pandas-datareader/issues/216 )

Kind regards

**Comment by bashtage** [comment]
As of v0.7.0 Google finance and Morningstar have been immediately deprecated due to large changes in their API and no stable replacement.
