### ISSUE TITLE
Move pandas-datareader from pydata to pandas-dev ?

### ISSUE THREAD

**Issue by femtotrader** [pydata/pandas-datareader#253]
Hello,

pandas-datareader is currently a repository which is part of [pydata](https://github.com/pydata) organization.

https://github.com/pydata/pandas-datareader/

Maybe we should move it to [pandas-dev](https://github.com/pandas-dev) ?

https://github.com/pandas-dev/pandas-datareader/

Pinging @wesm @jreback @sinhrks @jorisvandenbossche 

Your opinion ?

**Comment by davidandreoletti** [comment]
@femtotrader Link dead: https://github.com/pandas-dev/pandas-datareader/

**Comment by femtotrader** [comment]
Thanks @davidandreoletti I know this.

If we move this repository to pandas-dev,

pandas-datareader will be available using https://github.com/pandas-dev/pandas-datareader/

but I haven't credentials to move it.

That's the reason why I was pinging some people who are allowed to do this.

**Comment by jorisvandenbossche** [comment]
Personally, I don't think it is needed to move the repo. I think the location in the pydata org is fine, and not worth the trouble to move.

**Comment by gliptak** [comment]
So would this repo stay at this current place?

The grouping of repos between pandas-dev and pydata isn't very clear, for example

https://github.com/pandas-dev/pandas-website (repo for http://pandas.pydata.org/)

https://github.com/pydata/pandas.pydata.org (empty repo)

**Comment by jreback** [comment]
this repo will stay here for now. we are considering creating a new repo, maybe ``pandas-io`` where things could be consolidated at some point.

**Comment by wesm** [comment]
As some extra context the problems we are having with GitHub orgs is mainly our CI capacity which is org-specific. So if we create more pandas orgs we will be able to run more jobs in parallel

**Comment by gliptak** [comment]
@wesm Maybe TravisCI would be open to assign additional executors?

**Comment by wesm** [comment]
Not without paying more money (we are already paying to increase capacity for pandas pull requests), I don't think.

**Comment by gliptak** [comment]
Details from Travis support:

"The normal, free package gives you five concurrent jobs (which equals five concurrent workers, so to speak).

Beyond that, the next step up includes 10 extra concurrent jobs, effectively raising the limit to 15, for $500/month, paid annually and in advance."

I do not have details on other CI offerings availed to OSS projects.

**Comment by jreback** [comment]
@gliptak I don't think we need the capacity for datareader ATM. In any event I think still thinking about where if/any place to move this repo.

**Comment by bashtage** [comment]
No reason to do this.
