### ISSUE TITLE
Unable to load special German index over Google

### ISSUE THREAD

**Issue by GitHubUser2014** [pydata/pandas-datareader#265]
Hello,

it seems to be impossible to load the values of the MDAX, which is a German index. The Error message is:

    pandas_datareader._utils.RemoteDataError: Unable to read URL: http://www.google.com/finance/historical

The values are definitely available in Google as you could see here:
https://www.google.com/finance/historical?q=INDEXDB%3AMDAX&ei=2fJLWNCdJdessQGxnZqIAw

My code is as following:

```python
start = datetime.datetime(2015, 1, 1)
today = datetime.date.today()# - timedelta(1)
print('Start date is {0} and end date is {1}\n'.format(start,today))

df_downloadMDAX = web.DataReader("INDEXDB:MDAX", 'google', start, today).
```

Are there any reasons why that does not work? All other indexes work.
BTW: Thanks for your greatful work here!

**Comment by femtotrader** [comment]
Could you try with [latest development version](https://github.com/pydata/pandas-datareader#install-latest-development-version)?
and write here `RemoteDataError` exception

**Comment by GitHubUser2014** [comment]
Here is a screenshot of the entire error message:

![unknown](https://cloud.githubusercontent.com/assets/6164905/21073787/96535266-bee8-11e6-865f-03d1f99008cb.PNG)

Unfortunately, I cannot install the developer version cos I have some issues w/ GitHub. At the moment I use the stable version 0.2.1

**Comment by femtotrader** [comment]
In such a case, you can download latest version using https://github.com/pydata/pandas-datareader/archive/master.zip

**Comment by jeffcarey** [comment]
This is an issue with Google Finance--though you can view the information on the site, they don't provide an export for indexes. The same holds for the major US indexes like the S&P 500 and Dow Jones Industrial Average. If you go to the "Historical Prices" page for a stock/index and you don't see the "Export" link on the right, then it likely won't work in the pandas datareader.

**Comment by bashtage** [comment]
As of v0.7.0 Google finance and Morningstar have been immediately deprecated due to large changes in their API and no stable replacement.
