### ISSUE TITLE
API: Yahoo option type labels

### ISSUE THREAD

**Issue by davidastephens** [pydata/pandas-datareader#273]
#244 changed how option types are described from put and call to puts and calls.

This is a breaking API change and is different than how the google option reader describes them.
Docs broken [here](https://pandas-datareader.readthedocs.io/en/latest/remote_data.html#yahoo-finance-options)

Any objection to changing this back to put and call? Semantically, as the index is referring to an individual option, I think the singular is more appropriate.

Example:
```
In [1]: 
from pandas_datareader import Options
tsla = Options('tsla', 'yahoo')
data = tsla.get_all_data()
data.index.levels[2]

Out[1]: 
Index(['calls', 'puts'], dtype='object', name='Type')

In [2]:
tsla = Options('tsla', 'google')
data = tsla.get_options_data(expiry=tsla.expiry_dates[0])
data.index.levels[2]
Out[2]:
Index(['call', 'put'], dtype='object', name='Type')

```

**Comment by femtotrader** [comment]
Pinging @beluga9

**Comment by beluga9** [comment]
Sorry about that.  No objections @davidastephens.

**Comment by davidastephens** [comment]
No prob. Thanks, will modify and add tests to ensure consistency.
