### ISSUE TITLE
Description and topics

### ISSUE THREAD

**Issue by femtotrader** [pydata/pandas-datareader#278]
Hello,

This Github repository have no description.

It haven't any topics defined also.
see https://help.github.com/articles/about-topics/
https://github.com/blog/2309-introducing-topics

Maybe we should add a description to this repository and also some topics

Description:
Remote data access for Python pandas

Topics:
python data download remote network pandas

Kind regards

PS: I'm not allowed to do it so maybe someone allowed can do it.
PS2: Same "issue" in pandas repository https://github.com/pandas-dev/pandas/issues/15292

**Comment by gliptak** [comment]
@femtotrader Topics were added to the repo.
