### ISSUE TITLE
Options quotes are missing timezone

### ISSUE THREAD

**Issue by aisthesis** [pydata/pandas-datareader#28]
I ran into this problem on the 'Quote_Time' field when pulling options quotes using `pandas.io.data.Options.get_all_data()`. While 'Quote_Time' is objectively 'US/Eastern' timezone, it actually shows up in the dataframe as naive timezone, which in my use case then got interpreted as UTC. I would suggest setting the timezone correctly when the data is pulled from Yahoo.

I'm pretty sure that the Expiry field in the index also uses a naive timezone (`= None`).

[Here](https://github.com/aisthesis/pynance/issues/3) is a related issue for further clarification.

**Comment by dstephens99** [comment]
I ran into this issue because datetime.datetime.strptime can't recognize EDT or EST as a timezone.  

Any idea if Yahoo always shows the time as US/Eastern regardless of where the user is?   If that is the case, then we can just set the timezone.

As for the expiry date - is it helpful to have a timezone without a time? We could set it to 4pm US/Eastern, although I'm not sure what time the actually expire.

**Comment by aisthesis** [comment]
Yahoo! shows the time for me as Eastern even though I'm in PST and pulls the time in EST on servers that are set to use UTC.

**Comment by aisthesis** [comment]
Here is some output from my laptop, which is using PDT:

    >>> import pandas as pd
    >>> from pandas.io.data import Options
    >>> aapl = Options('aapl', 'yahoo')
    >>> aopt = aapl.get_all_data()
    >>> aopt.iloc[0,:]
    Last                               93.1
    Bid                                88.5
    Ask                                91.7
    Chg                                   0
    PctChg                            0.00%
    Vol                                  47
    Open_Int                            476
    IV                               63.28%
    Root                               AAPL
    IsNonstandard                     False
    Underlying                         AAPL
    Underlying_Price                 124.24
    Quote_Time          2015-03-26 16:00:00
    Name: (34.29, 2016-01-15 00:00:00, call, AAPL160115C00034290), dtype: object
    >>> aopt.iloc[0,:].loc['Quote_Time']
    Timestamp('2015-03-26 16:00:00')
    >>> aopt.index[0]
    (34.289999999999999, Timestamp('2016-01-15 00:00:00'), 'call', u'AAPL160115C00034290')
    >>> aopt.index[0][1]
    Timestamp('2016-01-15 00:00:00')
    >>> aopt.index[0][1].to_datetime()
    datetime.datetime(2016, 1, 15, 0, 0)
    >>> aopt.index[0][1].to_datetime().tzinfo
    >>> 
Both expiry and quote time are timezone naive.

**Comment by aisthesis** [comment]
I'm not finding much of use regarding the actual time of expiration. As public customer, you have to notify your broker of intent to exercise by 5:00 PM New York time on the Friday *before* expiration. At the latest by 0:00 AM Saturday morning New York time, the option is expired, as far as I can tell. But the brokerages on Saturday are generally in the process of settling the positions. I think it would be a  reasonable solution to leave everything as is with the expiration time (00:00:00) but just set the zone there to 'US/Eastern' as well.

**Comment by dstephens99** [comment]
See #29.  I converted everything to pandas timestamps and localized to US/Eastern.

**Comment by aisthesis** [comment]
Great, thanks! So `pandas-datareader 0.1.1` will include these changes? Any approximate timeline on when that version will be available?

**Comment by dstephens99** [comment]
Still some debate on the pull request (#29) on whether to include timezones.

**Comment by aisthesis** [comment]
Ping! Has anything been decided on this issue?

**Comment by davidastephens** [comment]
Continued discussion on #29

**Comment by bashtage** [comment]
This feature is deprecated.
