### ISSUE TITLE
get_available_datasets in Fama french

### ISSUE THREAD

**Issue by qiaoqiaozhu** [pydata/pandas-datareader#288]
I follow the documentation and do
```
from pandas_datareader.famafrench import get_available_datasets
get_available_datasets()
```
I get the error message:  Please install lxml if you want to use the get_datasets_famafrench function. 
This is despite the fact that I have lxml installed through conda. 

Any ideas?

**Comment by gfyoung** [comment]
Try uninstalling `lxml` and re-installing.  You need to insure that you can run the following line:
~~~python
from lxml.html import document_fromstring
~~~

**Comment by gliptak** [comment]
@qiaoqiaozhu Did this above work for you?

**Comment by bashtage** [comment]
This is not a pdr bug.
