### ISSUE TITLE
Cant install pandas-datareader

### ISSUE THREAD

**Issue by arunkumarwa** [pydata/pandas-datareader#289]
Hello 
running the install below.  no go.  Can someone help ?

thx

An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues

Current conda install:

               platform : win-64
          conda version : 4.3.14
       conda is private : False
      conda-env version : 4.3.14
    conda-build version : not installed
         python version : 3.6.0.final.0
       requests version : 2.12.4
       root environment : C:\ProgramData\Anaconda3  (read only)
    default environment : C:\ProgramData\Anaconda3
       envs directories : C:\ProgramData\Anaconda3\envs
                          C:\Users\akumar3\AppData\Local\conda\conda\envs
                          C:\Users\akumar3\.conda\envs
          package cache : C:\ProgramData\Anaconda3\pkgs
                          C:\Users\akumar3\AppData\Local\conda\conda\pkgs
           channel URLs : https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : None
           offline mode : False
             user-agent : conda/4.3.14 requests/2.12.4 CPython/3.6.0 Windows/10 Windows/10.0.14393

`$ C:\ProgramData\Anaconda3\Scripts\conda-script.py create -n my_root --clone=C:\ProgramData\Anaconda`

    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\exceptions.py", line 573, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main.py", line 134, in _main
        exit_code = args.func(args, p)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main_create.py", line 68, in execute
        install(args, parser, 'create')
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\install.py", line 212, in install
        clone(args.clone, prefix, json=context.json, quiet=context.quiet, index_args=index_args)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\install.py", line 57, in clone
        raise DirectoryNotFoundError(src_arg, 'no such directory: %s' % src_arg, json)
    TypeError: __init__() takes 2 positional arguments but 4 were given

**Comment by aking1012** [comment]
best guess is always upgrade pip

**Comment by gfyoung** [comment]
Where are you exactly installing `pandas-datareader` here?

**Comment by bashtage** [comment]
Run ``conda update conda`` and try again.

**Comment by arunkumarwa** [comment]
thanks for checking.  It was actually installed as part of the Anaconda package install which you pull down for CNTK.  I had a path issue in my spyder environment.  pandas works fine now.


Sent from Outlook<http://aka.ms/weboutlook>


________________________________

**Comment by gfyoung** [comment]
Not sure who can close this, but this should be closed now (@jreback ?)

**Comment by arunkumarwa** [comment]
i just closed it....thx


Sent from Outlook<http://aka.ms/weboutlook>


________________________________
