### ISSUE TITLE
Proxy Options

### ISSUE THREAD

**Issue by zglin** [pydata/pandas-datareader#292]
Don't see any the options to use a proxy for any of the data modules in the documentation, is this implemented?

**Comment by femtotrader** [comment]
You can pass your own Python Requests Session for (most) DataReader

see http://docs.python-requests.org/en/master/user/advanced/#proxies
and http://stackoverflow.com/questions/30837839/how-can-i-set-a-single-proxy-for-a-requests-session-object


```python
import requests
proxies = {
    'http': 'http://cache.domain.com:3128'
}
session = requests.Session()
session.proxies.update(proxies)

import pandas_datareader as pdr
f = pdr.DataReader("F", "yahoo", "2016-01-01", "2016-12-31", session=session)
```

PR to improve doc is welcome.

**Comment by zglin** [comment]
Thanks a bunch. Will do!
