### ISSUE TITLE
CI is broken because of WorldBank and GoogleOptions DataReaders tests

### ISSUE THREAD

**Issue by femtotrader** [pydata/pandas-datareader#295]
CI is broken

related to https://github.com/pydata/pandas-datareader/pull/293 (but not because of...)

see https://travis-ci.org/pydata/pandas-datareader/jobs/218240770

WorldBank https://travis-ci.org/pydata/pandas-datareader/jobs/218240770#L778
Pinging @sinhrks @stared @hayd 

GoogleOptions https://travis-ci.org/pydata/pandas-datareader/jobs/218240770#L766
Pinging @sinhrks @gliptak

Pinging @jreback @davidastephens

**Comment by femtotrader** [comment]
Pinging @davidastephens

**Comment by gfyoung** [comment]
@jreback : Should be closed after merging #322.
