### ISSUE TITLE
OANDA is broken

### ISSUE THREAD

**Issue by STguerin** [pydata/pandas-datareader#296]
For some reason OANDA is now returning an Error

```
from pandas_datareader.oanda import get_oanda_currency_historical_rates

fx_rates = get_oanda_currency_historical_rates(start='1990-01-01', end=None,
 quote_currency='USD', base_currency='EUR')
```

```
Traceback (most recent call last):
  File "C:\Anaconda2\lib\site-packages\IPython\core\interactiveshell.py", line 2881, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-6-14c50a5808d3>", line 3, in <module>
    fx_rates = get_oanda_currency_historical_rates(start='1990-01-01', end=None, quote_currency='USD', base_currency='KRW')
  File "C:\Anaconda2\lib\site-packages\pandas_datareader\oanda.py", line 42, in get_oanda_currency_historical_rates
    df = pd.read_csv(StringIO(response.text), parse_dates=[0], skiprows=skiprows, skipfooter=skipfooter, usecols=usecols, engine='python', thousands=',')
  File "C:\Anaconda2\lib\site-packages\pandas\io\parsers.py", line 562, in parser_f
    return _read(filepath_or_buffer, kwds)
  File "C:\Anaconda2\lib\site-packages\pandas\io\parsers.py", line 325, in _read
    return parser.read()
  File "C:\Anaconda2\lib\site-packages\pandas\io\parsers.py", line 815, in read
    ret = self._engine.read(nrows)
  File "C:\Anaconda2\lib\site-packages\pandas\io\parsers.py", line 1737, in read
    content = self._get_lines(rows)
  File "C:\Anaconda2\lib\site-packages\pandas\io\parsers.py", line 2224, in _get_lines
    new_rows.append(next(source))
Error: ',' expected after '"'

```

any idea?

**Comment by dclambert** [comment]
Just came here to post this.  It seems that OANDA may have moved to subscription only for CSV downloads: [http://www.oanda.com/currency/historical-rates/download](url)

**Comment by moortimis** [comment]
I came to post, saw it was done, and now I'm gone.

**Comment by femtotrader** [comment]
OANDA now displays on their website

Register to become a Premium Member
Features unlocked by becoming a premium member:
Download historical data to a CSV file
Access up to 25 years of historical data
Access over 15 types of central bank rates

Can someone here can explain what are condition to be a "Premium Member"?

Is it only necessary to register? or is it only available with a paid subscription?

**Comment by natashawatkins** [comment]
Are there any alternatives? Am I able to get quotes from Google/Yahoo finance?

**Comment by femtotrader** [comment]
I don't see OHLC data in Fred

**Comment by natashawatkins** [comment]
@femtotrader no unfortunately it's just close I believe..

**Comment by attibalazs** [comment]
looks like the api is downloading the HTML source instead of the rows of the historical exchange rates CSV file, what a shame :(

> 
> 00 = {list} <class 'list'>: ['<link rel="stylesheet" type="text/css" href="/static/sfb/hcc/css/lightbox-98fbe7ad20.css">']
> 01 = {list} <class 'list'>: ['<link rel="stylesheet" type="text/css" href="/static/sfb/hcc/css/hcc-544adfc59a.css">']
> 02 = {list} <class 'list'>: ['<link rel="stylesheet" type="text/css" media="print" href="/static/sfb/hcc/css/print-bdd45c5ac9.css">']
> 03 = {list} <class 'list'>: ['<script type="text/javascript" src="https://code.jquery.com/jquery-1.11.3.min.js"></script>']
> 04 = {list} <class 'list'>: ['<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery-cookie/1.4.1/jquery.cookie.js"></script>']
> 05 = {list} <class 'list'>: ['<script type="text/javascript" src="https://www.oanda.com/jslib/joanda.js"></script>']
> 06 = {list} <class 'list'>: ['<script type="text/javascript">']
> 07 = {list} <class 'list'>: ['        window.OANDA = {};']
> 08 = {list} <class 'list'>: ['        window.OANDA.lang = {};']
> 09 = {list} <class 'list'>: ['        jQuery(function () {']
> 10 = {list} <class 'list'>: ['            jQuery.ajaxSetup({cache: false});']
> 11 = {list} <class 'list'>: ['        });']
> 12 = {list} <class 'list'>: ['    ']

**Comment by gliptak** [comment]
Premium membership is $75/month. Should Oanda be removed from the codebase (until somebody updates to use premium "keys")? Thanks

![oanda](https://user-images.githubusercontent.com/50109/27938171-42298840-628a-11e7-886d-004e7cde7c3a.png)

**Comment by jreback** [comment]
yes, let's disable & put a doc note.

**Comment by gliptak** [comment]
@jreback The test was already disabled. Would you like to remove the code (and tests, docs) altogether, and add a release note? Thanks

**Comment by jreback** [comment]
yes i think let's remove it all

**Comment by davidandreoletti** [comment]
@jreback I began adding OANDA API v20 support into this project but never got the change to merge the PR [1]. 

Last time I checked (6months ago), OANDA API v20 access was free of charge. Perhaps you can consider deprecating the legacy OANDA API and use v20 OANDA API instead.

Note: I cannot maintain the PR anymore so you are free to do anything you like with it :)

[1] https://github.com/pydata/pandas-datareader/pull/257

CC: @femtotrader

**Comment by gliptak** [comment]
As per http://developer.oanda.com/rest-live-v20/introduction/ v2 API is available for demo (data?) and live accounts.
