### ISSUE TITLE
Fama-French does not retrieve full history

### ISSUE THREAD

**Issue by jonrtaylor** [pydata/pandas-datareader#298]
Portfolios go back many decades, yet the function only retrieves data from 2010 to current.

`CF_P = web.DataReader("Portfolios_Formed_on_CF-P", "famafrench")
CF_P['DESCR']`
out: u'Portfolios Formed on CF-P\n-------------------------\n\nThis file was created by CMPT_EP_CFP_OP_INV_NI_AC_RETS using the 201702 CRSP database. It contains value- and equal-weighted returns for portfolios formed on CF/P. The portfolios are constructed at the end of June. CF/P is cashflow (earnings before extraordinary plus deferred tax income statement plus common equitys share of depreciation) at the last fiscal year end of the prior calendar year divided by ME at the end of December of the prior year. Annual returns are from January to December. Missing data are indicated by -99.99 or -999. The break points include utilities and include financials. The portfolios include utilities and include financials. Copyright 2017 Kenneth R. French\n\n  0 : Value Weight Returns -- Monthly (86 rows x 19 cols)\n  1 : Equal Weight Returns -- Monthly (86 rows x 19 cols)\n  2 : Value Weight Returns -- Annual from January to December (7 rows x 19 cols)\n  3 : Equal Weight Returns -- Annual from January to December (7 rows x 19 cols)\n  4 : Number of Firms in Portfolios (86 rows x 19 cols)\n  5 : Average Firm Size (86 rows x 19 cols)\n  6 : Sum of CF     / Sum of ME (7 rows x 19 cols)\n  7 : Value Weight Average of CF     / ME (7 rows x 19 cols)'

Index zero (value weight returns - monthly) has 86 rows, but the actual data file has 788 (as of 4/27/17)

**Comment by jonrtaylor** [comment]
apologies - I jumped the shark. I wasn't passing start or end dates. I would only suggest that the official page snippet reflect those parameters as the example posted also kicks the same error.
`CF_P = web.DataReader("Portfolios_Formed_on_CF-P", "famafrench", start=start, end=end)`

**Comment by cfox189** [comment]
I agree.  The example should be adjusted to:

`ds = web.DataReader("5_Industry_Portfolios", "famafrench",start='1900-01')`
