### ISSUE TITLE
Decide on the package name

### ISSUE THREAD

**Issue by jorisvandenbossche** [pydata/pandas-datareader#3]
Currently, @hayd changed the package name to `pandas_datareader`. Is everybody satisfied with that? (to be clear: it is about the name that is `import`ed)

Personally, I find it a bit long, and I think I also don't really like the underscore in the name. But of course, it is just personal taste! (I justed wanted to bring up the discussion to have this now, and not later, and deliberately decide on this to keep it as it is or to change it). 
What about just `datareader`, or `pddatareader` (but that is a bit difficult with the two 'd's)

**Comment by bashtage** [comment]
I also think it is long, although it is closely tied to pandas.  I also think datareader is not very descriptive for what appears to be the process of pulling out.  IN particular, webreader or netreader would seem to fit since there are plenty of file-based readers remaining in core pandas.

**Comment by jnmclarty** [comment]
pandr

**Comment by hayd** [comment]
I had actually thought about pd_datareader (could be a good convention for any further sub-packages).

I don't feel strongly here. (though -1 on anything with pandr in it, sorry!)

**Comment by jnmclarty** [comment]
+1 to any convention that works with future subpackages. 

+1 for pd_*

so, -1 to pandr.

**Comment by jreback** [comment]
pandas-datareader ? 
I like the dash separators

**Comment by femtotrader** [comment]
I like `pandas-datareader `or `pandas_datareader`.
Having `pandas` before subpackage name is clear and when you sort Pypi package by name it will be easier to find every pandas subpackages.

**Comment by hayd** [comment]
@jreback I got confused at what dash separator meant with regard to lib name, it wasn't intentional/meaningful to drop it! ...

Hmmmm, it looks like the python convention is *not* to use dash separators as lib names: http://stackoverflow.com/a/761531/1240268 and instead (sparingly) use an underscore. ?

@femtotrader pypi searches the short and long descriptions too, so it's not the end of the world not to use pandas in the title... That said, I'm with you `pandas_` seems clearer.

**Comment by femtotrader** [comment]
I won't like to have to 

    __import__('pandas-datareader')

but

    import pandas_datareader

sounds much more familiar to me

**Comment by twiecki** [comment]
+1 on `pandas-datareader` and `import pandas_datareader`
