### ISSUE TITLE
Can't install pandas-datareader using pip or conda

### ISSUE THREAD

**Issue by femtotrader** [pydata/pandas-datareader#30]
Hello,

I'm trying to install pandas-datareader using pip or conda.

    $ conda install pandas-datareader
    Fetching package metadata: ....
    Error: No packages found in current osx-64 channels matching: pandas-datareader

    You can search for this package on Binstar with

        binstar search -t conda pandas-datareader
    $ conda --version
    conda 3.10.0
    $ pip install pandas-datareader
    Collecting pandas-datareader
      Could not find any downloads that satisfy the requirement pandas-datareader
      No distributions at all found for pandas-datareader

I'm using Mac OS X.

Any idea ?

Kind regards

**Comment by hayd** [comment]
Not just you :)

@dstephens99 looks like there are no files at https://pypi.python.org/pypi/pandas-datareader ! Perhaps tag a release and push the source & wheel.

**Comment by femtotrader** [comment]
I noticed "8 downloads in the last week" so I thought there was a file
but there isn't any more.

**Comment by dstephens99** [comment]
Re-uploaded the source/wheel for 0.1.0.  Seems to work for me know, let me know!

**Comment by jorisvandenbossche** [comment]
It is working for me!
