### ISSUE TITLE
RLS: 0.4

### ISSUE THREAD

**Issue by jreback** [pydata/pandas-datareader#328]

**Comment by jreback** [comment]
cc @davidastephens 

sorry about all the fixing. accid broke on pandas 0.20.1. So we fixed up and tests as well.

I think should release 0.4 with master as is.

**Comment by jreback** [comment]
@davidastephens can u do a release?

**Comment by davidastephens** [comment]
Yes - will do one tonight.

**Comment by jreback** [comment]
thanks @davidastephens 

I updated docs & pushed a release-procedure.md doc.  (read the docs does not appear to be building though it built last week).

lmk

**Comment by jreback** [comment]
thanks @davidastephens

**Comment by jreback** [comment]
@davidastephens can you trigger readthedocs to update. and trigger conda-forge?

**Comment by davidastephens** [comment]
I triggered the readthedocs update and submitted a PR to conda-forge.  I don't have write access to merge the conda-forge PR though.  Do you?
