### ISSUE TITLE
TST: Test class TestGoogle never runs due to bug in pandas.util.get_locales

### ISSUE THREAD

**Issue by davidastephens** [pydata/pandas-datareader#33]
pydata/pandas#9744

**Comment by hayd** [comment]
if we get coverage to 100% it should help prevent this in future, you can see what's being skipped: https://coveralls.io/builds/2213917

**Comment by dstephens99** [comment]
That's how I noticed it - I was looking at the coverage to try to improve it.   When I get this fixed, it should improve a lot.

**Comment by davidastephens** [comment]
Fixed with #35
