### ISSUE TITLE
'YahooDailyReader'

### ISSUE THREAD

**Issue by chemalle** [pydata/pandas-datareader#333]
Hi people,

Anyone know if Yahoo is not providing data anymore? Since yesterday I can not retrieve any data from pandas web data reader.

Thank you!

**Comment by rgkimball** [comment]
Their API changed a bit, hang tight for a fix. See #315 for discussion/details.

**Comment by thsavage** [comment]
Has the Yahoo API changed "a bit" or has it been discontinued?

**Comment by rgkimball** [comment]
It is still accessible, but they've substantially modified the endpoints and implemented a mandatory cookie. I'm still unclear on how to provide access for certain data (namely options and index constituents), but historical prices, dividends and splits are available.

**Comment by jreback** [comment]
dupe of #315
