### ISSUE TITLE
can't import PandasError (depreciated?)

### ISSUE THREAD

**Issue by bartelt** [pydata/pandas-datareader#334]
----> 1 import pandas_datareader.data as web

/Users/jlb/anaconda/envs/myfin/lib/python3.6/site-packages/pandas_datareader/base.py in <module>()
      9 from pandas import to_datetime
     10 import pandas.compat as compat
---> 11 from pandas.core.common import PandasError, is_number
     12 from pandas import Panel, DataFrame
     13 from pandas import read_csv

ImportError: cannot import name 'PandasError'

**Comment by jreback** [comment]
0.4.0 was released which fixes
