### ISSUE TITLE
Running on a docker container, replacing with NaN

### ISSUE THREAD

**Issue by i-frost** [pydata/pandas-datareader#337]
I have a container which has the same versions of pandas and datareader as my desktop.

But if I run a lookup on the container it complains with 
>>> web.DataReader(['AAPL'],'google', start, end)
/opt/conda/lib/python3.5/site-packages/pandas_datareader/base.py:192: SymbolWarning: Failed to read symbol: 'AAPL', replacing with NaN.
warnings.warn(msg.format(sym), SymbolWarning)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/lib/python3.5/site-packages/pandas_datareader/data.py", line 105, in DataReader
    session=session).read()
  File "/opt/conda/lib/python3.5/site-packages/pandas_datareader/base.py", line 178, in read
    df = self._dl_mult_symbols(self.symbols)
  File "/opt/conda/lib/python3.5/site-packages/pandas_datareader/base.py", line 197, in _dl_mult_symbols
    raise RemoteDataError(msg.format(self.__class__.__name__))
pandas_datareader._utils.RemoteDataError: No data fetched using 'GoogleDailyReader'

Any pointers to making this work?

Many Thanks

**Comment by aking1012** [comment]
Probably just need to swap the UA string.  They probably just drop requests from docker containers if they can figure out it's a container not a bonafide computer.

**Comment by i-frost** [comment]
Yep that fixed it, but oddly it is working without providing the UA string?
