### ISSUE TITLE
Google finance issues with datareader

### ISSUE THREAD

**Issue by jainraje** [pydata/pandas-datareader#344]
in the past I was able to perform on a ticker by ticker basis *bulk* OHLCV downloads (ex: 1yr history for 4000 tickers). Recently, I'm getting errors at about the 1000th ticker. The errors continue until the list is completed. 

Here is example of one of the errors:
Unable to read URL: http://www.google.com/finance/historical?enddate=May+26%2C+2017&q=NASDAQ%3AEBAY&output=csv&startdate=May+22%2C+2016 failed to pull pricing data

Any others able to download historical data from google for more than 4000?

**Comment by martinffx** [comment]
@jainraje do you have a stacktrace (error message) you're getting?

My assumption would be Google are now throttling the number of times there API can be called.

**Comment by jainraje** [comment]
I just ran a few tests:
- d/l single ticker: 'AMEX:SKY' => passed
- ran loop to d/l 3800 tickers => starting failing around 2000+ tickers
- after failure tried d/l single ticker 'AMEX:SKY' 

This failed with below stack trace:
---------------------------------------------------------------------------
RemoteDataError                           Traceback (most recent call last)
<ipython-input-48-c264075365cb> in <module>()
     20     df = pdr.get_data_yahoo(ticker, start=start_date, end=end_date)
     21 else:
---> 22     df = pdr.DataReader(ticker, source, start=start_date, end=end_date)
     23 
     24 print_df_info(df)

/Users/rajeev/anaconda/lib/python3.5/site-packages/pandas_datareader/data.py in DataReader(name, data_source, start, end, retry_count, pause, session, access_key)
    131                                  chunksize=25,
    132                                  retry_count=retry_count, pause=pause,
--> 133                                  session=session).read()
    134 
    135     elif data_source == "enigma":

/Users/rajeev/anaconda/lib/python3.5/site-packages/pandas_datareader/base.py in read(self)
    155         if isinstance(self.symbols, (compat.string_types, int)):
    156             df = self._read_one_data(self.url,
--> 157                                      params=self._get_params(self.symbols))
    158         # Or multiple symbols, (e.g., ['GOOG', 'AAPL', 'MSFT'])
    159         elif isinstance(self.symbols, DataFrame):

/Users/rajeev/anaconda/lib/python3.5/site-packages/pandas_datareader/base.py in _read_one_data(self, url, params)
     72         """ read one data from specified URL """
     73         if self._format == 'string':
---> 74             out = self._read_url_as_StringIO(url, params=params)
     75         elif self._format == 'json':
     76             out = self._get_response(url, params=params).json()

/Users/rajeev/anaconda/lib/python3.5/site-packages/pandas_datareader/base.py in _read_url_as_StringIO(self, url, params)
     83         Open url (and retry)
     84         """
---> 85         response = self._get_response(url, params=params)
     86         text = self._sanitize_response(response)
     87         out = StringIO()

/Users/rajeev/anaconda/lib/python3.5/site-packages/pandas_datareader/base.py in _get_response(self, url, params)
    118         if params is not None and len(params) > 0:
    119             url = url + "?" + urlencode(params)
--> 120         raise RemoteDataError('Unable to read URL: {0}'.format(url))
    121 
    122     def _read_lines(self, out):

RemoteDataError: Unable to read URL: http://www.google.com/finance/historical?startdate=Jan+01%2C+1980&enddate=May+30%2C+2017&output=csv&q=AMEX%3ASKY

**Comment by DMTSource** [comment]
If you visit the URl when the error occurs you will notice a "Am I a Robot" captcha page. They seem to be timing out briefly by ip if spam is detected. With Yahoo source broken there is now effectively no finance data.

**Comment by Jerryzhuht** [comment]
Thanks, I updated to the latest but still got the error.. It is imported from another package so I'm not sure how to change the backend.

**Comment by DMTSource** [comment]
@Jerryzhuht  to clarify after upgrading pandas-datareader I then, in the code, reverted back to yahoo with changes similar to:
df = web.DataReader(symbol.strip(), 'google', self.start, self.end).dropna(axis=0)
to
df = web.DataReader(symbol.strip(), 'yahoo', self.start, self.end).dropna(axis=0)

**Comment by seerwright** [comment]
Howdy. I'm new to zipline, but I believe I am seeing this same error. I'll follow the suggestions here of 1) updating pandas-datareader and 2) switching back to Yahoo. However, I have a basic question: why would zipline attempt to use an URL at all if I am using the --bundle switch when running my algorithm? In my mind, the bundle replaces the URL as the source of backtesting data. Thanks for any thoughts on this.

**Comment by felipetshr** [comment]
@DMTSource in which .py file in the pandas-datareader directory exactly do I need to make the indicated substitution? Tks a lot.

**Comment by DMTSource** [comment]
@felipetshr Sorry for the confusion, I think my 'secret' to getting it to work was using pandas-datareader version 0.5.0. I had to figure this out yesterday by chance when trying to get either yahoo or google finance data to work via web on diff operating systems. Both worked as of this posting with this version. 
I used something like:
pip install --upgrade pandas-datareader==0.5.0

**Comment by bashtage** [comment]
As of v0.7.0 Google finance and Morningstar have been immediately deprecated due to large changes in their API and no stable replacement.
