### ISSUE TITLE
`_utils.RemoteDataError` should subclass `ConnectionError`

### ISSUE THREAD

**Issue by aisthesis** [pydata/pandas-datareader#359]
As of Python 3.3, `IOError` is being merged into `OSError`. It looks to me like the appropriate position in the hierarchy for `_utils.RemoteDataError` would be as a subclass of `ConnectionError`, possibly more specifically `ConnectionRefusedError`. Cf. https://www.python.org/dev/peps/pep-3151/ and https://docs.python.org/3/library/exceptions.html#os-exceptions

**Comment by gfyoung** [comment]
Hmmm...I have a feeling you might encounter resistance on this.  `RemoteDataError` is used to specify errors in gathering data from a remote endpoint, whether it be that the data could not be fetched or that the returned data was something that couldn't be parsed.

The latter usage is pertinent to your proposal, as subclassing `RemoteDataError` under `ConnectionError` would not include this usage, which would be problematic (cf <a href="https://github.com/pydata/pandas-datareader/blob/6f4a22fe7eb5f1463592d244014e7b39813bd183/pandas_datareader/yahoo/daily.py#L149">here</a> for the latter usage).

**Comment by bashtage** [comment]
I think this isn't needed.
