### ISSUE TITLE
Yahoo Datareader RemoteDataError when end date added in Python 3

### ISSUE THREAD

**Issue by ccsv** [pydata/pandas-datareader#36]
See stackoverflow description: 

http://stackoverflow.com/questions/29296045/pandas-yahoo-datareader-remotedataerror-when-end-date-added?noredirect=1#comment46788752_29296045

**Comment by dstephens99** [comment]
This is very strange.  It seems to be a problem with Yahoo finance that only affects GOOG.

This is the link to download GOOG data per the stackoverflow question (doesn't work):
https://ichart.yahoo.com/table.csv?s=GOOG&a=0&b=1&c=2010&d=1&e=1&f=2013&g=d&ignore=.csv

Same link, ticker changed to AAPL (works)
https://ichart.yahoo.com/table.csv?s=AAPL&a=0&b=1&c=2010&d=1&e=1&f=2013&g=d&ignore=.csv

I'm not sure what we can do about this.
