### ISSUE TITLE
Make "skip_on_exception" a signature-preserving decorator. 

### ISSUE THREAD

**Issue by OlegShteynbuk** [pydata/pandas-datareader#363]
Currently `skip_on_exception`  is not a signature-preserving decorator, at least in Python 2.7. When writing tests one needs to use a workaround to  parametrize `skip_on_exception` decorator see https://github.com/pydata/pandas-datareader/pull/357 for discussion.

**Comment by OlegShteynbuk** [comment]
PR https://github.com/pydata/pandas-datareader/pull/364

**Comment by OlegShteynbuk** [comment]
run  successfully local tests with module wrapt that comes with anaconda and for some reasons, it is not available for Travis CI
https://github.com/GrahamDumpleton/wrapt

**Comment by bashtage** [comment]
It needs to be added here:

https://github.com/pydata/pandas-datareader/blob/master/.travis.yml#L54

to be available on TravisCI.

**Comment by bashtage** [comment]
Or here

https://github.com/pydata/pandas-datareader/blob/master/.travis.yml#L63

to install via pip

**Comment by OlegShteynbuk** [comment]
@bashtage thanks it works, comes with anaconda

**Comment by bashtage** [comment]
Need to add to tox

https://github.com/pydata/pandas-datareader/blob/master/tox.ini#L9

**Comment by femtotrader** [comment]
I wonder if it shouldn't be add to [setup.py](https://github.com/pydata/pandas-datareader/blob/master/setup.py#L27)

**Comment by bashtage** [comment]
It is test only.

**Comment by femtotrader** [comment]
Oh yes! sorry you are right! sorry for noise.

**Comment by gfyoung** [comment]
@OlegShteynbuk : Thanks for sharing this library!  Good to know that it exists.  While I'm still a little uneasy about installing an entire library just for this, I don't see a better way to fix this at the moment. :smile:

**Comment by bashtage** [comment]
Could mark a TODO on this to drop this library after 2.7 is dropped (even though this will be a while).

**Comment by OlegShteynbuk** [comment]
> Thanks for sharing this library! Good to know that it exists. While I'm still a little uneasy about installing an entire library just for this, I don't see a better way to fix this at the moment

@gfyoung there are a couple of good articles on the issue
https://hynek.me/articles/decorators/
more than three years ago by the author of wrapt
http://blog.dscpl.com.au/2014/01/how-you-implemented-your-python.html
