### ISSUE TITLE
Exceptions in documentation examples

### ISSUE THREAD

**Issue by raffam** [pydata/pandas-datareader#369]
Good morning,
Why does the [documentation](https://pandas-datareader.readthedocs.io/en/latest/remote_data.html#remote-data-yahoo) reports that its own examples give exceptions as results?
For example, the documentation reports that the following command
`f = web.DataReader("F", 'yahoo', start, end)`
Gives this exception as a result:
> ConnectionErrorTraceback (most recent call last)
> <ipython-input-5-679b50ab962b> in <module>()
> ----> 1 f = web.DataReader("F", 'yahoo', start, end)
> 
> /home/docs/checkouts/readthedocs.org/user_builds/pandas-datareader/envs/latest/local/lib/python2.7/site-packages/pandas_datareader-0.4.0-py2.7.egg/pandas_datareader/data.pyc in DataReader(name, data_source, start, end, retry_count, pause, session, access_key)
>     115                                 adjust_price=False, chunksize=25,
>     116                                 retry_count=retry_count, pause=pause,
> --> 117                                 session=session).read()
>     118 
>     119     elif data_source == "yahoo-actions":

This is an error in the doc, right?

**Comment by jreback** [comment]
these are generated for 0.4.0 where yahoo is broken

0.5.0 (soon) will fix this
