### ISSUE TITLE
Google Finance Options chains

### ISSUE THREAD

**Issue by femtotrader** [pydata/pandas-datareader#37]
Adding support for Google Finance Options chains will be a great idea.

Here is a Matlab script
http://www.mathworks.com/matlabcentral/fileexchange/50368-stock-option-chain-downloader--via-google-

Some Python code is also available here
https://github.com/femtotrader/pandas_datareaders_unofficial/blob/master/pandas_datareaders_unofficial/datareaders/google_finance_options.py

**Comment by gliptak** [comment]
Being worked as https://github.com/pydata/pandas-datareader/pull/183

**Comment by davidastephens** [comment]
Closed with #183
