### ISSUE TITLE
Add ENIGMA_API_KEY to Travis?

### ISSUE THREAD

**Issue by gliptak** [pydata/pandas-datareader#370]
@femtotrader Do you have access to add API keys to Travis? Thanks

**Comment by femtotrader** [comment]
Yes I have and it was set

![capture d ecran 2017-07-11 a 09 05 50](https://user-images.githubusercontent.com/5049737/28055195-2e301764-6618-11e7-98e2-127c8e2b5d33.png)

Some contributors suggested an other approach (using encrypted variables in `.travis.yml`)
https://docs.travis-ci.com/user/environment-variables/#Defining-encrypted-variables-in-.travis.yml

**Comment by gliptak** [comment]
Would this key also be used to generate the documentation? The documentation example fails as per  https://github.com/pydata/pandas-datareader/issues/299 Thanks

**Comment by femtotrader** [comment]
I don't think so. Doc is generate using ReadTheDocs and I have no access.

**Comment by gliptak** [comment]
@jreback Would you have ReadTheDocs admin access for Pydata? Thanks

**Comment by jreback** [comment]
@jorisvandenbossche has the key, he is back soon.

**Comment by gliptak** [comment]
Could https://readthedocs.org/ be updated with these keys? Thanks

**Comment by bashtage** [comment]
This has been done.
