### ISSUE TITLE
RLS: 0.5.0

### ISSUE THREAD

**Issue by jreback** [pydata/pandas-datareader#371]
@davidastephens ok I think this is ok to go. can you do the release? I can trigger conda-forge once the release commit is pushed. 

I don't have access to readthedocs acct, can you add me.

**Comment by jreback** [comment]
also the whatsnew docs needs a day on the day of release.

**Comment by mijcs18** [comment]
Is there a conservative estimate on when 0.5.0 will be released as well as if the Yahoo Finance fix will be included? Thank you.

**Comment by davidastephens** [comment]
@jreback Released.

@jorisvandenbossche is the only owner for read the docs, but I could trigger the update.

**Comment by jorisvandenbossche** [comment]
Back from holidays! I added both of you (@jreback and @davidastephens) as maintainers to readthedocs.

**Comment by jreback** [comment]
thanks for the release @davidastephens

**Comment by jreback** [comment]
@davidastephens needs a PR to: https://github.com/conda-forge/pandas-datareader-feedstock
to build the conda-forge packages
