### ISSUE TITLE
What are the limitation in in ticker names?

### ISSUE THREAD

**Issue by favetelinguis** [pydata/pandas-datareader#374]
When trying to following tickers from Yahoo only ^OMX is found although they are all available to view on Yahoo finance:

```["XDWD.ST",'^OMX','^HOXFLATGBG']```

Why are not all downloaded with pandas-datareader?

**Comment by gliptak** [comment]
There is a download button at https://finance.yahoo.com/quote/%5EOMX/history?p=%5EOMX

Possibly similar limitations for futures are noted at https://github.com/pydata/pandas-datareader/issues/290

**Comment by bashtage** [comment]
Yahoo has been deprecated.
