### ISSUE TITLE
Add Enigma Public Data Connector

### ISSUE THREAD

**Issue by hydrosquall** [pydata/pandas-datareader#376]
The Enigma reader currently points to `app.enigma.io`, which will soon be shut down due to the recent release of `public.enigma.com` on June 20, 2017.  Writeup is [here](https://www.enigma.com/blog/the-new-enigma-public).

In this new API, the concept of "datapaths" has been removed, and replaced with unique `uuid4` identifiers for every dataset.

I will base a new connector on the previous one, and recommend that the old connector be removed when `app.enigma.io` is officially shut down.

**Comment by gliptak** [comment]
https://github.com/pydata/pandas-datareader/issues/370

**Comment by gliptak** [comment]
@hydrosquall Consider closing this issue.

**Comment by hydrosquall** [comment]
Thanks @gliptak, you're right!
