### ISSUE TITLE
Yahoo download broken when using requests_cache

### ISSUE THREAD

**Issue by shipmints** [pydata/pandas-datareader#377]
Not a python requests or pandas_datareader internals hacker here so perhaps I did something wrong. When I call web.DataReader without passing the session, it works fine, albeit without a session cache.

Thanks in advance to all those who make Pandas and the toolkits around it possible.

```
$ pip show pandas-datareader|head -n2
Name: pandas-datareader
Version: 0.5.0
```

```
#!/usr/bin/env python
import pandas_datareader.data as web
import datetime
import requests_cache
expire_after = datetime.timedelta(days=3)
session = requests_cache.CachedSession(cache_name='requests_cache', backend='sqlite', expire_after=expire_after)
start = datetime.datetime(1902, 1, 1) # earlier than 1902 causes the pandas datareader daily.py implementation to overflow an int
end = datetime.datetime.today()
df = web.DataReader('F', 'yahoo', start, end, session=session)
```
Yields

```
  File ".../python2.7/site-packages/pandas_datareader/base.py", line 139, in _get_response
    raise RemoteDataError('Unable to read URL: {0}'.format(url))
pandas_datareader._utils.RemoteDataError: Unable to read URL: https://query1.finance.yahoo.com/v7/finance/download/F?crumb=Jl.kuiX1MoB&interval=1d&period2=1501905599&events=history&period1=-2145898800
```

**Comment by itzybitzy** [comment]
In what situation would you be attempting to download data from 1902?

**Comment by shipmints** [comment]
The idea is to get as much historical data as possible for analysis. More data is always better in finance. One can't know when every series starts so choosing a date far back enough as a generic starting point is one way to solve the problem. I'd pick 17000101 if I could. 1902 was a compromise to work around the bug.

**Comment by stoffprof** [comment]
Sure but Yahoo doesn't have data back that far, do they? There's clean data from CRSP that starts in 1926 and Global Financial Data sells data back to the 1600s, but those are both expensive databases. Yahoo had data on IBM starting in 1962 so I can imagine the have other equities starting earlier.

**Comment by shipmints** [comment]
Yahoo may indeed have data that far back for some symbols or series such as the DOW. They don't have an API, as far as I know, that says "give me everything," so we have to hack it via an early date. We also don't have access to their meta data series by series of start dates so picking something early and used universally across all series with opaque start dates makes sense. Perhaps you know something I don't.

**Comment by bashtage** [comment]
Yahoo has been deprecated.
