### ISSUE TITLE
empty data frames received for many valid tickers

### ISSUE THREAD

**Issue by jainraje** [pydata/pandas-datareader#379]
I just updated to 5.0.0 and started using datareader for bulk ticker history download. I'm observing many zero length data frames received for valid symbols. Prior I was using fix_yahoo_finance with no issues. If a retry mechanism is not in place for datareader, can one be added?

**Comment by manan904** [comment]
Can you give some examples where you received zero length data frames??

Also, I was advised to use google finance as an alternative to Yahoo Finance to get data...Try using that and see if you can get the data.

**Comment by bashtage** [comment]
Yahoo has been deprecated.
