### ISSUE TITLE
Eurostat -  mismatched tag; 

### ISSUE THREAD

**Issue by HristoBuyukliev** [pydata/pandas-datareader#383]
`eu_trade_since_2000 = web.DataReader("DS-043327", 'eurostat')`

gives the message 

`  File "<string>", line unknown
ParseError: mismatched tag: line 28, column 8`

That's not very informative. I have no idea what is going on at all. Part of the pip freeze output is:
>numpy==1.13.1
pandas==0.20.3
pandas-datareader==0.5.0

**Comment by manan904** [comment]
Can you please show the complete code?
Looks like some information is missing

**Comment by HristoBuyukliev** [comment]
`import pandas_datareader as web
eu_trade_since_2000 = web.DataReader("DS-043327", 'eurostat')`

That's the whole code.

**Comment by manan904** [comment]
I'm really sorry but I wasn't able to get the data on the ticker which you wrote...
Is this the link that you're trying to access???
`http://appsso.eurostat.ec.europa.eu/nui/show.do?dataset=DS-043327&lang=en`

**Comment by HristoBuyukliev** [comment]
Yeah, exactly. Only I need some specific filters - e.g. not transport mode "Unknown", but "Sea".

**Comment by manan904** [comment]
I'm afraid I don't know the solution for your problem.
I guess such a thing isn't possible with pandas yet.

**Comment by gliptak** [comment]
https://github.com/pydata/pandas-datareader/pull/670

The current ```master``` shows a query size error:
```
>>> import pandas_datareader as web
>>> we.__version__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'we' is not defined
>>> eu_trade_since_2000 = web.DataReader("DS-043327", 'eurostat')
Traceback (most recent call last):
  File "/mnt/pandas_datareader/io/sdmx.py", line 55, in read_sdmx
    structure = _get_child(root, _MESSAGE + "Structure")
  File "/mnt/pandas_datareader/io/sdmx.py", line 173, in _get_child
    raise ValueError("Element {0} contains " "no {1}".format(element.tag, key))
ValueError: Element {http://www.sdmx.org/resources/sdmxml/schemas/v2_1/message}GenericData contains no {http://www.sdmx.org/resources/sdmxml/schemas/v2_1/message}Structure

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 208, in wrapper
    return func(*args, **kwargs)
  File "/mnt/pandas_datareader/data.py", line 476, in DataReader
    session=session,
  File "/mnt/pandas_datareader/base.py", line 93, in read
    return self._read_one_data(self.url, self.params)
  File "/mnt/pandas_datareader/eurostat.py", line 37, in _read_one_data
    data = read_sdmx(resp.content, dsd=dsd)
  File "/mnt/pandas_datareader/io/sdmx.py", line 60, in read_sdmx
    raise ValueError(result)
ValueError: Query size exceeds maximum limit (1000000 entries).
```

Please identify a narrower example query.

**Comment by gliptak** [comment]
https://github.com/pydata/pandas-datareader/issues/384

**Comment by gliptak** [comment]
Please consider closing.
