### ISSUE TITLE
Eurostat -  Query size exceeds maximum limit

### ISSUE THREAD

**Issue by HristoBuyukliev** [pydata/pandas-datareader#384]
`eu_trade_since_1999 = web.DataReader("DS-022469", 'eurostat')`

gives the error message 

>---------------------------------------------------------------------------
>ValueError                                Traceback (most recent call last)
<ipython-input-4-c1414e943244> in <module>()
----> 1 eu_trade_since_1999 = web.DataReader("DS-022469", 'eurostat')

>/home/hristo/mlenv/local/lib/python2.7/site-packages/pandas_datareader/data.pyc in DataReader(name, data_source, start, end, retry_count, pause, session, access_key)
    157         return EurostatReader(symbols=name, start=start, end=end,
    158                               retry_count=retry_count, pause=pause,
--> 159                               session=session).read()
    160     elif data_source == "edgar-index":
    161         return EdgarIndexReader(symbols=name, start=start, end=end,

>/home/hristo/mlenv/local/lib/python2.7/site-packages/pandas_datareader/base.pyc in read(self)
     70         """ read data """
     71         try:
---> 72             return self._read_one_data(self.url, self.params)
     73         finally:
     74             self.close()

>/home/hristo/mlenv/local/lib/python2.7/site-packages/pandas_datareader/eurostat.pyc in _read_one_data(self, url, params)
     36 
     37         resp = self._get_response(url)
---> 38         data = read_sdmx(resp.content, dsd=dsd)
     39 
     40         try:

>/home/hristo/mlenv/local/lib/python2.7/site-packages/pandas_datareader/io/sdmx.pyc in read_sdmx(path_or_buf, dtype, dsd)
     58         result = list(root.iter(_COMMON + 'Text'))[1].text
     59         if not result.startswith('http'):
---> 60             raise ValueError(result)
     61 
     62         for _ in range(60):

>ValueError: Query size exceeds maximum limit (1000000 entries).

part of the pip freeze output is:
>numpy==1.13.1
pandas==0.20.3
pandas-datareader==0.5.0

**Comment by HristoBuyukliev** [comment]
More specifically, it seems the database in question does have over a million cells - it contains trade flows from country to country, for 200 periods, for nearly 2000 product categories. My question seems to be, how to filter those? For example, I only need 1 product (the total), only one transport mode, and so on, which would reduce the query size nearly 100k fold. 

Eurostat SDMX help says parameters can be specified by separating by a dot, like so:
extra_trade = EurostatReader('DS-043327/.QUANTITY_IN_TONS.CN..TOTAL.AT.1', start = '01.01.2015', end = '03.01.2015')

However, that flat out gives me a '400 bad request' response. Am I missing something?

**Comment by HristoBuyukliev** [comment]
Another update: the parameters do work that way, however I have some issues:

a) the same as in the last comment - I can't just add parameters to the query. It seems EurostatReader makes two queries: firstly for Dataset Structure Definition (DSD), and then the query to get the actual data. 

b) the parameter order seems random - I had to guess url-s such as 
>http://ec.europa.eu/eurostat/SDMX/diss-web/rest/data/DS-022469/.BG.CN.TOTAL.2.4.

or
>http://ec.europa.eu/eurostat/SDMX/diss-web/rest/data/DS-022469/.BG.CN.2.TOTAL.4.

or
>http://ec.europa.eu/eurostat/SDMX/diss-web/rest/data/DS-022469/.BG.CN.TOTAL.4.2.

 until I got 500 or 300 response. 
c) There seems to be a bug with some parameters - it gives me a "500 internal server error". For example, in the query above, I should be able to add "QUANTITY_IN_TONS" as parameter. In practice, I can't for some unknown reason. 

I tried to circumvent a) like so:

    class ParameterEurostatReader(EurostatReader):
        @property
        def dsd_url(self):
            if not isinstance(self.symbols, pd.compat.string_types):
                raise ValueError('data name must be string')

            return '{0}/datastructure/ESTAT/DSD_{1}'.format(
            self._URL, self.symbols.split('/')[0])

    extra_trade = ParameterEurostatReader('DS-043327/.BG.CN.TOTAL.2.4.')
    extra_trade.read()
Which gets the DSD ok, but then gives me the error:
>InvalidIndexError                         Traceback (most recent call last)
<ipython-input-12-a0ca1ab55076> in <module>()
----> 1 extra_trade.read()

>~/mlenv3/lib/python3.4/site-packages/pandas_datareader/base.py in read(self)
     70         """ read data """
     71         try:
---> 72             return self._read_one_data(self.url, self.params)
     73         finally:
     74             self.close()

>~/mlenv3/lib/python3.4/site-packages/pandas_datareader/eurostat.py in _read_one_data(self, url, params)
     37         resp = self._get_response(url)
     38         print(resp.__dict__)
---> 39         data = read_sdmx(resp.content, dsd=dsd)
     40 
     41         try:

>~/mlenv3/lib/python3.4/site-packages/pandas_datareader/io/sdmx.py in read_sdmx(path_or_buf, dtype, dsd)
     88     mseries = _construct_series(obss, name=idx_name, dsd=dsd)
     89 
---> 90     df = pd.DataFrame(mseries, dtype=dtype)
     91     df = df.T
     92     df.columns = mcols

>~/mlenv3/lib/python3.4/site-packages/pandas/core/frame.py in __init__(self, data, index, columns, dtype, copy)
    312                     if is_named_tuple(data[0]) and columns is None:
    313                         columns = data[0]._fields
--> 314                     arrays, columns = _to_arrays(data, columns, dtype=dtype)
    315                     columns = _ensure_index(columns)
    316 

>~/mlenv3/lib/python3.4/site-packages/pandas/core/frame.py in _to_arrays(data, columns, coerce_float, dtype)
   5622         return _list_of_series_to_arrays(data, columns,
   5623                                          coerce_float=coerce_float,
-> 5624                                          dtype=dtype)
   5625     elif isinstance(data[0], Categorical):
   5626         if columns is None:

>~/mlenv3/lib/python3.4/site-packages/pandas/core/frame.py in _list_of_series_to_arrays(data, columns, coerce_float, dtype)
   5716             indexer = indexer_cache[id(index)]
   5717         else:
-> 5718             indexer = indexer_cache[id(index)] = index.get_indexer(columns)
   5719 
   5720         values = _values_from_object(s)

>~/mlenv3/lib/python3.4/site-packages/pandas/core/indexes/base.py in get_indexer(self, target, method, limit, tolerance)
   2581 
   2582         if not self.is_unique:
-> 2583             raise InvalidIndexError('Reindexing only valid with uniquely'
   2584                                     ' valued Index objects')
   2585 

>InvalidIndexError: Reindexing only valid with uniquely valued Index objects

**Comment by gliptak** [comment]
@HristoBuyukliev could you offer a valid SDMX location (with params)? all the three above show ```bad request```

**Comment by HristoBuyukliev** [comment]
@gliptak haha, sorry, no. They probably changed their site since 2017.

**Comment by gliptak** [comment]
Please consider closing.
