### ISSUE TITLE
Install latest development version error

### ISSUE THREAD

**Issue by xtianvillaruz** [pydata/pandas-datareader#385]
Error occurred when i tried this:

C:\Users\user>pip install pandas-datareader
Requirement already satisfied: pandas-datareader in c:\programdata\anaconda3\lib\site-packages
Requirement already satisfied: requests-file in c:\programdata\anaconda3\lib\site-packages (from pandas-datareader)
Requirement already satisfied: requests-ftp in c:\programdata\anaconda3\lib\site-packages (from pandas-datareader)
Requirement already satisfied: requests>=2.3.0 in c:\programdata\anaconda3\lib\site-packages (from pandas-datareader)
Requirement already satisfied: pandas>=0.17.0 in c:\programdata\anaconda3\lib\site-packages (from pandas-datareader)
Requirement already satisfied: six in c:\programdata\anaconda3\lib\site-packages (from requests-file->pandas-datareader)
Requirement already satisfied: python-dateutil>=2 in c:\programdata\anaconda3\lib\site-packages (from pandas>=0.17.0->pandas-datareader)
Requirement already satisfied: pytz>=2011k in c:\programdata\anaconda3\lib\site-packages (from pandas>=0.17.0->pandas-datareader)
Requirement already satisfied: numpy>=1.7.0 in c:\programdata\anaconda3\lib\site-packages (from pandas>=0.17.0->pandas-datareader)

C:\Users\user> pip install git+https://github.com/pydata/pandas-datareader.git
Collecting git+https://github.com/pydata/pandas-datareader.git
  Cloning https://github.com/pydata/pandas-datareader.git to c:\users\user\appdata\local\temp\pip-y5xopm1i-build
  Error [WinError 2] The system cannot find the file specified while executing command git clone -q https://github.com/pydata/pandas-datareader.git C:\Users\user\AppData\Local\Temp\pip-y5xopm1i-build
Cannot find command 'git'

C:\Users\user>

thanks!

**Comment by HristoBuyukliev** [comment]
You don't have git installed.

**Comment by xtianvillaruz** [comment]
Thank you, but I can't install git.

this is what i get when trying installing it.


(C:\ProgramData\Anaconda3) C:\Users\user>!conda install git
'!conda' is not recognized as an internal or external command,
operable program or batch file.

(C:\ProgramData\Anaconda3) C:\Users\user>conda install git
Fetching package metadata .....An unexpected error has occurred.
Please consider posting the following information to the
conda GitHub issue tracker at:

    https://github.com/conda/conda/issues



Current conda install:

               platform : win-64
          conda version : 4.3.8
       conda is private : False
      conda-env version : 4.3.8
    conda-build version : not installed
         python version : 3.6.0.final.0
       requests version : 2.12.4
       root environment : C:\ProgramData\Anaconda3  (writable)
    default environment : C:\ProgramData\Anaconda3
       envs directories : C:\ProgramData\Anaconda3\envs
          package cache : C:\ProgramData\Anaconda3\pkgs
           channel URLs : https://conda.anaconda.org/anaconda-fusion/win-64
                          https://conda.anaconda.org/anaconda-fusion/noarch
                          https://repo.continuum.io/pkgs/free/win-64
                          https://repo.continuum.io/pkgs/free/noarch
                          https://repo.continuum.io/pkgs/r/win-64
                          https://repo.continuum.io/pkgs/r/noarch
                          https://repo.continuum.io/pkgs/pro/win-64
                          https://repo.continuum.io/pkgs/pro/noarch
                          https://repo.continuum.io/pkgs/msys2/win-64
                          https://repo.continuum.io/pkgs/msys2/noarch
            config file : C:\Users\user\.condarc
           offline mode : False
             user-agent : conda/4.3.8 requests/2.12.4 CPython/3.6.0 Windows/10 Windows/10.0.15063



`$ C:\ProgramData\Anaconda3\Scripts\conda-script.py install git`




    Traceback (most recent call last):
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\exceptions.py", line 617, in conda_exception_handler
        return_value = func(*args, **kwargs)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main.py", line 137, in _main
        exit_code = args.func(args, p)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\main_install.py", line 80, in execute
        install(args, parser, 'install')
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\cli\install.py", line 210, in install
        unknown=index_args['unknown'], prefix=prefix)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\index.py", line 120, in get_index
        index = fetch_index(channel_priority_map, use_cache=use_cache)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\index.py", line 445, in fetch_index
        repodatas = _collect_repodatas(use_cache, urls)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\index.py", line 433, in _collect_repodatas
        repodatas = _collect_repodatas_serial(use_cache, urls)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\index.py", line 401, in _collect_repodatas_serial
        for url in urls]
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\index.py", line 401, in <listcomp>
        for url in urls]
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\index.py", line 141, in func
        res = f(*args, **kwargs)
      File "C:\ProgramData\Anaconda3\lib\site-packages\conda\core\index.py", line 391, in fetch_repodata
        with open(cache_path, 'w') as fo:
    PermissionError: [Errno 13] Permission denied: 'C:\\ProgramData\\Anaconda3\\pkgs\\cache\\2116b818.json'


(C:\ProgramData\Anaconda3) C:\Users\user>pip install git
Collecting git
  Could not find a version that satisfies the requirement git (from versions: )
No matching distribution found for git

**Comment by HristoBuyukliev** [comment]
Git is not a python library. Git is a version control system. That's where "github" gets it's name from. Google it.

**Comment by xtianvillaruz** [comment]
Oh, i had that before and i uninstalled it coz i installed anaconda.
Sorry for being stupid...

Now it works!

Thank you so much!

**Comment by gliptak** [comment]
@xtianvillaruz If your issue is solved, please close the ticket.

**Comment by xtianvillaruz** [comment]
sorry.

ok thanks.
