### ISSUE TITLE
I can't get kosdaq historical from yahoo and google.

### ISSUE THREAD

**Issue by ryulstory** [pydata/pandas-datareader#387]
hello. all.
I am korean.
there are two kinds of stock in korea. it is KRX and KOSDAQ.
I can get data KRX. but i cannot get data KOSDAQ.

i can get data KRX from that code.

`df = data.DataReader("KRX:035420", "google", start, end)`

but i cannot get data KOSDAT from code.

`df = data.DataReader("KOSDAQ:003100", "google", start, end)`

could you tell me how to get it?

**Comment by bashtage** [comment]
These APIs are deprecated.
