### ISSUE TITLE
Wrong data from Yahoo

### ISSUE THREAD

**Issue by vvug** [pydata/pandas-datareader#388]
I'm downloading data from Yahoo and Google in this way:
```python
start = datetime.date(2000, 1, 1)
end = datetime.date(2000, 12, 31)
data = pdr.DataReader("ORCL", "yahoo", start, end)
#data = pdr.DataReader("ORCL", "google", start, end)

data.to_csv("data.csv")
```
the problem is that the two outputs differ a lot! This is from Google:
```
Date,Open,High,Low,Close,Volume
2000-01-03,124.63,125.19,111.63,118.13,23950800
2000-01-04,115.5,118.63,105.0,107.69,3852200
2000-01-05,101.63,106.38,96.0,102.0,16035300
[...]
```
and this from Yahoo:
```
Date,Open,High,Low,Close,Adj Close,Volume
2000-01-03,31.15625,31.296875,27.90625,29.53125,26.795395,98114800
2000-01-04,28.875,29.65625,26.25,26.921875,24.427761,116824800
2000-01-05,25.40625,26.59375,24.0,25.5,23.137615,166054000
[...]
```
Check for example how the closing price is completely different. As I can compare this data from [another source](https://gbeced.github.io/pyalgotrade/docs/v0.16/html/tutorial.html) I'm convinced that the Yahoo data is wrong. Unfortunately Google does not give the Adjusted Close information, which is what I need.

I'm using `pandas-datareader` 0.5.0 on Python 2.7.13

**Comment by vvug** [comment]
The same happens with Python 3.6.2.

**Comment by vvug** [comment]
Now I tried again, hoping it was a temporary problem. I did run my usual code:
```python
start = dt.date(2000, 1, 1)
end = dt.date(2000, 12, 31)
data = pdr.DataReader("ORCL", "yahoo", start, end)
data.to_csv("orcl-2000y.csv")
```
and now I get an entry from outside the time window I defined:
```
$ head orcl-2000y.csv
Date,Open,High,Low,Close,Adj Close,Volume
1999-12-31,27.84375,28.34375,27.703125,28.015625,25.420181,10714800
2000-01-03,31.15625,31.296875,27.90625,29.53125,26.795395,98114800
[...]
```
This didn't happen in the past, something is definitely wrong.

**Comment by lcshiung** [comment]
Oracle split twice in 2000. Yahoo's data is adjusted for splits. If you look at Google's data after Oct 12, 2000, they should be similar to Yahoo.

**Comment by bashtage** [comment]
Yahoo has been deprecated.
