### ISSUE TITLE
Add Alpha Vantage as data source?

### ISSUE THREAD

**Issue by gliptak** [pydata/pandas-datareader#389]
https://www.alphavantage.co/documentation/

Requires an API key

**Comment by rsvp** [comment]
Before releasing our own independent solution, we expect to
make a pull request to the pandas_datareader repository:
https://github.com/rsvp/fecon235/issues/7

**Comment by SteffenNa** [comment]
can only second this. have been using alpha vantage for a while now. Found their API is reliable and the data quality is good.

**Comment by rsvp** [comment]
What is the pandas_datareader **policy** on requiring the user to get an ***API key
from the vendor***? Will a pull request be accepted if there was such a requirement?

**Comment by gliptak** [comment]
There is already precedent with Enigma

https://github.com/pydata/pandas-datareader/blob/master/pandas_datareader/enigma.py

We will request adding them to Travis and ReadTheDocs

https://github.com/pydata/pandas-datareader/issues/370

**Comment by rsvp** [comment]
Maybe the vendor should be contacted, and be asked to contribute
their Python wrapper compatible within pandas_datareader.
This way the code is most likely to be maintained.

**Comment by MichaelWS** [comment]
its a free api key.  I am not sure if they would write it.

**Comment by gliptak** [comment]
I didn't find vendor implementation, but there is https://github.com/RomelTorres/alpha_vantage

@RomelTorres

**Comment by RomelTorres** [comment]
Hello there, I maintain the python wrapper as much as I can, usually the vendor contacts me whenever there is something new, to make sure I update it. I don't think AlphaVantage itself will release a python wrapper for its API call.

**Comment by gliptak** [comment]
@RomelTorres Might you consider adding your codebase into ```pandas-datareader```? Thanks

**Comment by RomelTorres** [comment]
@gliptak HI could do it, but how would be the best way to tackle that? Should I add the original library as a dependency and then send a PR to you guys? or should I port the code base only (That'd mean two things to maintain). 
Also, what do you guys want from alpha vantage, everything? or just the stock information?

BR Romel

**Comment by gliptak** [comment]
@RomelTorres First a disclaimer, I'm not an member/committer for ```pandas-datareader```.

My understanding is that the preference would be to not rely on a library (here is the current list of dependencies https://github.com/pydata/pandas-datareader/blob/master/setup.py#L28)

After you could consider using ```pandas-datareader``` in your projects, allowing to pull in additional data sources.

As for the data types, there is already stock and FX data (at various timeframes) from other sources, but you might be the first with cryptocurrency data :)

I think many users generate technical indicators from the "raw" data.

@davidastephens @jreback Please comment.

Thanks

**Comment by addisonlynch** [comment]
@RomelTorres have you had a chance to look into this? If so, let me know if you'd like any assistance. If not, I have some time to work on it now and was going to base the readers off of your library.

**Comment by RomelTorres** [comment]
Hi @addisonlynch I haven't had much time to be honest (a lot of projects going on atm) If you want you can base it off mine.
Saludos, Romel

**Comment by addisonlynch** [comment]
I created a pull which implements most of the API. There are some questsions/topics for discussion in the comment. Let me know what you think.
