### ISSUE TITLE
0.15.2 causing problems with pandas.io.data.Options

### ISSUE THREAD

**Issue by aisthesis** [pydata/pandas-datareader#39]
Identical with #22, as the issue isn't fixed. Are the changes reflected in a version that I can specify to be sure to pick them up? When I install from `pip` it looks as if the code hasn't been changed. See my latest comments under #22.

**Comment by dstephens99** [comment]
I've release v0.1.1 on pip.  It should have the fix in it.

I can't do anything about the version of pandas on pip until the next release there.    This is actually the reason why we split the packages (in order to have faster release cycles here).

Let me know if you still have issues with it.

**Comment by aisthesis** [comment]
Great! I'll try it specifying pandas-datareader>=0.1.1

**Comment by aisthesis** [comment]
Thanks for pushing the new release. Looks like it's working.
