### ISSUE TITLE
Add Tiingo as data source?

### ISSUE THREAD

**Issue by gliptak** [pydata/pandas-datareader#390]
https://api.tiingo.com/docs/general/overview

Requires an API key

**Comment by rsvp** [comment]
Before releasing our own independent solution, we expect to
make a pull request to the pandas_datareader repository:
https://github.com/rsvp/fecon235/issues/7

**Comment by hydrosquall** [comment]
If someone picks this up, they may find the `tiingo-python` package that I've been developing as a stepping-stone to adding functionality to `pandas-datareader`. https://github.com/hydrosquall/tiingo-python .
