### ISSUE TITLE
It seems that Google does no longer provide historical stock data?

### ISSUE THREAD

**Issue by paintdog** [pydata/pandas-datareader#391]
It seems that Google does no longer provide historical stock data respectively Google does no longer update the data. Is this correct? Is there a solution? Will there be any other sources (in the near future)?

With pandas-datareader and source "google" you can only get data until 2017-09-05 :(

```
import pandas_datareader.data as wb
import datetime

web_df = wb.DataReader("ETR:DAI", 'google',
                       datetime.date(2017,9,1),
                       datetime.date(2017,9,9))

print(web_df)
```

**Comment by rsvp** [comment]
Confirmation and alternatives: https://github.com/rsvp/fecon235/issues/7 
seeking solutions to merge into pandas_datareader

Several years ago Google terminated their quote retrieval API for sheets, 
but there was enough public backslash that it was reinstated.
So the current JSON termination might not be final.

**Comment by paintdog** [comment]
Update!

With the source code above you will now get the following result:
```
             Open   High    Low  Close   Volume
Date                                           
2017-09-01  61.38  62.16  61.22  61.80  3042884
2017-09-04  61.40  62.01  61.31  61.84  1802854
2017-09-05  62.01  62.92  61.77  62.42  3113816
2017-09-08  64.59  65.40  64.53  64.83  2733424
```
This means to me that google has not stopped the data delivering at all; there are now 2 dates without data...

**Comment by paintdog** [comment]
Since two days Google only delivers data for one year, this means you can get with pandas only data from 2016-09-16 till 2017-09-14, which is not so great.

**Comment by lmclupr** [comment]
I hav the same issue.  I only get one year of data, being the last year, regardless of start/end dates.  Is this permanent, or a throttling issue?

**Comment by godknowspe** [comment]
I just did some research on this issue and post the result here:
https://stackoverflow.com/questions/46259528/datareader-google-finance-date-not-working/46356247#46356247

Google still offer the historical stock data, but the URL has changed.

**Comment by rsvp** [comment]
But unfortunately, for PR https://github.com/pydata/pandas-datareader/pull/402/commits/eac67a4b60c1f6b67f0a4323fa66faf49641b77b 
the required Travis CI build has failed.

**Comment by bashtage** [comment]
As of v0.7.0 Google finance and Morningstar have been immediately deprecated due to large changes in their API and no stable replacement.
