### ISSUE TITLE
Add Robinhood as data source?

### ISSUE THREAD

**Issue by femtotrader** [pydata/pandas-datareader#392]
https://github.com/sanko/Robinhood/blob/master/Quote.md

from: https://www.reddit.com/r/algotrading/comments/6ygdsg/google_cancelled_their_json_stock_data_feeds_last/

**Comment by gliptak** [comment]
This didn't require an API key https://api.robinhood.com/quotes/?symbols=MSFT,FB,TSLA

**Comment by femtotrader** [comment]
This is only for current quotes.

Here is an example URL for historical quotes

https://api.robinhood.com/quotes/historicals/?symbols=MSFT,FB,TSLA&interval=day
