### ISSUE TITLE
Incorrect split calculation in yahoo-actions

### ISSUE THREAD

**Issue by tibkiss** [pydata/pandas-datareader#396]
When yahoo-actions is used to fetch split information then the resulting value is either 0 or raises ZeroDivisionError. 

YahooActionReader tries to eval the returned string then take the reciprocal of the evaluated statement: 
https://github.com/pydata/pandas-datareader/blob/331e3895c51326e87e69325e1a14f1e350cb832e/pandas_datareader/yahoo/actions.py#L35

If the split results reduced number of stocks then the eval'd value will be correct, but the reciprocal calculation will result 0 as integers are used by the operation:
```
In [24]: 1/eval('2/1')
Out[24]: 0
```
This issue could be fixed by specifying 1.0 in the numerator.

If the split results increased number of stocks then the `eval()` will yield a zero, which is used in the denominator causing ZeroDivisionError:
```
In [26]: 1/eval('1/2')
---------------------------------------------------------------------------
ZeroDivisionError                         Traceback (most recent call last)
<ipython-input-26-dc71badc23e7> in <module>()
----> 1 1/eval('1/2')

ZeroDivisionError: integer division or modulo by zero
```
One possible fix could be to parse the string, convert the numerator and denominator to float then calculate the proper split value.

Env: pandas-datareader==0.5.0, Python 2.7

**Comment by bashtage** [comment]
Yahoo Actions has been deprecated.
