### ISSUE TITLE
Datareader doesn't download the desired samples as instructed

### ISSUE THREAD

**Issue by yongsua1989** [pydata/pandas-datareader#401]
Hi, I would like to download only the stock price data for 3 months from Google Finance, but it keeps providing me data for one year. How do I slice the data I want or re-download the data I want?

> from pandas_datareader import data
> from datetime import datetime
> 
> cname = "KLSE:AXIATA" # Yahoo:6888.KL #Google: KLSE:AXIATA
> 
> wname = "google"
> 
> start= datetime(2017, 7, 15)
> 
> end=datetime(2017, 9, 15)
> 
> price = data.DataReader(cname, wname, start=start, end=end)["Close"].pct_change()

![g](https://user-images.githubusercontent.com/31859413/30623041-f13c5478-9de7-11e7-8da9-3fda713cc211.png)

**Comment by yongsua1989** [comment]
Anyway to slice the sample data? Is it possible instead of downloading whole year of data?

**Comment by rsvp** [comment]
The temporary problem with specifying dates is diagnosed here: https://github.com/pydata/pandas-datareader/issues/394#issuecomment-330649295 

Getting ***more*** data than you need should not be a major problem with pandas, e.g. use
```
 DataFrame.tail(n=64)
```
to approximate 3 months of daily data.

**Comment by i-frost** [comment]
I am doing this to get specific dates

df = df_reader.to_frame(filter_observations=False)

df[(df.index.get_level_values('Date')>='2017-09-21') & (df.index.get_level_values('Date')<='2017-09-22')]

**Comment by rsvp** [comment]
@i-frost as of v0.20.1 Panel is deprecated: https://pandas.pydata.org/pandas-docs/stable/whatsnew.html#whatsnew-0200-api-breaking-deprecate-panel and thus ".to_frame".

For contiguous dates, the easier expression would be: `df['2017-09-21':'2017-09-22']` which relies on index slicing.

**Comment by i-frost** [comment]
Hey @rsvp, I am getting a Panel back from the reader call should it be a MultiIndex instead?

pd.__version__
'0.20.3'
>>> df_reader = web.DataReader(['III'], 'google', (2017, 9, 23), (2017, 9, 23))
>>> df_reader
<class 'pandas.core.panel.Panel'>

**Comment by HJ1nitj** [comment]
Hi, 
I am getting this 'ImmediateDeprecationError(DEP_ERROR_MSG.format('Yahoo Daily'))' while fetching the financial data from yahoo.

please help me with this issue.

**Comment by bashtage** [comment]
This is not fixable. Yahoo is totally broken until someone figures out a way to rewrite it from scratch using a different method.

**Comment by HJ1nitj** [comment]
So can you please suggest some alternative?

**Comment by bashtage** [comment]
You can manually download data from Yahoo in the browser. Or you could see if the data you need is available from one of the other sources (e.g., Morningstar, IEX, etc.).  AFAIK there is no access to Yahoo from Python that works now.

**Comment by HJ1nitj** [comment]
thanks sir...
