### ISSUE TITLE
NaN for the start date

### ISSUE THREAD

**Issue by ComeAsUAre** [pydata/pandas-datareader#405]
Hello,
I just experienced a strange behaviour with some European Equities: 
`
import pandas_datareader.data as web
start='2017-05-25'
end='2017-10-01'

f=web.DataReader('ASML.AS', 'yahoo', start=start, end=end)
`

The first line of the resulting DF is 2017-05-24 and it has NaN for all attributes (open, high, low close etc.). 
If I move the start date back another day, the data for 2017-05-24 is included, but the day before then has the NaNs.

On Yahoo Finance, the historical data seems to be complete for all days including 2017-05-24:
https://finance.yahoo.com/quote/ASML.AS/history?p=ASML.AS

I am not sure what's causing this. Any feedback would be appreciated!

(python 3.6.2, pandas-datareader 0.5.0)

**Comment by bashtage** [comment]
Yahoo has been deprecated.
