### ISSUE TITLE
Enigma - JSONDecodeError

### ISSUE THREAD

**Issue by annjieching** [pydata/pandas-datareader#406]
Running python 3.6 and just trying to execute the sample code provided - wondering what's gone wrong here. I'm not a developer, wish I could be more helpful! 

`df = pdr.get_data_enigma('enigma.trade.ams.toxic.2015', os.getenv('ENIGMA_API_KEY'))
`

```

/Users/annjieching/anaconda/lib/python3.6/json/decoder.py in raw_decode(self, s, idx)
    355             obj, end = self.scan_once(s, idx)
    356         except StopIteration as err:
--> 357             raise JSONDecodeError("Expecting value", s, err.value) from None
    358         return obj, end

JSONDecodeError: Expecting value: line 1 column 1 (char 0) 
```

Thanks so much.

**Comment by hydrosquall** [comment]
@annjieching:

Thanks for your note! Which code sample were you using?

Enigma changed the public data source from `app.enigma.io` to `public.enigma.com` in June of this year, and the changes that I submitted to this library to accommodate the new data source just went through today. To make the above code sample work, you'll want to run the following steps in your terminal when inside a folder where you store code:

```bash
git clone https://github.com/pydata/pandas-datareader.git
cd pandas-datareader
python setup.py develop
```

Two other gotchas are possible:

- Make sure you have an environment variable set called `ENIGMA_API_KEY`. If you don't have an API key, the code sample won't work. You can find yours under the `account settings` tab when you're logged in to `public.enigma.com`
- The `dataset_id` for the ams.toxic dataset you're looking for is `701a6be6-ff66-4332-8d53-9cd80b201bd5`. You can find that by taking the trailing part of the URL when you search for the old identifier of `enigma.trade.ams.toxic.2015` in the `public.enigma.com` search bar.  This means your code would look something more like:

```python
dataset_id = "701a6be6-ff66-4332-8d53-9cd80b201bd5"
df = pdr.get_data_enigma(dataset_id, os.getenv('ENIGMA_API_KEY'))
```

Please feel free to tag me again if you have any further questions! I'm on the software engineering team at Enigma, so it's always great to see more people getting into trying our data :). (And thanks @gliptak for linking this issue to the latest merged PR.)

**Comment by bashtage** [comment]
It looks like this is fixed in master, so closing.  Reopen if still a problem.
