### ISSUE TITLE
 Could not find a suitable TLS CA certificate bundle, invalid path: D:\Anaconda3\lib\site-packages\requests\cacert.pem

### ISSUE THREAD

**Issue by xuantianfengwu** [pydata/pandas-datareader#407]
I met this problem when running codes:

import pandas_datareader.data as web
start = datetime.datetime(2010, 1, 1)
end = datetime.datetime(2013, 1, 27)
f = web.DataReader("^GSPC", 'yahoo', start, end)

Anybody has any solution?
Thanks a lot!

**Comment by gliptak** [comment]
This is likely an Anaconda specific issue, probably best discussed at their support forums.
https://github.com/requests/requests/issues/4171

**Comment by bashtage** [comment]
Closing since anaconda issue.
