### ISSUE TITLE
results are one day off

### ISSUE THREAD

**Issue by Dmon1Unlimited** [pydata/pandas-datareader#409]
Using the below:

```
import pandas_datareader as pdr
print(pdr.get_data_yahoo('ANZ.AX'))
```
```
I got the below results (just showing for october):

2017-10-01  29.740000  30.049999  29.629999  29.900000  29.900000   2918932
2017-10-02  29.950001  30.160000  29.820000  29.870001  29.870001   4525051
2017-10-03  29.770000  29.940001  29.240000  29.240000  29.240000   6629463
2017-10-04  29.370001  29.400000  29.049999  29.090000  29.090000   3970583
2017-10-05  29.450001  29.500000  29.230000  29.480000  29.480000   3458463
2017-10-08  29.459999  29.770000  29.299999  29.700001  29.700001   3333736
2017-10-09  29.610001  29.820000  29.549999  29.770000  29.770000   2765387
2017-10-10  29.879999  30.000000  29.790001  29.900000  29.900000   3559353
2017-10-11  30.040001  30.049999  29.799999  30.040001  30.040001   4020839
2017-10-12  30.059999  30.200001  30.000000  30.059999  30.059999   4170310
```

but if i compare against [Yahoo finance data](https://finance.yahoo.com/quote/ANZ.AX/history?p=ANZ.AX)

```
Oct 02, 2017 | 29.74 | 30.05 | 29.63 | 29.90 | 29.90 | 2,918,932
Oct 03, 2017 | 29.95 | 30.16 | 29.82 | 29.87 | 29.87 | 4,525,051
Oct 04, 2017 | 29.77 | 29.94 | 29.24 | 29.24 | 29.24 | 6,629,463
Oct 05, 2017 | 29.37 | 29.40 | 29.05 | 29.09 | 29.09 | 3,970,583
Oct 06, 2017 | 29.45 | 29.50 | 29.23 | 29.48 | 29.48 | 3,458,463
Oct 09, 2017 | 29.46 | 29.77 | 29.30 | 29.70 | 29.70 | 3,333,736
Oct 10, 2017 | 29.61 | 29.82 | 29.55 | 29.77 | 29.77 | 2,765,387
Oct 11, 2017 | 29.88 | 30.00 | 29.79 | 29.90 | 29.90 | 3,559,353
Oct 12, 2017 | 30.04 | 30.05 | 29.80 | 30.04 | 30.04 | 4,020,839
Oct 13, 2017 | 30.06 | 30.20 | 30.00 | 30.06 | 30.06 | 4,170,310
```

i can see all the data there but it is one day off. The code's result for 2017-10-12 matches the website's result for 2017-10-13 etc

Whereas if i use:

```import pandas_datareader as pdr
import datetime

start = datetime.date(2016, 10, 1)
end = datetime.date(2017, 10, 16)
data = pdr.DataReader("ANZ.AX", "yahoo", start, end)```

the results seem better. what is the difference between DataReader and get_data_yahoo?

**Comment by ralexx** [comment]
This looks like an issue on Yahoo's side, not pandas-datareader. Perhaps you can work around.

You are comparing the output from pandas-datareader against the Yahoo Finance web page display, which pandas-datareader does not use. Try clicking the "Download Data" link on that page (which is the URL that pandas-datareader does use) and compare against the web page. When I did it just now I saw the dates in the downloaded CSV file were one day behind the web page, as you have pointed out.

As for results that "seem better", there is no distinction between calling `get_data_yahoo` and `DataReader` with the `yahoo` argument. They both call the `YahooDailyReader` class and its parent classes to do the scraping/parsing.

**Comment by davidastephens** [comment]
I'm guessing this is a location issue due to this being an Australian equity.  Not sure if there is anything we can do from this end.
