### ISSUE TITLE
Update PyPI Release / Readthedocs

### ISSUE THREAD

**Issue by hydrosquall** [pydata/pandas-datareader#420]
Hi @jreback / @davidastephens / anyone with push access: 

Would it be possible to cut a new `0.6.0` release to PyPI, or bump the current version to `0.5.1` so that the ReadTheDocs documentation can be updated? This is because the old  usage directions for `EnigmaDataReader` no longer apply.

The PR #380 was merged last month into the current `0.5.0` build, but the (unreleased) docs reference the `0.6.0` build as directed in the PR. https://github.com/pydata/pandas-datareader/blame/master/docs/source/remote_data.rst#L210

This mismatch may contribute to confusion for other issues such as #406 .

**Comment by alexukf** [comment]
I would also be interested in a new release, since https://github.com/pydata/pandas-datareader/pull/404 fixes the following code, which doesn't work in `0.5.0`:
```
import pandas_datareader.data as web

print web.DataReader('SPY', 'google')
```

**Comment by bashtage** [comment]
Released
