### ISSUE TITLE
World Bank remote data error: need new url?

### ISSUE THREAD

**Issue by SummerIsHere** [pydata/pandas-datareader#421]
I am running the Anaconda distribution of Python3. I made sure I sure that pandas_datareader was up to date by running:

`pip install -U pandas_datareader`

Then I tried running the following:

```
from pandas_datareader import wb
wb.download(indicator='SP.POP.TOTL', country='WLD', start=1800, end=2100)
```

Upon which I get the error, traceback:

```
Traceback (most recent call last):
  File "/Users/jche11/anaconda/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2862, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-1a0b0bf45d07>", line 2, in <module>
    wb.download(indicator='SP.POP.TOTL', country='WLD', start=1800, end=2100)
  File "/Users/jche11/anaconda/lib/python3.6/site-packages/pandas_datareader/wb.py", line 379, in download
    **kwargs).read()
  File "/Users/jche11/anaconda/lib/python3.6/site-packages/pandas_datareader/wb.py", line 163, in read
    return self._read()
  File "/Users/jche11/anaconda/lib/python3.6/site-packages/pandas_datareader/wb.py", line 172, in _read
    df = self._read_one_data(self.url + indicator, self.params)
  File "/Users/jche11/anaconda/lib/python3.6/site-packages/pandas_datareader/base.py", line 81, in _read_one_data
    out = self._get_response(url, params=params).json()
  File "/Users/jche11/anaconda/lib/python3.6/site-packages/pandas_datareader/base.py", line 139, in _get_response
    raise RemoteDataError('Unable to read URL: {0}'.format(url))
pandas_datareader._utils.RemoteDataError: Unable to read URL: http://api.worldbank.org/countries/WLD/indicators/SP.POP.TOTL?date=1800%3A2100&per_page=25000&format=json
```

Copying that last url from the error message into a browser results in a request error from that page.

http://api.worldbank.org/countries/WLD/indicators/SP.POP.TOTL?date=1800%3A2100&per_page=25000&format=json

I looked at the World Bank API [documentation](https://datahelpdesk.worldbank.org/knowledgebase/articles/898581-api-basic-call-structure), and it appears that the base url is now http://api.worldbank.org/v2/

I modified the url from the error message to add "/v2"  after worldbank.org:

http://api.worldbank.org/v2/countries/WLD/indicators/SP.POP.TOTL?date=1800%3A2100&per_page=25000&format=json

Copying that into a browser successfully returned data

**Comment by kflamm** [comment]
I'm getting a similar problem when attempting to import WB data that shows up OK in wb.search().
With some series (GDP per capita), wb.download returns correct data. But with other series (cellphone coverage), I get a  JSON request error. 

This is a real problem, because the code example in the pandas_datareader documentation for 'wb' seems to no longer work when run.

Like SummerIsHere, I find that inserting '/v2' after worldbank.org seems to return data correctly when I get the JSON request error.

It is confusing that the original API url coded into pandas_datareader seems to work with some series, but not others. The wb.search() function still seems to work OK. 

Any hope this is going to get resolved soon?
Thanks for a great package. I was hoping to use the pandas_datareader's wb function in a class, but not workable if the function is not working reliably.

**Comment by kflamm** [comment]
To be clear, the documentation example works if you use the data series shown in that documentation ('IT.MOB.COV.ZS'), but fails if you instead use data series ('IT.CEL.COVR.ZS') which appears to include non-African countries. Both series are shown after wb.search('cell.*%').iloc[:,:2] . Two other series showing up in the documentation example search (the two cellphone user series) no longer show up.

As previously stated, inserting '/v2' after worldbank.org seems to create a correctly formed url to return the IT.CEL.COVR.ZS series, but this apparently is unneeded with the other series. Is it possible that wb.search() is somehow querying both versions of the World Bank data, but that wb.download is only working with the earlier version of the World Bank data archive?

**Comment by westurner** [comment]
Do the tests pass after changing to the v2 URL?
Is the API available over HTTPS?


https://github.com/pydata/pandas-datareader/blob/master/pandas_datareader/wb.py

https://github.com/pydata/pandas-datareader/blob/master/pandas_datareader/tests/test_wb.py

**Comment by westurner** [comment]
Should there be an additional test for the cases you've mentioned?

**Comment by bashtage** [comment]
Every test for every non-deprecated module passes now (except 1 for OECD, and it almost passes).

**Comment by bashtage** [comment]
Looks like https is supported.

**Comment by westurner** [comment]
Thanks!
