### ISSUE TITLE
Limitation of scraping in historical series through Google Quotes with web.dataReader

### ISSUE THREAD

**Issue by nativanando** [pydata/pandas-datareader#422]
I'm trying to scrape the historical series through the pandas web.dataReader but the period returned is only between 2016 and 2017.

Has there been any update limiting this search or is it a bug caused by the API?

Here is my code:
```
class Crawler:

    def __init__(self, nome_empresa, codigo):
        self.start = datetime.datetime(2001, 1, 1)
        self.end = datetime.datetime(2017, 8, 31)
        self.nome_empresa = nome_empresa
        self.codigo = codigo

    def executa_busca(self):
        file = web.DataReader(self.codigo, 'google',  self.start, self.end)
        file.to_csv('~/Documentos/TCC/dist-tcc/Implementacao/dados_calculados/dados_brutos/' + self.nome_empresa + '.txt')
```

**Comment by rsvp** [comment]
The issue is currently unresolved.
For an overview, and alternatives, see 
https://github.com/rsvp/fecon235/issues/7

**Comment by paintdog** [comment]
In [this thread](https://github.com/pydata/pandas-datareader/issues/418) a working url sheme was presented by VicTangg to get again "full" access to the historical data! It would be nice if this url sheme could be used to fix this bug soon.

For example:
https://finance.google.com/finance/historical?q=ETR:SIE&startdate=2000/01/01&enddate=2017/05/22&output=csv

**Comment by gliptak** [comment]
@paintdog What does "full" access mean?

This "old style" URL (generated by current pandas_datareader) does work https://finance.google.com/finance/historical?q=ETR:SIE&startdate=Jan%2001,%202017&enddate=Nov%2029,%202017&output=csv

**Comment by paintdog** [comment]
Have you tested your "old style" URL? It doesn't work!!!

Using your url we get stock prices starting at 2-Jan-17 (!). Using the new url sheme we get stock prices starting at 2-Jan-02 (!). Please try it out.

When I understand the current source code then we use http:// instead of https:// in pandas datareader to generate the url. Maybe this is the error!?

**We must fix it asap, I think.**

**Comment by bashtage** [comment]
Google Quotes has been deprecated.
