### ISSUE TITLE
HTTP Connection Failed 

### ISSUE THREAD

**Issue by jig78** [pydata/pandas-datareader#430]
I am trying to install pandas-datareader and I am getting this error below. Can you please help?

(C:\Users\pateljig\AppData\Local\Continuum\anaconda3) C:\Users\pateljig>conda in
stall -c anaconda pandas-datareader
Fetching package metadata ...
CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://conda.anaconda.org/anaconda/win-64/repodata.json>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

ConnectTimeout(MaxRetryError("HTTPSConnectionPool(host='conda.anaconda.org', por
t=443): Max retries exceeded with url: /anaconda/win-64/repodata.json (Caused by
 ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x000
0000005326BA8>, 'Connection to conda.anaconda.org timed out. (connect timeout=9.
15)'))",),)

(C:\Users\pateljig\AppData\Local\Continuum\anaconda3) C:\Users\pateljig>

**Comment by bashtage** [comment]
This is just a random Anaconda error.
