### ISSUE TITLE
Yahoo finance stock pull missing days

### ISSUE THREAD

**Issue by ritviknv** [pydata/pandas-datareader#431]
I'm getting a dataframe with missing days scattered somewhat randomly in between. So if I run the following code, I get the output attached file (zipped for upload). In this file, there are dates that are missing in no particular order. 

Am I doing something wrong? Or is there a limit to the amount of data I can pull? If so, what's the logic for missing dates. Thanks in advance for all the help!

[testOutput.csv.zip](https://github.com/pydata/pandas-datareader/files/1577999/testOutput.csv.zip)
```import pandas_datareader.data as data
import datetime

symbol = 'AMZN'
start = datetime.datetime(1980,1,1)
end = datetime.datetime(2017,10,10)	
df = data.DataReader(symbol,'yahoo',start,end)
df.to_csv('testOutput.csv')`

**Comment by taylor-case-af** [comment]
maybe ur just bad
