### ISSUE TITLE
FRED no longer working

### ISSUE THREAD

**Issue by jhoodsmith** [pydata/pandas-datareader#435]
FRED seems to have changed the URL structure for downloading CSV.

I'm using latest development version of pandas-datareader.

In using the example from the docs I get:

pandas_datareader._utils.RemoteDataError: Unable to read URL: http://research.stlouisfed.org/fred2/series/GDP/downloaddata/GDP.csv

**Comment by oOo0oOo** [comment]
I can also confirm this bug. Getting the same Error.

Found another possible URL after a quick look but not sure if it works in all cases:
https://fred.stlouisfed.org/graph/fredgraph.csv?id=GDP

**Comment by rsvp** [comment]
Cross-ref #436 
https://github.com/pydata/pandas-datareader/pull/436/files 

Thanks to @jhoodsmith

**Comment by NumberChiffre** [comment]
Getting the same error and updated the url using fredgraph, thank you!

**Comment by oOo0oOo** [comment]
Just a quick note: It seems the fred has reverted the URL; the original URL works again...

**Comment by jhoodsmith** [comment]
Good news that the original is working again. 

It might be worth following point by @rsvp above, and make better use of qualifiers. I used 'id' only in #436, as this followed the original code. However, better use of 'freq' and/or begin/end dates will reduce impact on FRED servers.

**Comment by jhoodsmith** [comment]
On a separate issue, I'm getting the same errors as reported by the #436 Travis build when I run tests locally.  There seems to general problems working with OECD and Google Options.

**Comment by rsvp** [comment]
### Working status of old URL

So for the stlouisfed.org domain, how is the ***redirection***
between the *research* and *fred* subdomains taking place?

Any official announcements from FRED as to their intentions?
Perhaps it was an internal experiment accidentally brought 
into production.

**Comment by bashtage** [comment]
Fixed
