### ISSUE TITLE
Python data reader having issues fetching data from Google Finance 

### ISSUE THREAD

**Issue by salehinRafi** [pydata/pandas-datareader#439]
I try to use google but unfortunately, it gave me an error.
I think the issues related to 

>  Google Finance has been renovated. As a part of this process, the Portfolios feature will be taken down soon. You can continue to follow stocks in the new Google Finance. Initially, up to 50 stocks were migrated from your portfolio list, and soon you’ll be able to add stocks from your portfolio to the new Google Finance. You can also download your full portfolio in CSV format, which can be imported into other portfolio services during the transition period. 

[Google Finance](https://finance.google.com/finance)

But when I try Yahoo an error related to **RemoteDataError: Unable to read URL** same as google error. As far as I know, supposedly Yahoo problem already solved. I already update them to the latest version as well.

**Comment by addisonlynch** [comment]
The issue is probably on Google's end, since the services is in may ways deprecated. Thinking of working on a new reader for the alternatives to the Google and Yahoo services, namely AlphaVantage (@rommeltorres) and IEX. Might serve as a decent replacement for them in the datareader

**Comment by bashtage** [comment]
Those and possibly Stooq.

**Comment by bashtage** [comment]
Google's API is unstable.  This now raises a warning.

**Comment by troymyname** [comment]
I am getting the "unstable" message as well.
