### ISSUE TITLE
Add Real Time pricing for Yahoo Data

### ISSUE THREAD

**Issue by djchou** [pydata/pandas-datareader#44]
This is a feature request.  I think adding real time price quotes would add a lot of value to the pandas-datareader.  Anyone agree?

**Comment by hayd** [comment]
+1. You may like to look at https://github.com/lukaszbanasiak/yahoo-finance.

**Comment by dstephens99** [comment]
Isn't the yahoo quote data real time now for US stocks? 

```python
from pandas_datareader.data import get_quote_yahoo

get_quote_yahoo('AAPL')
Out[9]: 
         PE  change_pct   last  short_ratio    time
AAPL  17.28        2.28  127.6          1.3  4:00pm


```
I'll have a look tomorrow during market hours.

**Comment by djchou** [comment]
It looks like that works.  Closing this issue
