### ISSUE TITLE
0.6 Release

### ISSUE THREAD

**Issue by bashtage** [pydata/pandas-datareader#443]
Tasks before 0.6 release

- [x] Decide future of google finance reader
- [x] Decide future of yahoo finance reader
- [x] Decide future of Edgar reader
- [x] Update docs with whatsnew
- [x] Update docs with minimal examples form new readers
- [x] Integrate IEX reader

**Comment by 1rocketdude** [comment]
I vote for abandoning google and yahoo altogether. They have been unstable for many months and do not appear likely to return in a manner that fits with pandas-datareader. The free services like barchart, tiingo, and quandl are mature and stable.

**Comment by rsvp** [comment]
## Re: future of Google and Yahoo finance

Here's an overview of the disruption history 
and some of the alternate remedies:
https://github.com/rsvp/fecon235/issues/7

So far there seems to be no official pronouncements 
about the future of providing equities data in a 
stable manner from neither Google nor Yahoo.

**Comment by bashtage** [comment]
Thanks.  It would be nice to collect views.  I am leaning towards putting something like a `DeprecationError` on Yahoo since it seems to be completely broken and will need to be removed.  Google is more unstable but not completely broken, so this is more difficult.

**Comment by hydrosquall** [comment]
Thank you so much @bashtage ! Just making a note on this thread that when this is released, https://github.com/pydata/pandas-datareader/issues/420 will be resolved.

**Comment by rsvp** [comment]
How is the latest version transmitted downstream to **Anaconda**? 
How are they notified?

Is it possible to `conda` install the HEAD of the master branch? 
(This would be a way to mitigate interim disruptions with Yahoo 
and Google, and get the latest documentation, without waiting 
around for a major release.)

**Comment by bashtage** [comment]
It can take a while for official Anaconda to pick up a module.  Conda-forge can be triggered by users though, and since this package doesn't have any binary requirements, PyPi is as good as anything else.

**Comment by alfredaita** [comment]
Yesterday Jan 15 2018 using Google with DataReader I was able to download 13 years of all the components to the S&P 500 with no issues.
This morning , using the same ipython session I was not able to download any quotes at all.
Immediately I started a new ipython session , with Google and DataReader, and it worked fine.

I would note that I changed the http link in daily.py:

  #return 'http://www.google.com/finance/historical'   original
        return 'http://finance.google.com/finance/historical' # replaced by alfred

**Comment by ralexx** [comment]
@rsvp 
> Is it possible to conda install the HEAD of the master branch?

Use `conda develop /path/to/pandas_datareader` [[doc](https://conda.io/docs/commands/build/conda-develop.html)]

**Comment by addisonlynch** [comment]
@bashtage I've made progress on an IEX reader, I'll have something to take a look at early next week (3 readers- Daily, Quotes, and Actions). Has anyone else gotten started on this? Will commit my work so far to my fork for those who wish to take a look.

**Comment by bashtage** [comment]
There are IEX readers in master now, as of today.  Try these.  Maybe they
could be improved?   Could certainly use more examples.
