### ISSUE TITLE
Unable to install the pandas-datareader package

### ISSUE THREAD

**Issue by rpatel2550** [pydata/pandas-datareader#444]
Hi,

I have been trying to install the pandas-datareader package via the following two methods:

1. C:\>conda install -c anaconda pandas-datareader

This method hung on the following message:

**Fetching package metadata: ...^C**

Once I tried to close the command line window the ^C was added to the line above and the window would not close.

2. C:\>pip install pandas-datareader

**Downloading/unpacking pandas-datareader
  Cannot fetch index base URL https://pypi.python.org/simple/
  Could not find any downloads that satisfy the requirement pandas-datareader
Cleaning up...
No distributions at all found for pandas-datareader
Storing debug log for failure in C:\Users\rpatel2550\pip\pip.log**

This method created an error log file, which I have pasted below:

C:\Program Files (x86)\Anaconda\Scripts\pip-script.py run on 01/12/18 17:52:47
Downloading/unpacking pandas-datareader
  Getting page https://pypi.python.org/simple/pandas-datareader/
  Could not fetch URL https://pypi.python.org/simple/pandas-datareader/: connection error: HTTPSConnectionPool(host='pypi.python.org', port=443): Max retries exceeded with url: /simple/pandas-datareader/ (Caused by <class 'socket.error'>: [Errno 10051] A socket operation was attempted to an unreachable network)
  Will skip URL https://pypi.python.org/simple/pandas-datareader/ when looking for download links for pandas-datareader
  Getting page https://pypi.python.org/simple/
  Could not fetch URL https://pypi.python.org/simple/: connection error: HTTPSConnectionPool(host='pypi.python.org', port=443): Max retries exceeded with url: /simple/ (Caused by <class 'socket.error'>: [Errno 10051] A socket operation was attempted to an unreachable network)
  Will skip URL https://pypi.python.org/simple/ when looking for download links for pandas-datareader
  Cannot fetch index base URL https://pypi.python.org/simple/
  URLs to search for versions for pandas-datareader:
  * https://pypi.python.org/simple/pandas-datareader/
  Getting page https://pypi.python.org/simple/pandas-datareader/
  Could not fetch URL https://pypi.python.org/simple/pandas-datareader/: connection error: HTTPSConnectionPool(host='pypi.python.org', port=443): Max retries exceeded with url: /simple/pandas-datareader/ (Caused by <class 'socket.error'>: [Errno 10051] A socket operation was attempted to an unreachable network)
  Will skip URL https://pypi.python.org/simple/pandas-datareader/ when looking for download links for pandas-datareader
  Could not find any downloads that satisfy the requirement pandas-datareader
Cleaning up...
  Removing temporary dir c:\users\rpatel2550\appdata\local\temp\pip_build_rpatel2550...
No distributions at all found for pandas-datareader

Using this error message I was able to go to this website:
https://pypi.python.org/simple/pandas-datareader/

The most recent file pandas-datareader-0.5.0.tar.gz is evidently available but I don't know how to install it. 

Please help!

Thanks,
R

**Comment by bashtage** [comment]
```
git clone https://github.com/pydata/pandas-datareader
cd pandas-datareader
python setup.py install
```

will get you master.

**Comment by bashtage** [comment]
You might need to update your Anaconda if it is old.

**Comment by rsvp** [comment]
@bashtage hi Kevin, could you kindly tell us how **Anaconda** gets 
hold of new releases? Does someone notify them manually? 
Or is it automated? Is there a conda command to get master HEAD?

Re: `python setup.py install` Will that *properly* install with respect to 
both the system's and Anaconda's versions of Python?

**Comment by rpatel2550** [comment]
Hi Kevin,

Thanks for your response,

I removed all traces of python/ anaconda (older versions etc) from my machine and then installed the latest 64-bit version of anaconda. Then I opened up an anaconda command prompt window and typed the following:

(C:\ProgramData\Anaconda3) C:\Users\rpatel2550> pip install pandas-datareader

The output was as follows:

**Collecting pandas-datareader
  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None))
 after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTT
PSConnection object at 0x000000FE381FB9B0>: Failed to establish a new connection
: [WinError 10051] A socket operation was attempted to an unreachable network',)
': /simple/pandas-datareader/
  Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None))
 after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTT
PSConnection object at 0x000000FE381FB518>: Failed to establish a new connection
: [WinError 10051] A socket operation was attempted to an unreachable network',)
': /simple/pandas-datareader/
  Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None))
 after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTT
PSConnection object at 0x000000FE381FB7F0>: Failed to establish a new connection
: [WinError 10051] A socket operation was attempted to an unreachable network',)
': /simple/pandas-datareader/
  Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None))
 after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTT
PSConnection object at 0x000000FE381FB6A0>: Failed to establish a new connection
: [WinError 10051] A socket operation was attempted to an unreachable network',)
': /simple/pandas-datareader/
  Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None))
 after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTT
PSConnection object at 0x000000FE381FB5C0>: Failed to establish a new connection
: [WinError 10051] A socket operation was attempted to an unreachable network',)
': /simple/pandas-datareader/
  Could not find a version that satisfies the requirement pandas-datareader (fro
m versions: )
No matching distribution found for pandas-datareader**

Still not sure why there is a connection issue - any ideas?

Could you help me understand the exact steps to install this manually? I'm not sure how to do it given your instructions:

git clone https://github.com/pydata/pandas-datareader
cd pandas-datareader
python setup.py install

Thanks,

R

**Comment by rpatel2550** [comment]
Following on:

I went to https://github.com/bashtage/pandas-datareader and downloaded the master file and unzipped it into C:\ProgramData\Anaconda3. Then I opened up the Anaconda command prompt and navigated to the folder pandas-datareader inside the zipped file and executed the setup.py file using python setup.py install. 

The following output occured but it seems hung on the "reading https://pypi.python.org/simple/requests-ftp/" stage (pasted below). I am still not able to import pandas_datareader in jupyter. Please help!

Thanks
R

**
Lots of copying pandas data reader output...
...
...

byte-compiling build\bdist.win-amd64\egg\pandas_datareader\tests\yahoo\test_opti
ons.py to test_options.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\pandas_datareader\tests\yahoo\test_yaho
o.py to test_yahoo.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\pandas_datareader\tests\yahoo\__init__.
py to __init__.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\pandas_datareader\tests\__init__.py to
__init__.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\pandas_datareader\tsp.py to tsp.cpython
-36.pyc
byte-compiling build\bdist.win-amd64\egg\pandas_datareader\wb.py to wb.cpython-3
6.pyc
byte-compiling build\bdist.win-amd64\egg\pandas_datareader\yahoo\actions.py to a
ctions.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\pandas_datareader\yahoo\components.py t
o components.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\pandas_datareader\yahoo\daily.py to dai
ly.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\pandas_datareader\yahoo\options.py to o
ptions.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\pandas_datareader\yahoo\quotes.py to qu
otes.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\pandas_datareader\yahoo\__init__.py to
__init__.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\pandas_datareader\_testing.py to _testi
ng.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\pandas_datareader\_utils.py to _utils.c
python-36.pyc
byte-compiling build\bdist.win-amd64\egg\pandas_datareader\_version.py to _versi
on.cpython-36.pyc
byte-compiling build\bdist.win-amd64\egg\pandas_datareader\__init__.py to __init
__.cpython-36.pyc
creating build\bdist.win-amd64\egg\EGG-INFO
copying pandas_datareader.egg-info\PKG-INFO -> build\bdist.win-amd64\egg\EGG-INF
O
copying pandas_datareader.egg-info\SOURCES.txt -> build\bdist.win-amd64\egg\EGG-
INFO
copying pandas_datareader.egg-info\dependency_links.txt -> build\bdist.win-amd64
\egg\EGG-INFO
copying pandas_datareader.egg-info\not-zip-safe -> build\bdist.win-amd64\egg\EGG
-INFO
copying pandas_datareader.egg-info\requires.txt -> build\bdist.win-amd64\egg\EGG
-INFO
copying pandas_datareader.egg-info\top_level.txt -> build\bdist.win-amd64\egg\EG
G-INFO
creating dist
creating 'dist\pandas_datareader-0+unknown-py3.6.egg' and adding 'build\bdist.wi
n-amd64\egg' to it
removing 'build\bdist.win-amd64\egg' (and everything under it)
Processing pandas_datareader-0+unknown-py3.6.egg
creating c:\programdata\anaconda3\lib\site-packages\pandas_datareader-0+unknown-
py3.6.egg
Extracting pandas_datareader-0+unknown-py3.6.egg to c:\programdata\anaconda3\lib
\site-packages
Adding pandas-datareader 0+unknown to easy-install.pth file

Installed c:\programdata\anaconda3\lib\site-packages\pandas_datareader-0+unknown
-py3.6.egg
Processing dependencies for pandas-datareader==0+unknown
Searching for requests-ftp
Reading https://pypi.python.org/simple/requests-ftp/**

**Comment by bashtage** [comment]
Unfortunately something is wrong with your network and/or pip.

**Comment by rpatel2550** [comment]
I removed all traces of python and anaconda from my machine and then reinstalled anaconda in the root directory C:\. This seemed to allow the pip installer to work.

**Comment by bashtage** [comment]
Ok, closing.
