### ISSUE TITLE
RLS 0.6.0

### ISSUE THREAD

**Issue by bashtage** [pydata/pandas-datareader#453]
There have been a lot of changes in the past few days.  

Please report any issues here.  I there are none raised by the start of next week, 0.6.0 will be released then.

- [x] Add release date to what's new
- [x] Tag release

**Comment by bashtage** [comment]
closes #420

**Comment by rsvp** [comment]
Will the ***deprecation messages*** for 
**yahoo-finance** and **google-finance** 
suggest alternatives means of obtaining 
equities data? What are the fallback plans 
for pandas_datareader?

**Comment by bashtage** [comment]
They don't know.  Open to suggestions -- PRs to improve the messages are welcome. 

FWIW google finance isn't deprecated.  Only google options and google quotes.

**Comment by bashtage** [comment]
@jreback I need some help setting up doctr to build the docs and host on gh-pages.  This is simpler than using RTD and also solves the issue of needed API keys which can be encrypted. I don't have admin so I can't complete the commands myself.

Also, who is the uploader to PyPi?

Would like to be able to release by early next week.

**Comment by bashtage** [comment]
@davidastephens so you manage the PyPI and RTD?  If so, will you be able to push a release after I tag it next week?

**Comment by jreback** [comment]
@bashtage I think @TomAugspurger or @jorisvandenbossche might be able to help with doctr

**Comment by davidastephens** [comment]
@bashtage Yes, I can push a release next week.  Thanks for cleaning it up.

**Comment by bashtage** [comment]
@TomAugspurger  and @jorisvandenbossche could you run `doctr configure` against master and submit a PR with the keyfile?  It will be much easier to build for gh-pages than using RTD when API keys. I can't figure out a method to store API keys on RTD.

**Comment by bashtage** [comment]
I'm ready to release 0.6.0, but need to get doctr setup beore doing this since docs are only pushed to gh-pages on tags.

**Comment by jorisvandenbossche** [comment]
@bashtage you don't have the rights to set up doctr?

**Comment by bashtage** [comment]
No.  I'm not an admin only have commit rights.

**Comment by bashtage** [comment]
Now fully ready to release, just need to get doctr sorted.

**Comment by davidastephens** [comment]
Ok, so still waiting for doctr?  Let me know when ready.

**Comment by bashtage** [comment]
Yes, it is ready.  Just need some help where someone runs 

```
doctr configure
```

and then follows the instructions to commit the key file. Do you have permissions on pydata?

**Comment by davidastephens** [comment]
I just tried this, I don't have permissions either.  @jorisvandenbossche  Do you have permissions?

**Comment by jorisvandenbossche** [comment]
According to the github team I am not more a maintainer (no other role) than you @bashtage and @davidastephens 
I think you have to ask @jreback (but I would also propose that @jreback adds both of you as maintainer in the pandas-datareader team, https://github.com/orgs/pydata/teams/pandas-datareader/members)

**Comment by bashtage** [comment]
I think it needs to be done with permission in pydata not just pandas data
reader.  Doctr pushes to gh-pages and so needs a ssh key

**Comment by bashtage** [comment]
I think anyone listed here

https://github.com/orgs/pydata/people?page=1

Who is an owner can complete the doctr configure ste.

**Comment by bashtage** [comment]
I got an email that indicates this is the case. Thanks.

**Comment by bashtage** [comment]
@davidastephens I tagged v0.6.0 so this should be ready for PyPI

**Comment by davidastephens** [comment]
@bashtage  Thanks - have pushed to PyPi.  
Do you have a PyPi username?  If so, I can add you as an owner.  

Thanks again for cleaning this all up.

**Comment by bashtage** [comment]
Thanks.  Also bashtage on PyPi.

**Comment by bashtage** [comment]
@jreback I was able to do what I needed to do to get doctr setup.  It might be a good idea to remove me as an owner now since I don't really need this permission.
