### ISSUE TITLE
BLS (Bureau of Labor Statistics)

### ISSUE THREAD

**Issue by westurner** [pydata/pandas-datareader#460]
https://www.bls.gov/developers/

https://www.bls.gov/developers/api_python.htm#python2

https://github.com/zewilson/bls/blob/master/data_loader.py

**Comment by bashtage** [comment]
Is there data here that isn't in FRED?

**Comment by westurner** [comment]
That's a good question. IDK if FRED has every BLS series or not?

https://fred.stlouisfed.org/sources

- US DOL BLS: https://fred.stlouisfed.org/source?soid=22

**Comment by esvhd** [comment]
On another note, does the BLS API provide first release data? i.e. without following revision?

**Comment by dtemkin** [comment]
I began working on this and I hit a "design" snag. Since, all of the series' are encoded, what is the best way to simulate the 'multi-screen search' feature? Or should this be avoided all together, thereby requiring pre-compiled series ids to be inputted by the user?

**Comment by bashtage** [comment]
Sounds like this is not a good fit for pdr.  If someone wants to submit a reader, please open a new issue.
