### ISSUE TITLE
Update Read The Docs for 0.6.0

### ISSUE THREAD

**Issue by addisonlynch** [pydata/pandas-datareader#482]
Datareader stable [Read the Docs](https://pandas-datareader.readthedocs.io/en/latest/) needs to be updated for RLS 0.6.0 (still at 0.5.0)

**Comment by bashtage** [comment]
The alternative is to kill RTD and to use github.io instead.  RTD doesn't seem to support encrypted API keys, which means that some of the docs can't be correctly generated.

**Comment by addisonlynch** [comment]
Yeah if not possible, might as well remove it. It is the "*second* stable implementation" anyway

**Comment by bashtage** [comment]
@jorisvandenbossche @davidastephens and @jreback are the owners of RTD.

**Comment by jreback** [comment]
@bashtage I added you to RTD!

**Comment by bashtage** [comment]
Built now.
