### ISSUE TITLE
How to pass Quandl api key?

### ISSUE THREAD

**Issue by francescodiorazio** [pydata/pandas-datareader#484]
Quandl's docs states:

import quandl
quandl.ApiConfig.api_key = "KEY"

But that doesn't work with pandas_datareader.data DataReader.

I dug into the script [data.py for pandas_datareader](https://github.com/pydata/pandas-datareader/blob/4a014c5d77e20ab3f945f409805fa7daed4720f9/pandas_datareader/data.py) and access_key only works for Enigma & Tiingo.

Please advise, thanks.

**Edit**:  I was thinking, if I can append the request URL with my API key it will work, pandas sends this URL:

https://www.quandl.com/api/v3/datasets/WIKI/TICKER_SYMBOL.csv

And the API key can be passed to quandl like so:

https://www.quandl.com/api/v3/datasets/WIKI/TICKER_SYMBOL.csv?&api_key=KEY

**Comment by bashtage** [comment]
This looks like a bug. It should look like the other api-keyed readers and accept this as an argument or use QUANDL_API_KEY

Do you want to write a PR?

**Comment by francescodiorazio** [comment]
I would, however in the last 2 hours I was not able to accomplish that, so I hard coded it in quandl.py:

```
        params = {
            'start_date': self.start.strftime('%Y-%m-%d'),
            'end_date': self.end.strftime('%Y-%m-%d'),
            'order': "asc",
            'api_key': "MY_KEY",
```

Before that I tried mimicking the enigma & tiingo readers api_key code for quandl.py, but I kept getting these errors:

TypeError: __init__() got an unexpected keyword argument 'api_key'
or
TypeError: DataReader() got an unexpected keyword argument 'api_key'

Even though I added it to data.py:

```
    elif data_source == "quandl":
        return QuandlReader(symbols=name, start=start, end=end,
                            retry_count=retry_count, pause=pause,
                            session=session, api_key=access_key).read()
```
So the only thing I can contribute here is the fact that a quandl api key does work with pandas datareader, but I hacked it by hard coding it (see above).
