### ISSUE TITLE
Morningstar queries to some tickers fail because the API returns no volumes

### ISSUE THREAD

**Issue by ggomarr** [pydata/pandas-datareader#486]
(I am a newbie at this, please guide me on how to contribute effectively)

Running
pandas_datareader.data.DataReader('HSI','morningstar',start=datetime.date(2012,12,22),end=datetime.date(2012,12,22))
fails because the Morningstar query for HSI does not return 'volumes' information.

This is the response directly from the API:
{"DividendData":[],"FairValueList":null,"Max":49000,"Min":9800,"PriceDataList":[{"DailyMaxNumPoint":-1,"Datapoints":[[29578.01,NaN,NaN,NaN]],"DateIndexs":[43089],"Description":"","Max":29578.01,"Min":29578.01,"Slot":3,"StartPos":29578.01,"Symbol":"XHKG:HSI","chartType":0}],"PriceType":"",**"VolumeList":null**}

I do not know how many tickers behave like this.

This specific case can be fixed by modifying pandas_datareader/mstar/daily.py as follows:
```
-        volumes = jsondata["VolumeList"]["Datapoints"]
+        try:
+            volumes = jsondata["VolumeList"]["Datapoints"]
+        except:
+            volumes = len(dateidx) * [ float('nan') ]

[...]

             if self.incl_vol is True:
-                bardict.update({"Volume": int(volumes[p] * 1000000)})
+                try:
+                    bardict.update({"Volume": int(volumes[p] * 1000000)})
+                except:
+                    bardict.update({"Volume": volumes[p]})
             else:
                 pass
```
There are other approaches - I do not know which one would be more aligned with the spirit of the module. Also, I have not investigated whether this change is safe in 100% of the use cases - it seems to be working fine for my project though.

Let me know if there is anything I can do to help!

**Comment by Bram-S** [comment]
Something similar happens for:
`pandas_datareader.data.DataReader('XAMS:ENX','morningstar',start=datetime.date(2012,12,22),end=datetime.date(2012,12,22))
`
