### ISSUE TITLE
ignore ssl verification switch?

### ISSUE THREAD

**Issue by kcompher** [pydata/pandas-datareader#493]
some of the data readers fail ssl verification on my network (``certificate verify fail``). Is there an ignore flag somewhere in pandas-datareader api that be used?

**Comment by AndreaPisoni** [comment]
I see this is tagged as 0.7, but you can already achieve this today easily through the session parameter on your API call. 

Try this:

```import requests
import pandas as pd
import pandas_datareader as web

start = datetime.datetime(2018, 1, 1)
end = datetime.datetime.now()

session = requests.Session()
session.verify = False #SSL verification will be turned OFF, requests will give you an InsecureRequestWarning

df = web.DataReader("TSLA", 'quandl', start, end, session=session)```

**Comment by bashtage** [comment]
This appears to be solved.  Please reopen if it is still an issue.
