### ISSUE TITLE
Release 0.7.0

### ISSUE THREAD

**Issue by bashtage** [pydata/pandas-datareader#495]
The recent re-addition of Yahoo! will trigger a new release in the next week.  I will try to get as many PRs in before then.

**Comment by paintdog** [comment]
Do you have an idea, when 0.7 will be released? Support of Yahoo Finance would be fine and a great help for some users...

**Comment by addisonlynch** [comment]
Status on this release, @bashtage?

**Comment by dtemkin** [comment]
@bashtage Please review my PR (#515) at your earliest convenience. I made many updates fixing broken test cases, google, stooq and morningstar api's.

**Comment by addisonlynch** [comment]
@bashtage this should probably be pushed soon due to the issues in #520. As of now PDR 0.6.0 is not functional and cannot be imported due to ``is_list_like`` compat.

**Comment by saggzz** [comment]
did you try pip install pandas==(older Version than yours, maybe 0.19.2) and run again

**Comment by Liam3851** [comment]
@bashtage Can you please release 0.7.0? pandas 0.23 has been out for months now and pandas-datareader is incompatible because #520 has not been released publicly.

**Comment by addisonlynch** [comment]
I believe the release is ready @bashtage. Is there anything else needed? I agree with the previous comments, we should push this ASAP unless there's anything we are waiting on.

**Comment by bashtage** [comment]
@davidastephens any thoughts about the changes to actions?

**Comment by bashtage** [comment]
Just cut 0.7, need @jorisvandenbossche or someone who has access to PyPI to upload a universal wheel.

**Comment by bashtage** [comment]
Now posted to pypi.  Thanks everyone, esp @addisonlynch. 

@davidastephens Would be helpful if you have some time to look at the actions adjustment.  I did it last night and it made sense to me but should be checked. It can be pretty inaccurate to reflate dividends after a split.

**Comment by jorisvandenbossche** [comment]
@bashtage FYI I don't have any PyPI access, only to readthedocs. But I suppose you have been added in the meantime?

**Comment by bashtage** [comment]
Thanks - I noticed that I was added for PyPI after pinging you.
