### ISSUE TITLE
Add Investopedia as a Data Source?

### ISSUE THREAD

**Issue by DennisStoller** [pydata/pandas-datareader#497]
Example URL, and note there is no API key required:

https://www.investopedia.com/markets/api/partial/historical/?Symbol=HMSF.L&Type=Historical+Prices&Timeframe=Daily&StartDate=Jan+10%2C+2018

This should return daily data for the following fields: Date, Open, High, Low, Adjusted Close, Volume

Importantly, this data set differs from Morningstar, IEX, et al because it provides Adjusted Close, which is adjusted for dividends and splits.  The others provide a Close price, with no adjustments.

Edit: while I am here ... thanks to all contributors for the pandas-datareader package!

**Comment by bashtage** [comment]
Sure, PR would be welcome.

**Comment by addisonlynch** [comment]
@DennisStoller the next release will include AlphaVantage which supports daily/weekly/monthly adjusted time series (see #490). It seems that Investopedia would be pretty trivial to implement as well, so I'll look into it. Having a hard time finding their docs for this, however.

**Comment by DennisStoller** [comment]
@addisonlynch thank you.  I've built a basic solution already using BeautifulSoup.  Initial testing shows some of the data to contain some errors.  I could not find documentation either.  I suspect they are using Reuters codes just like Yahoo was, and I have managed to work out some index codes too.  I have not yet succeeded with FX, and have not tried futures yet.  I'm happy to send you what I have, but the code is very amateur so I doubt it is of much value to you.  Another feature with this is that download time increases significantly with size of the time series requested.

At the moment I am working on cleaning data retrieved from it, rather than trying to make my code look like a grown-up wrote it.

**Comment by addisonlynch** [comment]
@DennisStoller ahh, for some reason I didn't realize this is HTML data. PDR generally tries to steer clear of any scraping (though will implement when needed). Will the AV data to be added provide what you're looking for? If so we can probably skip Investopedia, as no docs + scraping both raise reliability issues.

**Comment by DennisStoller** [comment]
@addisonlynch yes, I think the AlphaVantage solution should work, and it sounds like a much better fit with PDR.  Occasional data issues also present another argument against going with Investopedia.  Shall we close this Investopedia idea as inconsistent with the PDR approach?

**Comment by addisonlynch** [comment]
@DennisStoller yes..we can reopen if a public API becomes available. Thanks for looking into it!

**Comment by DennisStoller** [comment]
Closed as discussed above.
