### ISSUE TITLE
TST: also test with pandas master

### ISSUE THREAD

**Issue by jorisvandenbossche** [pydata/pandas-datareader#5]
There is now already a broad test range of pandas versions (0.10-0.15), but ideally, there should also be a test against pandas master.

**Comment by hayd** [comment]
I actually don't think this is too important, IMO this package is going to be pretty stable (and so not built enough for that to be a useful barometer/alarm). I think a better strategy will be to check that it's passing with latest pandas at rc time (when we can just add the rc release to travis).

*If the pandas devs build a package which gets completely broken on pandas updates what hope does the rest of the world have?? :p*

**Comment by davidastephens** [comment]
@hayd Looking to add the rc release to travis.  Doesn't seem to work - I'm getting:
```
Error: No packages found in current linux-64 channels matching: pandas 0.17.0rc1*
```
from Travis.  Is there a way to add the rc release to the travis build?  
https://github.com/davidastephens/pandas-datareader/commit/f9a944c76da7ea28cf2fe10cc7ea060b43a07dbc

https://travis-ci.org/davidastephens/pandas-datareader/jobs/81315264

**Comment by hayd** [comment]
You may need to use a special channel to conda install it? I think I remember @jreback  saying something like that on the ML...

**Comment by jreback** [comment]
add

conda config --add channels pandas

thrn

conda install pandas 

gets the latest 

u can also do

conda install pandas -c pandas

**Comment by hayd** [comment]
Thanks! Hopefully this builds: https://travis-ci.org/pydata/pandas-datareader/builds/81331703 #90 :)

**Comment by davidastephens** [comment]
Got it to work.   Had to add a "v" in front of the version.  

Had to make one change to make it build: adding the stack level on the Option deprecation warning. 
https://travis-ci.org/davidastephens/pandas-datareader/jobs/81332942 #91
