### ISSUE TITLE
ENH: Morningstar Financial Statements

### ISSUE THREAD

**Issue by dtemkin** [pydata/pandas-datareader#516]
I tried to incorporate this within the last release but it was a little too buggy. 

The urls can be found here - https://gist.github.com/hahnicity/45323026693cdde6a116 .

As an addendum:
 'columnYear' controls the number of "periods" returned (accepts value 5 or 10)
 'dataType' is either ['A' or 'Q'] and controls if it is an annual or quarterly report. (also if 'dataType'='A', the api will return, at most, 5 columns.)

**Comment by addisonlynch** [comment]
From the first line of that gist:

> If you're interested in grabbing Morningstar data but cash strapped **there are ways to do it without actually paying for it**.

Something tells me a workaround for Morningstar's paywall on these items wouldn't be a good idea for PDR, but alas I am new here and am not completely sure.

I'll look into it!

**Comment by bashtage** [comment]
As of v0.7.0 Google finance and Morningstar have been immediately deprecated due to large changes in their API and no stable replacement.
