### ISSUE TITLE
QUANDL: URL format need to be updated.

### ISSUE THREAD

**Issue by vison5631** [pydata/pandas-datareader#521]
Hi

Located in quandl.py line 86:
`url = '{url}{dataset}/{symbol}.csv?{params}'`
This line should be changed to:
`url = '{url}{dataset}/{symbol}/data.csv?{params}'`

Otherwise you will get error from quandl:
Response Text:
b'code,message\nQECx02,You have submitted an incorrect Quandl code. Please check your Quandl codes and try again.\n'

**Comment by addisonlynch** [comment]
Can you provide a brief snippet that demonstrates a request which throws this error? It does seem per their docs that the 2nd example you've provided from above is indeed the correct one, but the example in  the PDR docs:

```python
df = web.DataReader('WIKI/AAPL', 'quandl', '2015-01-01', '2015-01-05')
```
which calls https://www.quandl.com/api/v3/datasets/WIKI/AAPL.json?api_key= works for me nonetheless.

**Comment by gliptak** [comment]
Reading https://docs.quandl.com/docs/in-depth-usage

this works https://www.quandl.com/api/v3/datasets/WIKI/FB.csv?start_date=2017-01-01&end_date=2017-12-31&api_key=kkkkkkkk
this works too https://www.quandl.com/api/v3/datasets/WIKI/FB/data.csv?start_date=2017-01-01&end_date=2017-12-31&api_key=kkkkkkkk

Something wrong with SPY

this doesn't work https://www.quandl.com/api/v3/datasets/WIKI/SPY.csv?start_date=2017-01-01&end_date=2017-12-31&api_key=kkkkkkkk
nor this https://www.quandl.com/api/v3/datasets/WIKI/SPY/data.csv?start_date=2017-01-01&end_date=2017-12-31&api_key=kkkkkkkk

I added the failing testcase https://github.com/pydata/pandas-datareader/pull/531

https://github.com/pydata/pandas-datareader/issues/532

**Comment by gliptak** [comment]
From Quandl Support:

To see a list of all tickers covered in the free WIKI database, please download this list with your API key: 
https://www.quandl.com/api/v3/databases/WIKI/codes?api_key=YOURAPIKEY

We currently don't have a free resource for SPY data.

I closed https://github.com/pydata/pandas-datareader/pull/531 and maybe this issue is to be closed too.

**Comment by bashtage** [comment]
This seems to be fixed in master.  Please reopen if it is an issue.
