### ISSUE TITLE
Financial Data for Morningstar Recursion Error

### ISSUE THREAD

**Issue by vmocco** [pydata/pandas-datareader#523]
There is a problem in the recursion of the MorningStarDailyReader in this function: _dl_mult_symbols

Could you make a change similar to this one:

    def _dl_mult_symbols(self, symbols,retryattempt=False):
        failed = []
        symbol_data = []
        for symbol in symbols:

            params = self._url_params()
            params.update({"ticker": symbol})

            try:
                resp = requests.get(self.url, params=params)
            except Exception:
                if symbol not in failed:
                    if self.retry_count == 0:
                        warn("skipping symbol %s: number of retries "
                             "exceeded." % symbol)
                        pass
                    else:
                        print("adding %s to retry list" % symbol)
                        failed.append(symbol)
            else:
                if resp.status_code == requests.codes.ok:
                    jsondata = resp.json()
                    if jsondata is None:
                        failed.append(symbol)
                        continue
                    jsdata = self._restruct_json(symbol=symbol,
                                                 jsondata=jsondata)
                    symbol_data.extend(jsdata)
                else:
                    raise Exception("Request Error!: %s : %s" % (
                        resp.status_code, resp.reason))

            time.sleep(self.pause)

        if len(failed) > 0 and self.retry_count > 0:
            # TODO: This appears to do nothing since
            # TODO: successful symbols are not added to
            self.retry_count -= 1
            failed_symbol_data = self._dl_mult_symbols(symbols=failed,retryattempt=True)
            if failed_symbol_data:
                symbol_data.extend(failed_symbol_data)
        else:
            self.retry_count = 0

        if not symbol_data:
            #raise ValueError('All symbols were invalid')
            warn('{} was unable to be found'.format(failed))
        elif self.retry_count == 0 and len(failed) > 0:
            warn("The following symbols were excluded do to http "
                 "request errors: \n %s" % failed, SymbolWarning)

        if retryattempt:
            return symbol_data
        else:
            symbols_df = DataFrame(data=symbol_data)
            dfx = symbols_df.set_index(["Symbol", "Date"])
            return dfx

**Comment by bashtage** [comment]
As of v0.7.0 Google finance and Morningstar have been been immediately deprecated due to large changes in their API and no stable replacement.
