### ISSUE TITLE
pandas_datareader import error from docker build

### ISSUE THREAD

**Issue by TyrelCB** [pydata/pandas-datareader#527]
Traceback (most recent call last):
  File "app.py", line 4, in <module>
    import some_custom_app as custom
  File "/app/some_custom_app.py", line 11, in <module>
    from pandas_datareader import data as web
  File "/usr/local/lib/python3.6/site-packages/pandas_datareader/__init__.py", line 2, in <module>
    from .data import (DataReader, Options, get_components_yahoo,
  File "/usr/local/lib/python3.6/site-packages/pandas_datareader/data.py", line 14, in <module>
    ***from pandas_datareader.fred import FredReader***
  File "/usr/local/lib/python3.6/site-packages/pandas_datareader/***fred.py***", line 1, in <module>
    from pandas.core.common import is_list_like
***ImportError: cannot import name 'is_list_like'***

**Comment by addisonlynch** [comment]
This was repaired in #520 and will be implemented in the 0.7.0 release. For now, I would recommend downloading the dev repo from here.

**Comment by TyrelCB** [comment]
In case anyone else has this problem I just had to change my requirements file. 
### From:
pandas_datareader
### To:
-e git+https://github.com/pydata/pandas-datareader.git@master#egg=MyProject

Thanks addisonlynch

**Comment by vlad-bezden** [comment]
It's fixed in latest version, use following command to get latest:

pip install git+https://github.com/pydata/pandas-datareader.git

here is an url with more instructions:
https://pandas-datareader.readthedocs.io/en/latest/#install-latest-development-version

**Comment by KabiruAbdulhamid** [comment]
Thanks @vlad-bezden it solves my problem

**Comment by saeedesmaili** [comment]
@vlad-bezden This command installs the 0.6.0+32.gf371300 version. How can I install the 0.7 version?

pip install git+https://github.com/pydata/pandas-datareader.git

**Comment by bashtage** [comment]
That is the latest.  0.7 is not released - it is 0.6+32 new commits.
