### ISSUE TITLE
Quandl API key in Travis?

### ISSUE THREAD

**Issue by gliptak** [pydata/pandas-datareader#532]
Could a Quandl API key be added to Travis? Currently Quandl tests are skipped:

https://travis-ci.org/pydata/pandas-datareader/jobs/384958923

pandas_datareader/tests/test_quandl.py sssssssss

Thanks

**Comment by bashtage** [comment]
There is a key. These are not available for PRs to prevent them from being
disclosed.

**Comment by gliptak** [comment]
@bashtage Thanks for the clarification.

**Comment by rsvp** [comment]
## FYI: If the test was NOT skipped...

And no key is present, here's what generally happens at  `pytest`:

```
E   ErrorDownloading: Error Downloading! HTTP Error 429: Too Many Requests
 !!!!!!!!!!!!!!!!!!! Interrupted: 2 errors during collection !!!!!!!!!!!!!!!!!!!!
 ==================== 1 deselected, 2 error in 3.26 seconds =====================
 The command "pytest -s -r xX --doctest-modules -k 'not oLocal' tests" exited with 2. 

 Quandl Error Code       HTTP Status Code        Description
 QELx01  429     You have exceeded your daily call limit as an anonymous user.
 QELx02  429     You have exceeded your daily call limit as a registered user.
 QELx03  429     You have exceeded your daily call limit as a subscriber.
 QELx04  429     You have exceeded your 10-minute call limit as a registered user.
 QELx05  429     You have exceeded your 10-minute call limit as a subscriber.
```

It seems all public Travis users are one anonymous user from Quandl's POV.
Is there a rate limit or speed limit for API usage?
 
> Anonymous users have a limit of 20 calls per 10 minutes and 50 calls per day. Authenticated users have a limit of 300 calls per 10 seconds, 2,000 calls per 10 minutes and a limit of 50,000 calls per day. Authenticated users of free databases have a concurrency limit of one; that is, they can make one call at a time and have an additional  call in the queue. Premium data subscribers have a limit of 5,000 calls per 10 minutes and a limit of 720,000 calls per day. Premium data subscribers are limited to 10 bulk downloads per hour. Last updated on May 17, 2018 
 
I think marking such tests as e.g. oLocal ("only Local" with key present) 
skips the avalanche of XFAIL reports.

**Comment by bashtage** [comment]
If you are running on your own branch in your own Travis account you can store a api key in Travis.
