### ISSUE TITLE
KeyError: 'Adj Close'  During handling of the above exception, another exception occurred:

### ISSUE THREAD

**Issue by yuanyuning** [pydata/pandas-datareader#533]
I don't know hwo to deal with this error.

`import pandas as pd
from pandas_datareader import data as pdr
import fix_yahoo_finance as yf
symbols=['^GDAXI','^GSPC','YHOO','MSFT']
data=pd.DataFrame()
for sym in symbols:   
    data[sym]=pdr.get_data_yahoo(sym,start='2006-1-1')['Adj Close']
data=data.dropna()`

KeyError                                  Traceback (most recent call last)
E:\anaconda\lib\site-packages\pandas\core\indexes\base.py in get_loc(self, key, method, tolerance)
   2524             try:
-> 2525                 return self._engine.get_loc(key)
   2526             except KeyError:

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

KeyError: 'Adj Close'

During handling of the above exception, another exception occurred:

KeyError                                  Traceback (most recent call last)
<ipython-input-43-e5314ad8cf11> in <module>()
      1 data=pd.DataFrame()
      2 for sym in symbols:
----> 3     data[sym]=pdr.get_data_yahoo(sym,start='2006-1-1')['Adj Close']

E:\anaconda\lib\site-packages\pandas\core\frame.py in __getitem__(self, key)
   2137             return self._getitem_multilevel(key)
   2138         else:
-> 2139             return self._getitem_column(key)
   2140 
   2141     def _getitem_column(self, key):

E:\anaconda\lib\site-packages\pandas\core\frame.py in _getitem_column(self, key)
   2144         # get column
   2145         if self.columns.is_unique:
-> 2146             return self._get_item_cache(key)
   2147 
   2148         # duplicate columns & possible reduce dimensionality

E:\anaconda\lib\site-packages\pandas\core\generic.py in _get_item_cache(self, item)
   1840         res = cache.get(item)
   1841         if res is None:
-> 1842             values = self._data.get(item)
   1843             res = self._box_item_values(item, values)
   1844             cache[item] = res

E:\anaconda\lib\site-packages\pandas\core\internals.py in get(self, item, fastpath)
   3841 
   3842             if not isna(item):
-> 3843                 loc = self.items.get_loc(item)
   3844             else:
   3845                 indexer = np.arange(len(self.items))[isna(self.items)]

E:\anaconda\lib\site-packages\pandas\core\indexes\base.py in get_loc(self, key, method, tolerance)
   2525                 return self._engine.get_loc(key)
   2526             except KeyError:
-> 2527                 return self._engine.get_loc(self._maybe_cast_indexer(key))
   2528 
   2529         indexer = self.get_indexer([key], method=method, tolerance=tolerance)

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.PyObjectHashTable.get_item()

KeyError: 'Adj Close'

**Comment by rubik** [comment]
I have experienced the same issues. The weird thing is that on my laptop I usually run it again and it works, but on a remote server I have it *never* works...

**Comment by bashtage** [comment]
There is a lot of filtering to avoid automated scraping from these endpoints.  There is nothing we can do about this.
