### ISSUE TITLE
Unable to read data from quandl

### ISSUE THREAD

**Issue by yt-feng** [pydata/pandas-datareader#535]
import pandas_datareader.data as web
symbol = 'GOOG','AAPL'
df = web.DataReader(symbol,'quandl','2015-01-01','2015-03-05')  #yahoo
df

`ValueError                                Traceback (most recent call last)
<ipython-input-31-392eb3f84a19> in <module>()
      1 import pandas_datareader.data as web
      2 symbol = 'GOOG','AAPL'
----> 3 df = web.DataReader(symbol,'quandl','2015-01-01','2015-03-05')  #yahoo
      4 df

C:\ProgramData\Anaconda3\envs\py2\lib\site-packages\pandas_datareader\data.pyc in DataReader(name, data_source, start, end, retry_count, pause, session, access_key)
    384         return QuandlReader(symbols=name, start=start, end=end,
    385                             retry_count=retry_count, pause=pause,
--> 386                             session=session, api_key=access_key).read()
    387     elif data_source == "moex":
    388         return MoexReader(symbols=name, start=start, end=end,

C:\ProgramData\Anaconda3\envs\py2\lib\site-packages\pandas_datareader\quandl.pyc in __init__(self, symbols, start, end, retry_count, pause, session, chunksize, api_key)
     52             api_key = os.getenv('QUANDL_API_KEY')
     53         if not api_key or not isinstance(api_key, str):
---> 54             raise ValueError('The Quandl API key must be provided either '
     55                              'through the api_key variable or through the '
     56                              'environmental variable QUANDL_API_KEY.')

ValueError: The Quandl API key must be provided either through the api_key variable or through the environmental variable QUANDL_API_KEY.
`

It works well with yahoo, however not with google and quandl

Version - dev

Note: I used the dev version because of an import error for 0.6.0

Thank you.

**Comment by addisonlynch** [comment]
In order to retrieve data from quandl, you need to register for and input (via the parameter api_key or the environment variable QUANDL_API_KEY) a Quandl API key. Registering for a key can be done [here](https://docs.quandl.com/docs#section-authentication).

**Comment by addisonlynch** [comment]
@yt-feng please close this issue if all problems have been resolved. Thanks!
