### ISSUE TITLE
Fama french data library url not working anymore

### ISSUE THREAD

**Issue by sivananth** [pydata/pandas-datareader#54]
Hi, I use your library extensively, and it seems the Fama french option doesnt work anymore -

![image](https://cloud.githubusercontent.com/assets/9622083/8870382/22c89a06-320b-11e5-9919-d803262ca726.png)

I tried tracing the error - perhaps the url has changed (or denied access) - 

http://mba.tuck.dartmouth.edu/pages/faculty/ken.french/ftp/

Is there a way you could fix this? Thanks in advance.

**Comment by sinhrks** [comment]
Thanks for the report! This was fixed in #53. 

Please update, otherwise specifying ` `web.DataReader("5_Industry_Portfolios_TXT", "famafrench")`` can be a temp workaround.
