### ISSUE TITLE
Import pandas-datereader mistake

### ISSUE THREAD

**Issue by AntonGridushko** [pydata/pandas-datareader#546]
Hello eo!
I have mistake occured importing pandas_datereader

Could ao help me?

ImportError                               Traceback (most recent call last)
<ipython-input-12-75f869254055> in <module>()
----> 1 from pandas_datareader import data

c:\users\anton\appdata\local\programs\python\python36-32\lib\site-packages\pandas_datareader\__init__.py in <module>()
      1 from ._version import get_versions
----> 2 from .data import (DataReader, Options, get_components_yahoo,
      3                    get_dailysummary_iex, get_data_enigma, get_data_famafrench,
      4                    get_data_fred, get_data_google, get_data_moex,
      5                    get_data_morningstar, get_data_quandl, get_data_stooq,

c:\users\anton\appdata\local\programs\python\python36-32\lib\site-packages\pandas_datareader\data.py in <module>()
     12     ImmediateDeprecationError
     13 from pandas_datareader.famafrench import FamaFrenchReader
---> 14 from pandas_datareader.fred import FredReader
     15 from pandas_datareader.google.daily import GoogleDailyReader
     16 from pandas_datareader.google.options import Options as GoogleOptions

c:\users\anton\appdata\local\programs\python\python36-32\lib\site-packages\pandas_datareader\fred.py in <module>()
----> 1 from pandas.core.common import is_list_like
      2 from pandas import concat, read_csv
      3 
      4 from pandas_datareader.base import _BaseReader
      5 

ImportError: cannot import name 'is_list_like'

**Comment by addisonlynch** [comment]
This was fixed in #520 and will be a part of the next release (0.7.0). For now, I would recommend using the dev version (master branch of this repo - pip install git+https://github.com/pydata/pandas-datareader)
