### ISSUE TITLE
Unable to get data from google.

### ISSUE THREAD

**Issue by Vikas125** [pydata/pandas-datareader#547]
Df= web.DataReader('SPY', data_source='google')
Df=Df[['Open','High','Low','Close']]
/Users/vikas/anaconda3/lib/python3.6/site-packages/pandas_datareader/google/daily.py:40: UnstableAPIWarning: 
The Google Finance API has not been stable since late 2017. Requests seem
to fail at random. Failure is especially common when bulk downloading.

  warnings.warn(UNSTABLE_WARNING, UnstableAPIWarning)
Traceback (most recent call last):

  File "<ipython-input-2-329433d59ce6>", line 1, in <module>
    Df= web.DataReader('SPY', data_source='google')

  File "/Users/vikas/anaconda3/lib/python3.6/site-packages/pandas_datareader/data.py", line 315, in DataReader
    session=session).read()

  File "/Users/vikas/anaconda3/lib/python3.6/site-packages/pandas_datareader/base.py", line 206, in read
    params=self._get_params(self.symbols))

  File "/Users/vikas/anaconda3/lib/python3.6/site-packages/pandas_datareader/base.py", line 84, in _read_one_data
    out = self._read_url_as_StringIO(url, params=params)

  File "/Users/vikas/anaconda3/lib/python3.6/site-packages/pandas_datareader/base.py", line 95, in _read_url_as_StringIO
    response = self._get_response(url, params=params)

  File "/Users/vikas/anaconda3/lib/python3.6/site-packages/pandas_datareader/base.py", line 155, in _get_response
    raise RemoteDataError(msg)

RemoteDataError: Unable to read URL: https://finance.google.com/finance/historical?q=SPY&startdate=Jan+01%2C+2010&enddate=Jun+23%2C+2018&output=csv
Response Text:
b'<html><head><meta http-equiv="content-type" content="text/html; charset=utf-8"/><title>Sorry...</title><style> body { font-family: verdana, arial, sans-serif; background-color: #fff; color: #000; }</style></head><body><div><table><tr><td><b><font face=sans-serif size=10><font color=#4285f4>G</font><font color=#ea4335>o</font><font color=#fbbc05>o</font><font color=#4285f4>g</font><font color=#34a853>l</font><font color=#ea4335>e</font></font></b></td><td style="text-align: left; vertical-align: bottom; padding-bottom: 15px; width: 50%"><div style="border-bottom: 1px solid #dfdfdf;">Sorry...</div></td></tr></table></div><div style="margin-left: 4em;"><h1>We\'re sorry...</h1><p>... but your computer or network may be sending automated queries. To protect our users, we can\'t process your request right now.</p></div><div style="margin-left: 4em;">See <a href="https://support.google.com/websearch/answer/86640">Google Help</a> for more information.<br/><br/></div><div style="text-align: center; border-top: 1px solid #dfdfdf;"><a href="https://www.google.com">Google Home</a></div></body></html>'

**Comment by rishabh-vij** [comment]
You can use yahoo finance API instead. You'll need to get it first by pip install fix-yahoo-finance.
ex.py:
`#imports
#imports

import pandas as pd
pd.core.common.is_list_like = pd.api.types.is_list_like
from pandas_datareader import data, wb
import fix_yahoo_finance as yf
yf.pdr_override()
import numpy as np
import datetime

#To get data:

start = datetime.datetime(2006, 1, 1)
end = datetime.datetime(2016, 1, 1)
df = data.get_data_yahoo('MS', start, end)

**Comment by Patil-Sahil** [comment]
Tried installing fix-yahoo by  by pip install fix-yahoo-finance but it says - 

Could not find a version that satisfies the requirement fix -yahoo ( from versions: )
No matching distribution found for fix-yahoo

**Comment by arunj59** [comment]
**Yahoo Actions has been immediately deprecated!**
What else can be used?

Error
ImmediateDeprecationError                 Traceback (most recent call last)
<ipython-input-3-b4377ab16ca7> in <module>()
      2 end = datetime.datetime(2006, 1, 30)
      3 
----> 4 BAC = data.get_data_yahoo('BAC', start, end)

~\Anaconda3\lib\site-packages\pandas_datareader\data.py in get_data_yahoo(*args, **kwargs)
     61 
     62 def get_data_yahoo(*args, **kwargs):
---> 63     raise ImmediateDeprecationError(DEP_ERROR_MSG.format('Yahoo Actions'))
     64     return YahooDailyReader(*args, **kwargs).read()
     65 

ImmediateDeprecationError: 
Yahoo Actions has been immediately deprecated due to large breaks in the API without the
introduction of a stable replacement. Pull Requests to re-enable these data
connectors are welcome.

See https://github.com/pydata/pandas-datareader/issues

**Comment by addisonlynch** [comment]
@arunj59 try morningstar or quandl.

**Comment by bashtage** [comment]
As of v0.7.0 Google finance and Morningstar have been been immediately deprecated due to large changes in their API and no stable replacement.
