### ISSUE TITLE
questions : unable to install pandas-datareader

### ISSUE THREAD

**Issue by yoonsong** [pydata/pandas-datareader#548]
Requirement already satisfied: pandas_datareader in c:\users\anaconda3\lib\site-packages (0.6.0)
Requirement already satisfied: pandas>=0.19.2 in c:\users\anaconda3\lib\site-packages (from pandas_datareader) (0.23.0)
Requirement already satisfied: requests>=2.3.0 in c:\users\anaconda3\lib\site-packages (from pandas_datareader) (2.18.4)
Requirement already satisfied: requests-file in c:\users\anaconda3\lib\site-packages (from pandas_datareader) (1.4.3)
Requirement already satisfied: requests-ftp in c:\users\anaconda3\lib\site-packages (from pandas_datareader) (0.3.1)
Requirement already satisfied: wrapt in c:\users\anaconda3\lib\site-packages (from pandas_datareader) (1.10.11)
Requirement already satisfied: lxml in c:\users\anaconda3\lib\site-packages (from pandas_datareader) (4.2.1)
Requirement already satisfied: pytz>=2011k in c:\users\anaconda3\lib\site-packages (from pandas>=0.19.2->pandas_datareader) (2018.4)
Requirement already satisfied: python-dateutil>=2.5.0 in c:\users\anaconda3\lib\site-packages (from pandas>=0.19.2->pandas_datareader) (2.7.3)
Requirement already satisfied: numpy>=1.9.0 in c:\users\anaconda3\lib\site-packages (from pandas>=0.19.2->pandas_datareader) (1.14.3)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\users\anaconda3\lib\site-packages (from requests>=2.3.0->pandas_datareader) (3.0.4)
Requirement already satisfied: idna<2.7,>=2.5 in c:\users\anaconda3\lib\site-packages (from requests>=2.3.0->pandas_datareader) (2.6)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in c:\users\anaconda3\lib\site-packages (from requests>=2.3.0->pandas_datareader) (1.22)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\anaconda3\lib\site-packages (from requests>=2.3.0->pandas_datareader) (2018.4.16)
Requirement already satisfied: six in c:\users\anaconda3\lib\site-packages (from requests-file->pandas_datareader) (1.11.0)

mine shows this, and there was no "successful install"
can anybody help me what's happening;_;

**Comment by bashtage** [comment]
You need to install from git, not pip. The latest pip is 0.6, which is why it is satisfied.
