### ISSUE TITLE
Yahoo Daily depricated?

### ISSUE THREAD

**Issue by waswaswas10** [pydata/pandas-datareader#549]
Traceback (most recent call last):
  File "C:\Users\Samue\Desktop\Python\IDLE\Projects\Practice1.py", line 13, in <module>
    df = web.DataReader ('TSLA' ,'yahoo', start, end)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\pandas_datareader\data.py", line 291, in DataReader
    raise ImmediateDeprecationError(DEP_ERROR_MSG.format('Yahoo Daily'))
pandas_datareader.exceptions.ImmediateDeprecationError: 
Yahoo Daily has been immediately deprecated due to large breaks in the API without the
introduction of a stable replacement. Pull Requests to re-enable these data
connectors are welcome.

**Comment by leafmouse** [comment]
Hi,
I also met this problem, the following description for your information.

Yahoo! Finance has been immediately deprecated. Yahoo! substantially altered their API in late 2017 and the csv endpoint was retired.

Reference:
http://pandas-datareader.readthedocs.io/en/latest/remote_data.html

**Comment by addisonlynch** [comment]
Parts of Yahoo Finance (including the daily reader) were reinstated in #525. I would recommend downloading the latest development version, as described [here](https://github.com/pydata/pandas-datareader#install-latest-development-version).

**Comment by naitikbhise** [comment]
@addisonlynch I tried the new git version download and instal. Still, the problem persists as I can't access the TSLA data. What should I do next?

**Comment by Jaseibert** [comment]
Hey @addisonlynch the latest release which you linked still throws an immediate deprecation error when implemented. @naitikbhise What is the specific use case where the "Yahoo Daily" API is needed as opposed to other Financial/Stock Tick API's provided like Robinhood, or Morningstar?

**[Robinhood API Docs](https://pandas-datareader.readthedocs.io/en/latest/remote_data.html#remote-data-robinhood)**

import pandas_datareader.data as web

#Define your Start and End Dates
start = dt.datetime(2017,8,15)
end = dt.datetime(2018,8,15)

#Make your call to the Robinhood API
df = web.DataReader('TSLA', 'robinhood', start, end)
df.head() 

OR

**[Morningstar API Docs](https://pandas-datareader.readthedocs.io/en/latest/remote_data.html#remote-data-morningstar)**

import pandas_datareader.data as web

#Define your Start and End Dates
start = dt.datetime(2013,8,15)
end = dt.datetime(2018,8,15)

#Make your call to the MorningStar API
df = web.DataReader('TSLA', 'morningstar', start, end)
df.head()

**Comment by MohamedSalahLFC** [comment]
@addisonlynch 
@naitikbhise 
@leafmouse 

Neither Morningstar(only for small datas)  nor Robinhood worked for me.
If your still stuck try 'quandl' as a datasource , it should worked perfectly !!

**Comment by Joydeep75** [comment]
Robinhood API worked for me, as mentioned above. But I have used it, little differently as follows, 

prices = data.get_data_robinhood(['CVX','XOM','BP'], 
                             start = dt.datetime(2015,1,1),
                             end = dt.datetime(2018,1,1))
prices.head()

**Comment by bashtage** [comment]
Yahoo is back in the latest release (0.7.0)
