### ISSUE TITLE
[ENH] Fama/French

### ISSUE THREAD

**Issue by 0x0L** [pydata/pandas-datareader#55]
pandas crashes when trying to read some files from Fama-French whose format is a bit different:
```python
pd.io.data.get_data_famafrench("Portfolios_Formed_on_ME")

---------------------------------------------------------------------------
...
IndexError: index -1 is out of bounds for axis 0 with size 0
```

PR https://github.com/pydata/pandas-datareader/pull/56

**Comment by jorisvandenbossche** [comment]
@0x0L Can you report this to https://github.com/pydata/pandas-datareader/issues (the new home for this functionality)?

**Comment by jorisvandenbossche** [comment]
whoops, this is here :-) (blaming mixed notifications!)

**Comment by 0x0L** [comment]
PR https://github.com/pydata/pandas-datareader/pull/56
