### ISSUE TITLE
Google Finance

### ISSUE THREAD

**Issue by vnmabus** [pydata/pandas-datareader#551]
As far as I understand, the Google Finance API is currently not supported. However, it seems that other projects such as
https://github.com/pdevty/googlefinance-client-python

are obtaining historical data from Google using the following URL:
https://finance.google.com/finance/getprices

Is there a reason why we can not do the same?

**Comment by rsvp** [comment]
hi @vnmabus The last URL leads to a blank page.
Is it just a stem for something intended to be more specific?

**Comment by vnmabus** [comment]
I think you are supposed to pass query parameters in order to download the data, as it is done in the mentioned project, using the requests module. I have tried doing that and it worked.

**Comment by stoffprof** [comment]
I started writing some code and should have a PR later today.

**Comment by stoffprof** [comment]
This URL doesn't seem to work any longer. Is there some data that Google provided that isn't in Yahoo or another source already? We can add some other source if needed.

**Comment by amitbhsingh** [comment]
****
I replaced yahoo with google and bam it worked 
![screen shot 2018-09-07 at 12 13 00 pm](https://user-images.githubusercontent.com/22262662/45230608-5c1cd780-b297-11e8-97a0-4cebb34e6c22.png)

BAC=data.DataReader('BAC','yahoo',start,end)

****

**Comment by bashtage** [comment]
As of v0.7.0 Google finance and Morningstar have been immediately deprecated due to large changes in their API and no stable replacement.
