### ISSUE TITLE
NotImplementedError: data_source=None is not implemented

### ISSUE THREAD

**Issue by jimibengbeng** [pydata/pandas-datareader#567]
import datetime as dt
import matplotlib.pyplot as plt
from matplotlib import style
import pandas as pd
import pandas_datareader.data as web
style.use("ggplot")
start = dt.datetime(2015,1,1)
end  = dt.datetime(2016,12,31)
df = web.DataReader('TSLA')

NotImplementedError                       Traceback (most recent call last)
<ipython-input-18-2f2b5751887d> in <module>()
----> 1 df = web.DataReader('TSLA')

/anaconda3/lib/python3.6/site-packages/pandas_datareader/data.py in DataReader(name, data_source, start, end, retry_count, pause, session, access_key)
    401     else:
    402         msg = "data_source=%r is not implemented" % data_source
--> 403         raise NotImplementedError(msg)
    404 
    405 

NotImplementedError: data_source=None is not implemented

**Comment by jimibengbeng** [comment]
pandas_datareader installed by pip version 0.6

**Comment by bashtage** [comment]
You need to provide the string name of the data source.
