### ISSUE TITLE
pandas.io.wb.download returned DataFrame does not contain iso_code

### ISSUE THREAD

**Issue by yaph** [pydata/pandas-datareader#57]
The [docstring of this method](https://github.com/pydata/pandas-datareader/blob/master/pandas_datareader/wb.py#L112) states that the DataFrame contains the iso_code, which is not the case. The column is [dropped](https://github.com/pydata/pandas-datareader/blob/master/pandas_datareader/wb.py#L159) from the DataFrame before it is returned.

I commented out the above line, but then most values for iso_code are NAN, because of the call to [convert_objects](https://github.com/pydata/pandas-datareader/blob/master/pandas_datareader/wb.py#L166). I think it would be useful to include the iso_code in the result, but if the conversion is to be kept, it would need to become part of the index.

Not sure, what would be the best solution here. In case the current behaviour is to be kept, the docstring should be corrected.

I previously reported this here: https://github.com/pydata/pandas/issues/10860

**Comment by hayd** [comment]
There's also a warning for this line: https://github.com/pydata/pandas-datareader/blob/402cd7f247a20d8518ad1359ef99f1eaddd49dcf/pandas_datareader/wb.py#L157.

Can we just remove the line which drops this column? (or hide it behind a kwarg e.g. `drop_iso_code`.)
