### ISSUE TITLE
local ssl certificate verification

### ISSUE THREAD

**Issue by AndreaPisoni** [pydata/pandas-datareader#570]
It would be good to be able to point to local SSL certificates. The more generic requests library allows to do that through the verify parameter. If datareader is based on requests (haven't looked at the code yet, being honest here), then it should be quite straightforward.

**Comment by AndreaPisoni** [comment]
Never mind, I should have thought about this for more than a minute and maybe looked at the code. You can already achieve this through the request session.

`import requests
import pandas as pd
import pandas_datareader as web

start = datetime.datetime(2018, 1, 1)
end = datetime.datetime.now()

session = requests.Session()
session.verify = #path to your local SSL cert

df = web.DataReader("TSLA", 'quandl', start, end, session=session)
`

Should work like a charm

**Comment by bashtage** [comment]
Closing as solved.  Reopen if you think this is still an issue.
