### ISSUE TITLE
TST: Add cron job to Travis CI

### ISSUE THREAD

**Issue by addisonlynch** [pydata/pandas-datareader#571]
Given that Pandas Datareader heavily relies on a number of external data sources, it may be useful to add a daily or weekly cron job to Travis CI. This would enable more efficient discovery of broken/altered endpoints and help catch those which are not raised in issues.

Since many endpoints are often changing, contributors often discover and repair bugs as extra commits to their PRs that outside of their PR's originally-intended scope. Further, these commits are often squashed and documentation of them is sometimes harder to find. A cron job would make the process of identifying and repairing the bugs both less convoluted and better-documented, preventing confusion from the perspective of both entry-level contributors and the project's maintainers.

**Comment by bashtage** [comment]
Done:

![image](https://user-images.githubusercontent.com/5585221/45410335-55141180-b669-11e8-841b-fb440f473e30.png)
