### ISSUE TITLE
Stooq: 1) Data before April 2010 is not shown 2) start / end does not work

### ISSUE THREAD

**Issue by nospam999** [pydata/pandas-datareader#578]
I have two problems with version 0.7.0 and Data from Stooq:

1) Data before April 2010 ist not shown (works in version 0.6.0)
2) start and end does not work (same problem in version 0.6.0)

Here is the code:
`import pandas as pd
import pandas_datareader.data as web
symbol ='AAPL.US'
start = '20000101'
end   = '20180901'
df = web.DataReader(symbol, 'stooq', start, end)
print(df)`

**Comment by KageYoshi777** [comment]
I've got the same problem with stooq. start end end date doesn't work.

**Comment by vcheng728** [comment]
start = datetime.datetime(2019, 1, 1)
end = datetime.datetime.now()
df = web.DataReader("TSLA", 'stooq', start, end)

also does not work for me, goes to default range of 2010 to today

**Comment by partopronto** [comment]
I have tested and verified the bug fix:

_start_ and _end_ are **not set** to the parent:

File: pandas_datareader/**data.py** Line 433
`      start=start,`
`      end=end,`

    elif data_source == "stooq":
        return StooqDailyReader(
            symbols=name,
            start=start,
            end=end,
            chunksize=25,
            retry_count=retry_count,
            pause=pause,
            session=session,
        ).read()
            ...

don't ask for a pull request

**Comment by bashtage** [comment]
Someone needs to make a PR, if they want this fixed at least.
