### ISSUE TITLE
ImmediateDeprecationError: 

### ISSUE THREAD

**Issue by prateek2029** [pydata/pandas-datareader#580]
Google finance has been immediately deprecated due to large breaks in the API without the
introduction of a stable replacement. Pull Requests to re-enable these data
connectors are welcome.

**Comment by agrija9** [comment]
I'm having the same problem. Is there any update on this issue?

**Comment by bashtage** [comment]
Google is not working until someone finds a work around.

**Comment by agrija9** [comment]
If this helps (in the meantime), I changed the data source to 'iex'. Now I can read the data:

I did:
**C = data.DataReader("C", 'iex', start, end)**

**Comment by ZhengRyan** [comment]
> If this helps (in the meantime), I changed the data source to 'iex'. Now I can read the data:
> 
> I did:
> **C = data.DataReader("C", 'iex', start, end)**

good!!!

**Comment by Fowk** [comment]
try yahoo instead

**Comment by bashtage** [comment]
Closing since Google is gone.
