### ISSUE TITLE
ImportError: cannot import name 'is_list_like'

### ISSUE THREAD

**Issue by Millioto** [pydata/pandas-datareader#581]
`import pandas_datareader.data as web
import pandas as pd
import numpy as np
from datetime import datetime
start = datetime(2015, 2, 9)
end = datetime(2017, 5, 24)
f = web.DataReader('F', 'morningstar', start, end)
f.head()`

> Here is the error I get:
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-0eb3cbcc71fe> in <module>()
----> 1 import pandas_datareader.data as web
      2 import pandas as pd
      3 import numpy as np
      4 from datetime import datetime
      5 start = datetime(2015, 2, 9)

~/anaconda3/lib/python3.6/site-packages/pandas_datareader/__init__.py in <module>()
      1 from ._version import get_versions
----> 2 from .data import (DataReader, Options, get_components_yahoo,
      3                    get_dailysummary_iex, get_data_enigma, get_data_famafrench,
      4                    get_data_fred, get_data_google, get_data_moex,
      5                    get_data_morningstar, get_data_quandl, get_data_stooq,

~/anaconda3/lib/python3.6/site-packages/pandas_datareader/data.py in <module>()
     12     ImmediateDeprecationError
     13 from pandas_datareader.famafrench import FamaFrenchReader
---> 14 from pandas_datareader.fred import FredReader
     15 from pandas_datareader.google.daily import GoogleDailyReader
     16 from pandas_datareader.google.options import Options as GoogleOptions

~/anaconda3/lib/python3.6/site-packages/pandas_datareader/fred.py in <module>()
----> 1 from pandas.core.common import is_list_like
      2 from pandas import concat, read_csv
      3 
      4 from pandas_datareader.base import _BaseReader
      5 

**ImportError: cannot import name 'is_list_like'**

**Comment by bashtage** [comment]
You need to upgrade to the latest pdr.

**Comment by nospam999** [comment]
inserting "pd.core.common.is_list_like = pd.api.types.is_list_like" before 
import pandas_datareader.data as web
solves this problem at version 0.6.0

**Comment by atuljain2995** [comment]
import pandas as pd
    pd.core.common.is_list_like = pd.api.types.is_list_like

right before

    import pandas_datareader as web


# And your problem is solved.

**Comment by bashtage** [comment]
Fixed in master.
