### ISSUE TITLE
AlphaVantage 5/minute ratelimit is making tests fail

### ISSUE THREAD

**Issue by bashtage** [pydata/pandas-datareader#582]
We would need up to ~50 minute to pass tests.  Also affect doc building.

Should switch to allowed fail on RemoteData error with the right text.  Should also return this as part of the RemoteDataError

`Thank you for using Alpha Vantage! Please visit https://www.alphavantage.co/premium/ if you would like to have a higher API call volume`

**Comment by bashtage** [comment]
I don't think we should stretch it out.  We could do something more clever like (a) only testing in 1 config (easy) and (b) choosing a random subset of 5 tests to run, so that on average we get complete coverage eventually. 

The other alternative would be to approach AV to ask for an improved key for testing only.

**Comment by gliptak** [comment]
it doesn't stretch it out that long, sort of processes in bursts. I will submit a PR for this and https://github.com/pydata/pandas-datareader/issues/673 together.

**Comment by bashtage** [comment]
How are you going to deal with the 5 concurrent jobs on Travis?

**Comment by gliptak** [comment]
@bashtage ok, to that point the value might need to be higher. The good news is that this doesn't run PRs ...

**Comment by bashtage** [comment]
Maybe you could enable it for one job.

**Comment by bashtage** [comment]
Fixed as much as it can be.
