### ISSUE TITLE
mocking/replay-based testing instead of outbound internet usage

### ISSUE THREAD

**Issue by TheChymera** [pydata/pandas-datareader#586]
Hi everybody, I am packaging your software for Gentoo Linux and derivative distributions.
I notice that the distribution strongly discourages relying on network connectivity and production servers for testing. Having read the [“Tests that require network or service access”](https://devmanual.gentoo.org/ebuild-writing/functions/src_test/index.html) section of the documentation, I find this a very sensible approach.

More to the point, in my own experience with this package, this has caused tests to [“dynamically“ break](https://github.com/pydata/pandas-datareader/issues/583#issuecomment-425655790). For the time being I am distributing your package with the test suite disabled. Would you be interested in migrating to a test suite which can better be sandboxed in the future?

**Comment by bashtage** [comment]
I think mocking is beyond the scope for this project.
