### ISSUE TITLE
FamaFrench dataset only 2010 onwards

### ISSUE THREAD

**Issue by randlow** [pydata/pandas-datareader#596]
Hi all, 

Why is the FamaFrench factors data reader only for 2010 onwards?  From the website they have it since 1927.  I can't find how I can change the function to read data from prior to 2010

thanks

**Comment by vashOnGitHub** [comment]
Not sure why it doesn't work on here, but I shipped a getFamaFrenchFactors package just 2 days ago: https://github.com/vashOnGitHub/getFamaFrenchFactors

It gets data from their website, converts it to percentages, cleans up and returns it as a pd df.

**Comment by bashtage** [comment]
Did you set the start date?  It defaults to 1-1-2010 IIRC

**Comment by bashtage** [comment]
Closing as answered.
