### ISSUE TITLE
how to import data in csv format after reading data from quandl

### ISSUE THREAD

**Issue by Amitmoin** [pydata/pandas-datareader#598]

**Comment by atuljain2995** [comment]
RELI - Reliance company
iex - from where to fetch the data.

"But currently source services are not returning any value so it gets KeyError"

    import pandas_datareader as web
    df = web.DataReader("RELI", 'iex', start, end)
    df.to_csv('first_yahoo_prices_volumes_to_csv_demo.csv')

**Comment by bashtage** [comment]
Closing as answered.
