### ISSUE TITLE
HTTPS connection pool 

### ISSUE THREAD

**Issue by rm17tink** [pydata/pandas-datareader#600]
I keep getting this error with both websites(quandl and IEX), Thoughts? 

`SSLError: HTTPSConnectionPool(host='www.quandl.com', port=443): Max retries exceeded with url: /api/v3/datasets/WIKI/BAX.csv?start_date=2015-01-01&end_date=2018-12-10&order=asc&api_key=dddddddddd (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'ssl3_get_server_certificate', 'certificate verify failed')],)",),))`

**Comment by turkialjrees** [comment]
The error says that certificate verification failed which means that your client is not able to verify the server's certificate. You might need to update your SSL CA certificate bundle.

You might try upgrading the certifi package: pip install -U certifi.

**Comment by bashtage** [comment]
Closing as answered.
