### ISSUE TITLE
No adjusted values columns from IEX or Yahoo

### ISSUE THREAD

**Issue by vischia** [pydata/pandas-datareader#603]
Hello,

I decided to open a new issue, as I realized I was posting in comments about a quite unrelated issue.

If I use the IEX source I can get some data, but there are no adjusted values; I get the following columns:

    date, open, high, low, close, volume

whereas from quandl I was getting 12 columns:

    Date, Open, High, Low, Close, Volume, Ex-Dividend, Split Ratio, Adj. Open, Adj. High, Adj. Low, Adj. Close, Adj. Volume

If I try Yahoo, as suggested here https://github.com/pydata/pandas-datareader/issues/587#issuecomment-450471265 , I still get only "High, Low, Open, Close, Volume, Adj Close", i.e. I still miss most of the adjusted quantities, and the Ex-Dividend and Split ratio.

Am I missing something, or are the adjusted prices simply not available from IEX or Yahoo?

My question is multi-step:

- how can I get those additional columns using the "yahoo" data source? Is there a way of using the "yahoo" data source AND get the additional columns? If not, why? Can I just infer the adjustment factor from adj_close/close and apply it to the other columns? I am not familiar on whether the different adjusted quantities are adjusted, but from what I understand Ex-dividend and Split ratio are used to determine the adjustment factor: if my reasonment is correct, that one could effectively compute the factor by taking the ratio adj_close/close and then apply it to the other columns. Is that correct?

- for the IEX data source, I don't even get the "adj close", so even if my previous point is OK, with IEX I would have no way of computing the factor. Why? I have briefly looked here: https://pandas-datareader.readthedocs.io/en/latest/readers/iex.html but I could not quite understand if perhaps it's a matter of additional parameters to be set.

- in case adjusted prices are simply not available from Yahoo or IEX, does anyone have a hint on why and on whether is there a source that gives adjusted prices?

Thank you in advance!

**Comment by bashtage** [comment]
We pass through what the provider returns, so there is nothing pdr can do.
