### ISSUE TITLE
ImmediateDeprecationError: 

### ISSUE THREAD

**Issue by nashtgc** [pydata/pandas-datareader#604]
ImmediateDeprecationError: 
Google finance has been immediately deprecated due to large breaks in the API without the
introduction of a stable replacement. Pull Requests to re-enable these data
connectors are welcome.

**Comment by addisonlynch** [comment]
Google Finance has discontinued their API, and as such this feature is deprecated (marked for removal) in Pandas Datareader. Alternatives to Google Finance include Alpha Vantage, Quandl, and IEX.

**Comment by beckmiller** [comment]
How to solve this problem?

**Comment by alphadi** [comment]
Simple, use Yahoo finance. Just pass yahoo in the arguments instead of google

**Comment by surajkaul** [comment]
Is anyone looking at this? I get error when I use Options for both yahoo and google

> 
> ImmediateDeprecationError: 
> Yahoo Options has been immediately deprecated due to large breaks in the API without the
> introduction of a stable replacement. Pull Requests to re-enable these data
> connectors are welcome.
> 
> See https://github.com/pydata/pandas-datareader/issues

**Comment by seherozcelik** [comment]
bb = data.DataReader(name = "F", data_source="yahoo", start, end ) this worked

**Comment by bashtage** [comment]
Nothing to do here, the API is gone.
