### ISSUE TITLE
Robinhood Failure

### ISSUE THREAD

**Issue by TyrelCB** [pydata/pandas-datareader#605]
Roobinhood datasource stopped working within the last couple weeks

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-5-c5e209956c33> in <module>()
----> 1 robinhood_year('TNA')

<ipython-input-3-7921f944d6b7> in robinhood_year(symbol)
      1 def robinhood_year(symbol):
----> 2     return web.DataReader(symbol, 'robinhood')

c:\users\tyrel\appdata\local\programs\python\python35\lib\site-packages\pandas_datareader\data.py in DataReader(name, data_source, start, end, retry_count, pause, session, access_key)
    389         return RobinhoodHistoricalReader(symbols=name, start=start, end=end,
    390                                          retry_count=retry_count, pause=pause,
--> 391                                          session=session).read()
    392     elif data_source == 'tiingo':
    393         return TiingoDailyReader(symbols=name, start=start, end=end,

c:\users\tyrel\appdata\local\programs\python\python35\lib\site-packages\pandas_datareader\base.py in read(self)
     75         """Read data from connector"""
     76         try:
---> 77             return self._read_one_data(self.url, self.params)
     78         finally:
     79             self.close()

c:\users\tyrel\appdata\local\programs\python\python35\lib\site-packages\pandas_datareader\base.py in _read_one_data(self, url, params)
     84             out = self._read_url_as_StringIO(url, params=params)
     85         elif self._format == 'json':
---> 86             out = self._get_response(url, params=params).json()
     87         else:
     88             raise NotImplementedError(self._format)

c:\users\tyrel\appdata\local\programs\python\python35\lib\site-packages\pandas_datareader\base.py in _get_response(self, url, params, headers)
    134                 return response
    135 
--> 136             last_response_text = response.text.encode(response.encoding)
    137             time.sleep(pause)
    138 

TypeError: encode() argument 1 must be str, not None

**Comment by trevorwelch** [comment]
I'm pretty sure Robinhood is shutting down that endpoint. If you navigate to: https://api.robinhood.com/quotes/AAPL/ for example you see that it's always blank now
