### ISSUE TITLE
IEX Default Start is Invalid

### ISSUE THREAD

**Issue by k128** [pydata/pandas-datareader#607]
The default start date in the iex "daily.py" module is 1/1/2010, but it is also programmed to give an error if a start date more than five years ago is entered, so if a start date is not provided, the default behavior is to error.  The default start date should be set to be exactly five years ago from the current date, to provide maximum length without error.

**Comment by addisonlynch** [comment]
This is correct, thank you for pointing out. I will take care of it, and it will be released in 0.8.0.

**Comment by addisonlynch** [comment]
@bashtage ``_utils._sanitize_dates`` uses 1/1/2010 as its default start date. Thinking we should update this to a later date...perhaps 1/1/2016? A few providers don't provide data at 9 years out

**Comment by gliptak** [comment]
https://github.com/pydata/pandas-datareader/issues/596 possibly related?

**Comment by addisonlynch** [comment]
@gliptak yep. We need to update these in general. Was waiting on @bashtage for direction on a new date to use.

**Comment by bashtage** [comment]
Is this still an issue?  Should the start date be reader-specific?

**Comment by gliptak** [comment]
is ```_utils._sanitize_dates``` being called for all providers?

**Comment by bashtage** [comment]
It is called in base so unless a Reader fails to super, then it gets used

https://github.com/pydata/pandas-datareader/blob/ad27478193aae59074863b1000b8fd3270c5f58a/pandas_datareader/base.py#L62

**Comment by bashtage** [comment]
Default dates can be set reader-by-reader by changing the dates from `start=None` to e.g., `start='2016-01-01'` if the common one doesn't work.  Perhaps 5-ish years as a default, so 2015-01-01? (or 2014)?

**Comment by gliptak** [comment]
Based on https://github.com/pydata/pandas-datareader/pull/677#issuecomment-531997861 the date handling could be improved.
