### ISSUE TITLE
[BUG] Yahoo duplicate row

### ISSUE THREAD

**Issue by okomarov** [pydata/pandas-datareader#610]
I am on 0.7.0 pdr:

```
pdr.get_data_yahoo('AMZN', start='2019-01-25', end='2019-01-26')
```
where `2019-01-26` is a Saturday.

This outputs:
```
                   High          Low    Open        Close   Volume    Adj Close
Date
2019-01-25  1683.449951  1662.000000  1670.5  1670.569946  4959679  1670.569946
2019-01-25  1683.479980  1661.609985  1670.5  1670.569946  4945900  1670.569946
```

It should only return the last row.

**Comment by okomarov** [comment]
This seems to be an issue with yahoo itself.

Querying same day, returns nothing:
<br>

<img width="934" alt="screenshot 2019-01-26 at 22 04 51" src="https://user-images.githubusercontent.com/3731173/51792843-3729f200-21af-11e9-8c62-4fd0b9ad282f.png">

Querying Friday to Sunday returns the two rows listed above:
<br>
<img width="943" alt="screenshot 2019-01-26 at 21 56 31" src="https://user-images.githubusercontent.com/3731173/51792861-70626200-21af-11e9-9008-5415cf96d575.png">

and params for the GET request are:

 

  name | value 
-- | --
formatted | true
crumb | plThqsOcXUi
lang | en-US
region | US
period1 | 1548374400
period2 | 1548547200
interval | 1d
events | div\|split
corsDomain | finance.yahoo.com

**Comment by okomarov** [comment]
Reported bug on [Yahoo forums](https://yahoo.uservoice.com/forums/382977-finance/suggestions/36651802-duplicate-row)

**Comment by bashtage** [comment]
Closing as answered.
