### ISSUE TITLE
Econdb parser

### ISSUE THREAD

**Issue by econdb** [pydata/pandas-datareader#616]
I just created a [pull request](https://github.com/pydata/pandas-datareader/pull/615) to include a parser for the [econdb.com](https://www.econdb.com) api. It aggregates datasets from +90 primary sources, including Bank of Japan, China National Bureau of Statistics, or Rosstat.  [Here](https://www.econdb.com/search/#q=""&models.source=true) you can find the complete list of agencies.

Behind the scenes, we have scrapers that extract, clean and process data from the primary sources, and that should save users time in doing the task themselves.

**Comment by rleallurtis** [comment]
Hi econdb,

I have been testing the library dataparser with your data source (econdb) and I have found some pandas errors (ValueError) using the code that you generate using your export python option (df = web.DataReader('dataset=ABS_GDP&to=2020-01-01&from=1964-01-01&h=TIME&v=Indicator', 'econdb'))

The error that pandas returns is the following one: **ValueError: columns overlap but no suffix specified: Index(['values'], dtype='object')**

Testing the econdb API,
I saw that you can retrieve a specific dataset or multiple datasets, I used the following links:
https://www.econdb.com/api/series/?ABS_GVA_CVM
https://www.econdb.com/api/series/ABS_GVA_CVM.A2716056J.Q.AU

Testing your API with these URLs (https://www.econdb.com/api/series/?ABS_GVA_CVM, https://www.econdb.com/api/series/ABS_GVA_CVM.A2716056J.Q.AU) and looking over the code, I saw the following:

```
for entry in results:
    series = pd.DataFrame(entry["data"])[["dates", "values"]].set_index("dates")
```
_Results can not exist sometimes_

```
   if not df.empty:
    df = df.join(series, how="outer")
  else:
    df = series
```
_Also, Values column can exist multiple times (this provokes a ValueError (Columns overlap)). DataFrame join raises ValueError if there are multiple columns with the same name without specifying suffix_

I think that this error can be fixed if the label 'values' is replaced for the indicator or ticker in this case ("ticker": "TDB10295.1070001_1077778_ITC11_450.M.IT",)

Regards :)

**Comment by econdb** [comment]
Hi @rleallurtis 

There were a couple of issues in your request, one in the data serialization and another in the pandas_datareader parser. We fixed them both (https://github.com/pydata/pandas-datareader/pull/758). 

Thanks for using the service, and feel free to write us at admin@econdb.com if you have other questions around the data. 

Cheers
