### ISSUE TITLE
Tiingo IEX Historical Reader is Missing

### ISSUE THREAD

**Issue by boingaon** [pydata/pandas-datareader#618]
Tiingo's IEX Historical API curates and stores a much larger rolling data window over IEX's native API, so I think it would be great if it could be included. I have the change prepared but wanted to open an issue for discussion first.

API:
https://api.tiingo.com/iex/{{ticker}}/prices

Doc:
https://api.tiingo.com/docs/iex/realtime#historicalPriceData

**Comment by tiingo** [comment]
Furthermore, we are working on expanding the data back to October of 2016 :) 
Let us know if you nee any help on implementation!

We also plan to offer parsed tick data files from then as well :)

**Comment by bashtage** [comment]
Fixed in #619
