### ISSUE TITLE
Inconsistent naming of API key parameter

### ISSUE THREAD

**Issue by addisonlynch** [pydata/pandas-datareader#620]
All ``Reader`` objects have the ``api_key`` attribute which stores their API key (when needed). For example, ``get_data_quandl`` (which uses ``QuandlReader``) accepts ``api_key`` as an argument.

However, one must pass ``access_key`` instead of ``api_key`` to ``DataReader``, which may create confusion ([example](https://stackoverflow.com/questions/54675413/what-is-wrong-with-the-placement-of-my-api-key/54675521#54675521)).

I think it would be best to rename the ``access_key`` for ``DataReader`` to ``api_key`` to create consistent behavior between itself and all other functions in ``data``. 

One other option would be to change the ``api_key`` attribute to ``access_key`` in all other instances, but this is less reasonable in the interest of POLA.

**Comment by bashtage** [comment]
Fixed by #693
