### ISSUE TITLE
Easiest way to find stock name from it's Yahoo format symbol?

### ISSUE THREAD

**Issue by otis632** [pydata/pandas-datareader#622]
My program asks users to input the stock/index symbol as per YF to make data-reads easier. However, I'm not looking for a simple way to query the full stock/index name.

**Comment by keadillantegakkan** [comment]
Do you mean you like to enter the full company's name instead of the ticker symbol? 
I think I would map the company's name to the ticker symbol and then pass the variable into the function that you are using the query the data.

**Comment by bashtage** [comment]
This resolution isn't supported in pdr.
