### ISSUE TITLE
IEX Cloud as new data source?

### ISSUE THREAD

**Issue by gliptak** [pydata/pandas-datareader#623]
Next iteration of IEX data

https://iexcloud.io/

https://iextrading.com/developer/docs/

**Comment by addisonlynch** [comment]
@gliptak thanks...I was planning to roll my implementation from [iexfinance](https://github.com/addisonlynch/iexfinance) into this (I wrote the original IEX daily reader for PDR). Most of the endpoints have remained the same, but there are a few new ones, including financial statements, which we may want to implement.

IEX is maintaining their old API until at least June, so I was planning on using that for PDR until then, as it does not require registration and is free.

**Comment by gliptak** [comment]
yes, we are to obtain a token to be used for ```Travis```

**Comment by addisonlynch** [comment]
See https://iexcloud.io/docs/api/#sandbox

**Comment by kabonker** [comment]
So will we all have to get like API keys and accounts?   Will the current Pandas datareader for IEX be upgraded to a new one?   Or will it just end?  June is fast approaching, I think they give the data back as JSON but have not tried to interface yet.

**Comment by addisonlynch** [comment]
@kabonker yes. We will port the existing readers to the IEX Cloud platform. Legacy V1 (no auth) API will be discontinued by the provider on 6/1/19, so it will be done by then. You will need to sign up for an API key, as IEX Cloud requires authentication.

**Comment by gliptak** [comment]
Closing with https://github.com/pydata/pandas-datareader/pull/638 merged
