### ISSUE TITLE
Error for every data feed - please help

### ISSUE THREAD

**Issue by michaelwjoyner** [pydata/pandas-datareader#628]
I am new to Python, from pyChame venv I did a "pip install pandas_datareader" and it installed 0.7.0.  No matter what data feed I try I get this:

_import pandas_datareader as pdr
pdr.get_data_fred('GS10')_

`Traceback (most recent call last):
  File "/home/mj/PycharmProjects/untitled/helloworld.py", line 1, in <module>
    import pandas_datareader as pdr
  File "/home/mj/PycharmProjects/untitled/venv/lib/python3.6/site-packages/pandas_datareader/__init__.py", line 2, in <module>
    from .data import (DataReader, Options, get_components_yahoo,
  File "/home/mj/PycharmProjects/untitled/venv/lib/python3.6/site-packages/pandas_datareader/data.py", line 29, in <module>
    from pandas_datareader.stooq import StooqDailyReader
  File "/home/mj/PycharmProjects/untitled/venv/lib/python3.6/site-packages/pandas_datareader/stooq.py", line 43
    elif symbol_parts[1].lower() == 'pl:
                                       ^
SyntaxError: EOL while scanning string literal

Process finished with exit code 1`

**Comment by addisonlynch** [comment]
```python
from pandas_datareader import data as web

web.get_data_fred("GS10")
```

**Comment by michaelwjoyner** [comment]
Hi Addis, I did that, this is what I am getting back.

![image](https://user-images.githubusercontent.com/17679881/54500770-9073ef00-48dd-11e9-844c-4f64501ef779.png)

**Comment by addisonlynch** [comment]
Ahh, I see. There is a typo in ``stooq.py`` that is causing this error. We will repair soon.

**Comment by michaelwjoyner** [comment]
Addison, good eye mate.

**Comment by michaelwjoyner** [comment]
@addisonlynch How when I know when the patch is made?

**Comment by bashtage** [comment]
Fixed in master now.
