### ISSUE TITLE
Could not convert string to float: 'N'

### ISSUE THREAD

**Issue by oucler** [pydata/pandas-datareader#630]
Starting from today (03/18/2018) not able to get list of nasdaq ticker list. I was able to run the command below and it worked fine previously.

import pandas as pd
import pandas_datareader.data as web

web.get_nasdaq_symbols()

I am getting the error message below:

    data = self._reader.read(nrows)

  File "pandas/_libs/parsers.pyx", line 899, in pandas._libs.parsers.TextReader.read

  File "pandas/_libs/parsers.pyx", line 914, in pandas._libs.parsers.TextReader._read_low_memory

  File "pandas/_libs/parsers.pyx", line 991, in pandas._libs.parsers.TextReader._read_rows

  File "pandas/_libs/parsers.pyx", line 1123, in pandas._libs.parsers.TextReader._convert_column_data

  File "pandas/_libs/parsers.pyx", line 1197, in pandas._libs.parsers.TextReader._convert_tokens

ValueError: could not convert string to float: 'N'

pandas_datareader.__version__
'0.6.0'

**Comment by toddpi314** [comment]
Just started seeing this over in CA, USA this morning as well on `0.6.0`

**Comment by oucler** [comment]
I have tried with multiple pandas versions:
0.24.2
0.23.4
0.23.0
0.22.0

but it is the same error. I am guessing the data sent for parsing causing the issue.

**Comment by toddpi314** [comment]
Hmmm, has that last line always been there?

```
...
Y|ZYME|Zymeworks Inc. Common Shares|N| |N|100|N||ZYME|ZYME|N
Y|ZYNE|Zynerba Pharmaceuticals, Inc. - Common Stock|Q|G|N|100|N|N||ZYNE|N
Y|ZYXI|Zynex, Inc. - Common Stock|Q|S|N|100|N|N||ZYXI|N
File Creation Time: 0318201917:03|||||
```

ref: ftp://ftp.nasdaqtrader.com/SymbolDirectory/nasdaqtraded.txt

**Comment by oucler** [comment]
I found the problematic two stock names:
Y|ISEM|Invesco RAFI Strategic Emerging Markets ETF|Q|G|Y|100|N|N||ISEM|N
Y|ISF|ING Group, N.V. Perp Hybrid Cap Secs (Netherlands)|N| |N|100|N||ISF|ISF|N

if you remove these two stock from the list that works fine as a temporary solution.

I added "del lines[4207:4209]"  after converter_map variable decleration in nasdaq_trader.py file. This is not an elegant solution but for time being it works.

**Comment by bashtage** [comment]
Working now.
