### ISSUE TITLE
Stooq  download Error

### ISSUE THREAD

**Issue by gswf-sha** [pydata/pandas-datareader#632]

**Comment by gswf-sha** [comment]
The following code used to work:
`f = web.DataReader('^DJI', 'stooq')
`
but now returns following error:
> 
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-3-69dd4e0174b3> in <module>
----> 1 f = web.DataReader('^DJI', 'stooq')

~/anaconda/envs/ds/lib/python3.7/site-packages/pandas_datareader/data.py in DataReader(name, data_source, start, end, retry_count, pause, session, access_key)
    340                                 chunksize=25,
    341                                 retry_count=retry_count, pause=pause,
--> 342                                 session=session).read()
    343 
    344     elif data_source == "iex-book":

~/anaconda/envs/ds/lib/python3.7/site-packages/pandas_datareader/base.py in read(self)
    208         if isinstance(self.symbols, (compat.string_types, int)):
    209             df = self._read_one_data(self.url,
--> 210                                      params=self._get_params(self.symbols))
    211         # Or multiple symbols, (e.g., ['GOOG', 'AAPL', 'MSFT'])
    212         elif isinstance(self.symbols, DataFrame):

~/anaconda/envs/ds/lib/python3.7/site-packages/pandas_datareader/base.py in _read_one_data(self, url, params)
     82         """ read one data from specified URL """
     83         if self._format == 'string':
---> 84             out = self._read_url_as_StringIO(url, params=params)
     85         elif self._format == 'json':
     86             out = self._get_response(url, params=params).json()

~/anaconda/envs/ds/lib/python3.7/site-packages/pandas_datareader/base.py in _read_url_as_StringIO(self, url, params)
     99             service = self.__class__.__name__
    100             raise IOError("{} request returned no data; check URL for invalid "
--> 101                           "inputs: {}".format(service, self.url))
    102         if isinstance(text, compat.binary_type):
    103             out.write(bytes_to_str(text))

OSError: StooqDailyReader request returned no data; check URL for invalid inputs: https://stooq.com/q/d/l/

> 
Any help will be appreciated.

**Comment by addisonlynch** [comment]
Try downloading the latest development version of pandas datareader from git. The following works for me:

```python

from pandas_datareader import data as web

web.DataReader("^DJI", "stooq")
```

**Comment by bashtage** [comment]
Closing as answered.
