### ISSUE TITLE
Won't pull data from Yahoo Finance

### ISSUE THREAD

**Issue by rajpatel5** [pydata/pandas-datareader#637]
This is the error I get when trying to pull MSFT stock data.
It was working earlier today, but when I came to it like 10 minutes later, this kept popping up!

pandas_datareader._utils.RemoteDataError: Unable to read URL: https://finance.yahoo.com/quote/MSFT/history?period1=1399449600&period2=1554710399&interval=1d&frequency=1d&filter=history
Response Text:
b'\x1f\x8b\x08\x00\x00\x00\x00\x00\x00\x03\x85U{o\xdb6\x10\xff\x7f\x9f\x82e\x90\xd7j\xea\xe1\xa6Kc[\x1e\xba>\x80\x00E;t\t\xb6b\x18\n\x9a:K\x84%R%)?Z\xe4\xbb\xf7(Y\xb2\xe3$\x98\x04A\xc7{\xf1~w\xbc\xe3\xe4\xd9\xdbOon\xbe\xfc\xf9\x8e\xe4\xae,\xa6\xbf\x102\xf1\x04)\xb8\xca\x12\n\x8a\xd5\x96N\'9\xf0\xb4\x91\x95\xe08j\xba\x8a\xc1\xb7Z.\x13*\xb4r\xa0\x1cs\x9b\n(\xd9\xae\x12\xea`\xedB\xefhLD\xce\x8d\x05\x97\xdc\xde\xbcg\xaf\xa8\xf7\xe2\x9f\xd6S\'\xa3\xb5\x9b\xef\x0b\x9dt\x05L\xbf\xf0\\\xebI\xd8.\xee\xd9)^BB\x97\x12V\x956no\xdf\x95L]\x9e\xa4\xb0\x94\x02X\xb3\x18H%\x9d\xe4\x05\xb3\x82\x17\x90\xc4\x83\x12\x19%\xaeky\x10\xcc>\xac\x7f\xd8\xedk\xf6F\x97\x15wrV\xec#\xbb~\x97@\x9a\xc1@\xe4Fc\x10\xf1\xce\x89u\x9b6\xce&\x81?\xb6\xec\x1cd\x96\xbb\x11\x89\xa3\xe8x\x8c\xbc;\xfcf:\xdd\xf4\n3.\x16\x99\xd1\xb5JG\xe4h\xce\xf1\x15\xa46\xc5\x99\x0f\xc7\x8e\xc2\xd0\x06\x1bYf\x81\xd0e\xa8T\x88dhy\xca*\xaeR\xce\x86Q|\x11\r\x87Q\xf4\xdb\x8b8\xa8TvN^F\xc7\xfe\x1b?p\xce\xac\xfc\x0e#\xc4\xb1\x043~"6\xff\xf8\xca1^\xc8L\xa12"\xdei\xcf1\x05#\xf2"\x8aH\xfc\xaaZ\x13\x9aC\xb1\x04\'\x05\x96\x03j\xa0\x03\xd23\x06\x047I\xb9B\xc2a\rK\xfcs\x835\x18\x10\xcb\x95e\x16\x8c\x9cw\xb9p\x1c\xf3\xfbd\xb6\xfc\xd3\x94\xf1 Ho\xc4\n\xbe\xd15*\xcf\xe5\x1a\xd2\x1e\xb16)\x18&tQ\xf0\xca6\x88[\xea@\xc1V\\H\x95\x8dHt_0"J+\xe8\xa2\xcb\xe3>4\x0f\x7f\x9b\xc4\x8ba\xb5\xde\xcf\n[m\xc3\xbe\x88zo\xb8\xadFgG\xc8\x8a\xae\xa2\xce_\xd5\xbb\xeb\xe4\xf1k\xffv\xf2\xa3\x12\xac\xe5\x19\xb0\x83}\xbb\rf\xba\xe8\x91\x96\xdcdRm\x01\xdc3\x1e\xf6\xc6\xa9\xb4\x15\xa6iD\xa4*\xa4\x026+\xb4Xt\x0e~=\x90v\xfc\xefZ\x97\x98\xef\xdd>k\xd6\xd5\xe0\x12\xca\x8e\xfd\xf5\x80w\xd7\xf5A\xd87\xc2\xc4\n#+\xd7vH\xaaE]\xe2\x81\nVF:8;\x9d\xe0Q&\xd6\x88\x84\x86a\x06:\xd8\xf8no\x8e\xf9\xecw\x9b\xc4\xf1\xd5\xe5\xe5\xcb\xcbxxu\xe2\x92\xd3\xe7\nV\xe4-G\xb3\xf3 \x03w#K\xa4\x9e\x9f\x9exs\xbe\xb2\'`\xccW\xec\x19T\x04%t\n\xb7\x9f\xaf}\xf3b!\x95;\xeb7\xbe\xfd\xfc\xc1\x1b\xa1rr<\xa9\xac\x15\xd3\x13\x07\xd6=nuz<\xf9\xf1G-\x16\xe0\xee\xc4\xb7\xfc\xdf\x116\xd9\x7f\xd3S\xb4\xa7\xed\x81LhT\xad\xe9\xf6\xc0\xb6\x8b\x10\xe5\xe3%7d\x06\x1c\xe7\x05I\x88\x0f\xfb\xba\xc4\x92\x9c\x9d\x8f[f\xb0E<\x13*\x98W{\xa0\xabC\xd0\xf4q\xd0\xf4\x01h\xfa\xff\xa0\xe9C\xd0\x8fZ=\x01\xda\x97\x17\xcb\xda\x17s\x12\xf6\x17\x82\x1fe\r\xf1\x8c1b\x1dw\xb5%\xde-\xf1\xcdpA\x18\xeb\x85\x1f\xb5#\xef\xfd$"\x98\x9a\xbf\xc0\xe0\x88\xe8\xc4M;\xb7T\xe3o\xe2\xcc\xee*H{\xb2?0O\x8f\xc6&\x9f\xac\xd0\x99\xde\x9b\x8d\xc3+?\x1b)\xe1\x05\xc2n.\x15\xf2\x015v\x93\x1b\xbb\xbc9\xb3\tm{\x8a9]!vlr:\xfd[\x16\x05\x16\x94\x18_\xe7f\x9e\x06A\x80\t\x88{\xeb\x8a\xc8\x14-\xbb\xc6\xa5\xd3\x9b\x9c\xab\x05\xc1\xd9\x84\xbdk\xfc\xdf\x10\x7f\x8f`\xbe\x01-\xab\'\x0c\x87t\xfa\t5Aa\x00\x00\xc6\xe2\xc8\x04\xb2\xd2f\x81S\x8a\xe0\xad$\x16\xc5\x868M\x0cX\x8ds\x96\xb8\x1c\x88\xb4\xb6\xbe\xef3l\xf3\x85\x7f\xb3\xfd\xb7\x19\rw9\x0e\xb7\x9c\xe6\xc2\xff\t\x85J\xd2\xb9\x00\x08\x00\x00'

**Comment by keadillantegakkan** [comment]
Works for me.
![image](https://user-images.githubusercontent.com/51392956/58936367-25caa500-87a2-11e9-94ee-7c16e71cd9c6.png)

**Comment by rajpatel5** [comment]
Well yea it works now, but when I first posted this it didn't!
