### ISSUE TITLE
DataReader should raise an exception when a data_source is not implemented

### ISSUE THREAD

**Issue by femtotrader** [pydata/pandas-datareader#64]
Hello,

I think it will be more explicit if DataReader raised an exception when data_source is not
in  `("yahoo", "yahoo-actions", "google", "fred", or "ff")``

Maybe something like

    if data_source == "yahoo":
        return ...
    ...
    elif data_source == "famafrench":
        return ...
    else:
        raise(NotImplementedError("data_source=%r is not implemented" % data_source))

Kind regards

**Comment by davidastephens** [comment]
Agreed
