### ISSUE TITLE
Trouble getting data from Yahoo Finance

### ISSUE THREAD

**Issue by Mlutzky** [pydata/pandas-datareader#641]
When I try to run the get_data_yahoo() i get the following error:
   super(YahooDailyReader, self).__init__(symbols=symbols,

TypeError: super(type, obj): obj must be an instance or subtype of type
I have tried running on google and getting the same error there. Is there something that changed in the program because it was working yesterday and then this error repeatedly started showing up. I have not found any fixes out there. Thank you for the help.

**Comment by albertoivo** [comment]
Try this:
```python
import pandas_datareader.data as web
import datetime

last_year = datetime.datetime.now().year - 1
start = datetime.datetime.now().replace(year=last_year)
end = datetime.datetime.now()

apple = web.DataReader('aapl', 'yahoo', start, end)
```

**Comment by e4chai** [comment]
It worked! thanks!

**Comment by bashtage** [comment]
Closing as answered.
