### ISSUE TITLE
can not pull data 

### ISSUE THREAD

**Issue by IrinaMax** [pydata/pandas-datareader#643]
`df = web.DataReader("XOM", "morningstar", start, end)`
giving error
`---------------------------------------------------------------------------
ImmediateDeprecationError                 Traceback (most recent call last)
<ipython-input-26-73c0e86e3b41> in <module>
----> 1 df = web.DataReader("XOM", "morningstar", start, end)

~/anaconda3/envs/dlaiwtpip/lib/python3.6/site-packages/pandas_datareader/data.py in DataReader(name, data_source, start, end, retry_count, pause, session, access_key)
    385         return MorningstarDailyReader(symbols=name, start=start, end=end,
    386                                       retry_count=retry_count, pause=pause,
--> 387                                       session=session, interval="d").read()
    388     elif data_source == 'robinhood':
    389         return RobinhoodHistoricalReader(symbols=name, start=start, end=end,

~/anaconda3/envs/dlaiwtpip/lib/python3.6/site-packages/pandas_datareader/mstar/daily.py in __init__(self, symbols, start, end, retry_count, pause, timeout, session, freq, incl_splits, incl_dividends, incl_volume, currency, interval)
     55                  incl_splits=False, incl_dividends=False, incl_volume=True,
     56                  currency='usd', interval='d'):
---> 57         raise ImmediateDeprecationError(DEP_ERROR_MSG.format("Morningstar"))
     58         super(MorningstarDailyReader, self).__init__(symbols, start, end,
     59                                                      retry_count, pause,

ImmediateDeprecationError: 
Morningstar has been immediately deprecated due to large breaks in the API without the
introduction of a stable replacement. Pull Requests to re-enable these data
connectors are welcome.

See https://github.com/pydata/pandas-datareader/issues`

**Comment by bashtage** [comment]
Morningstar is not supported. They changed their API and there was no obvious method available to fix it.
