### ISSUE TITLE
IEX API has changed: now it requires a token

### ISSUE THREAD

**Issue by mmistroni** [pydata/pandas-datareader#645]
HI all
 just discovered that IEX now has deprecated the old free api and requires now a token and a subscription. 
Afaik IEX is one of the sources supported by pandas datareader. Will you be adding support for this token? alternatively, which other sources will you recommend to get latest market data?
Thanks and regards
 Marco
PS let me know if any help is needed i would be willing to volunteer my time as i am an API user and i desperately need pd-datareader for my own pet projects

**Comment by addisonlynch** [comment]
Implementation ready in #638 and should be merged soon.

**Comment by mmistroni** [comment]
Hello any ETA on when it'll be available to the wide public? just for my own interest
kind regards

**Comment by addisonlynch** [comment]
@mmistroni token support is now live via #638 for historical data only. Documentation updates forthcoming

**Comment by jagand** [comment]
Do we pass IEX_API_TOKEN as a parameter when calling or is it just an environment variable? And do we store just the public key as the value if its environment variable

**Comment by addisonlynch** [comment]
You can pass the value as the ``api_key`` keyword argument as follows:

```python
web.DataReader("AAPL", "iex", api_key="<YOURKEY>")
```

or by setting ``IEX_API_TOKEN``

**Comment by jagand** [comment]
> You can pass the value as the `api_key` keyword argument as follows:
> 
> ```python
> web.DataReader("AAPL", "iex", api_key="<YOURKEY>")
> ```
> 
> or by setting `IEX_API_TOKEN`

Getting below error when I try f = web.DataReader('F', 'iex', api_key="sk_")

Traceback (most recent call last):
  File "Test5.py", line 4, in <module>
    f = web.DataReader('F', 'iex', api_key="sk_")
TypeError: DataReader() got an unexpected keyword argument 'api_key'

**Comment by mmistroni** [comment]
hi 
sorry not very familiar with git hub and these pull requests. Could you pls tell me how can i download the version which contains the fix for iex api? 
kind regards
 Marco

**Comment by addisonlynch** [comment]
@mmistroni you can install the latest git repo via:

```bash
pip install -e git+https://github.com/pydata/pandas-datareader
```

**Comment by addisonlynch** [comment]
Oops @jagand the parameter is ``access_key``. Sorry about that

```python
f = web.DataReader("F", "iex", access_key="sk_")
```

**Comment by VeeGee257** [comment]
> @mmistroni you can install the latest git repo via:
> 
> ```shell
> pip install -e git+https://github.com/pydata/pandas-datareader
> ```

Hi,

I get the below error when I run this:
Could not detect requirement name for 'git+https://github.com/pydata/pandas-datareader', please specify one with #egg=your_package_name

Please help.
Thanks
V

**Comment by VeeGee257** [comment]
> You can pass the value as the ~`api_key`~ `access_key` keyword argument as follows:
> 
> ```python
> web.DataReader("AAPL", "iex", access_key="<YOURKEY>")
> ```
> 
> or by setting `IEX_API_TOKEN`

Hi,

I am trying this and getting the below error:
TypeError                                 Traceback (most recent call last)
<ipython-input-11-56c05cc14881> in <module>
      1 from pandas_datareader.data import Options
      2 
----> 3 fb_options = Options('FB', 'iex',access_key="IEX_API_TOKEN")

TypeError: Options() got an unexpected keyword argument 'access_key'

Do I need to go to IEX and generate a user specific token? If yes, how do I do that?

Thanks
V

**Comment by mmistroni** [comment]
Yes.look out for iexcloud
U can get free subscription with a limited amount of messages.or u can pay
$9 a month for more.
Depending on ur usage -historical data consumes quite a bit of msgs- u will
have to choose a decent plan
Hth

**Comment by mmistroni** [comment]
Same for me

pip install -e git+https://github.com/pydata/pandas-datareader
Could not detect requirement name for
'git+https://github.com/pydata/pandas-datareader', please specify one
with #egg=your_package_name

am i missing something?

kind regards

**Comment by VeeGee257** [comment]
> iexcloud

Thanks!! Will try it out.

**Comment by sdressler** [comment]
> Same for me pip install -e git+https://github.com/pydata/pandas-datareader Could not detect requirement name for 'git+https://github.com/pydata/pandas-datareader', please specify one with #egg=your_package_name am i missing something? kind regards

It must be `pip install git+https://github.com/pydata/pandas-datareader` (without `-e`).

**Comment by addisonlynch** [comment]
@sdressler is correct. Apologies for the typo...corrected now.

**Comment by bashtage** [comment]
Closing as fixed.
