### ISSUE TITLE
Google discontinued the API, use IEX instead, that lets you obtain the data for the past 5 years

### ISSUE THREAD

**Issue by Rutu18** [pydata/pandas-datareader#646]
Google discontinued the API, use IEX instead, that lets you obtain the data for the past 5 years

_Originally posted by @adityathakur2310 in https://github.com/pydata/pandas-datareader/issues/587#issuecomment-433686072_

**Comment by Rutu18** [comment]
data_source='IEX' is not implemented

this error we get when we use IEX

**Comment by mmistroni** [comment]
dr.DataReader(symbol, 'iex', start, end)[['close']]
But it wont work as IEX has done a change recently (1st of June) where it requires an api key.
Have raised issue and it has been addressed, only i dont know when it'll be merged into the master and made available to everyone
