### ISSUE TITLE
try this:

### ISSUE THREAD

**Issue by Rutu18** [pydata/pandas-datareader#647]
try this:
df = web.DataReader(
        selected_dropdown_value, data_source='yahoo',
        start=dt(2017, 1, 1), end=dt.now())

change 'google' for 'yahoo'

_Originally posted by @lfirpo in https://github.com/pydata/pandas-datareader/issues/587#issuecomment-427505165_

======================================================
For this we get error of DATE  when used yahoo.Yahoo works for BAC rest (CG,GS)gives error

**Comment by Nyaribari** [comment]
you can also use : yahoo=data.DataReader('GOOG',start='2004', end='2019',data_source='yahoo')

**Comment by mmistroni** [comment]
uh wasnt' yahoo API deprecated?

**Comment by elva4012** [comment]
It was Google API deprecated
