### ISSUE TITLE
Yahoo dividend adjustments

### ISSUE THREAD

**Issue by simongarisch** [pydata/pandas-datareader#651]
I bumped into this while fixing tests for https://github.com/pydata/pandas-datareader/pull/650

test_yahoo::TestYahoo::test_yahoo_DataReader assumes that Yahoo does not by default adjust dividends for splits.

It looks like yahoo has changed this logic. I can see unadjusted dividends on the Nasdaq page and adjusted dividends on the Yahoo page.

Taking the AAPL example there was a cash dividend of 3.29 (Nasdaq site) on 8 May 2014.
There was then a 1/7 stock split on 09 Jun 2014.
Yahoo records this 8 May dividend as $0.47 (= 3.29 / 7), so yahoo appears to be making dividend adjustments for splits by default.

Within daily.py yahoo.pandas_datareader we have the parameter adjust_dividends: bool, default false. If you set adjust_dividends = True then it'll assume that Yahoo has not made this adjustment and will try to adjust for the dividends a second time. Unadjusted divi = 3.29, yahoo adjusted divi = 3.29 / 7 = 0.47, but then pandas_datareader will adjust this again to 0.47 / 7 = 0.067.

Once you've merged my current pull request I'll look to continue and apply a fix.

**Comment by gliptak** [comment]
@simongarisch #650 was merged

**Comment by simongarisch** [comment]
@gliptak This issue is good to close thanks and fixed as part of #650
