### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by CHIMMARA** [pydata/pandas-datareader#652]
import datetime as df
import matplotlib.pyplot as plt
from matplotlib import style
from matplotlib.finance import candlestick_ohlc
import matplotlib.date as mdates
import pandas as pd
import pandas_datareader.data as web

style.use('ggplot')
start=dt.datetime(2018,1,1)
end=dt.datetime(2019,1,1)
df=web.DataReader('INFY','yahoo',start,end)
print(df.head(10))

df_ohlc=df['Adj Close'].resample("10D").ohlc(
df_volum=df['volume'].resample('10D').sum()
print(df_ohlc.head())

I am getting below error for this code
 File "<ipython-input-32-dd6accfa2ceb>", line 17
    print(df_ohlc.head())
        ^
SyntaxError: invalid syntax

**Comment by CHIMMARA** [comment]
can somebody help on error

**Comment by suminb** [comment]
Looks like you're missing a closing parenthesis:

```
df_ohlc=df['Adj Close'].resample("10D").ohlc( <-- HERE
df_volum=df['volume'].resample('10D').sum()
print(df_ohlc.head())
```

**Comment by f-vert** [comment]
do you need a bachelors to be a data analyst?

**Comment by bashtage** [comment]
Pde only please.
