### ISSUE TITLE
ModuleNotFoundError: No module named 'pandas_datareader'

### ISSUE THREAD

**Issue by cSharma19** [pydata/pandas-datareader#661]
I've seen some similar issues, but haven't been able to solve mine, hence the post. 

Operating system: Windows 10
IDE: VS Code
Python: 3.7.3
Distribution: Anaconda

1. I created a virtual environment using Conda
2. I installed pandas_datareader using: conda install -c anaconda pandas-datareader 
3. I confirmed that the package is present in the virtual enviroment
4. pandas version: 0.25.0
5. pandas_datarader:0.7.4
6. When I run import pandas_datareader in VS Code (and I'm running the command interactively/in Jupyter notebook), I get the following error

ModuleNotFoundError                       Traceback (most recent call last)
 in 
----> 1 import pandas_datareader

ModuleNotFoundError: No module named 'pandas_datareader

I also ran : conda install -c anaconda ipykernel, and then attempted another import, only to get more detailed errors.

![image](https://user-images.githubusercontent.com/39869009/62979810-6ff78480-bdea-11e9-99ee-cd04aa5016e5.png)

At this point - I'm not sure of what I'm doing...and I was hoping to get some advice before I break something on my system.....
thanks
Chet

**Comment by bashtage** [comment]
You have an old pandas-datareader on your path. You need to remove it.

**Comment by cSharma19** [comment]
@bashtage  - thanks for the response. I'm very new to this....would you mind elaborating a little more? As far as I know, I have the latest version of the install; this is the command I used.
https://anaconda.org/anaconda/pandas-datareader

**Comment by bashtage** [comment]
You need to install using pip.

**Comment by cSharma19** [comment]
Thanks. Doesn't work.

**Comment by bashtage** [comment]
1. Create a new Python 3.7 virtual env
2. `pip install pip --upgrade`
3. `pip install pandas-datareader`

Just did this and it 100% works.  If this doesn't solve your problem, then you need general Python support since it isn't a pdr issue.

**Comment by cSharma19** [comment]
Thanks for the help again. I think you're right...I'll look at Python support....this is the only package among the others (numpy, pandas, matplotlib,math etc.) that I'have had trouble with. Quite bewildered.

**Comment by cSharma19** [comment]
So turns out that I have to downgrade the pandas version. This is what I tried and it worked!

1. conda install pandas = 0.24.2 (from cmd terminal in VSC)
2. import pandas_datareader (from test.py notebook in VSC, running interactively/Jupyter)
3.  just an extra bit of testing:
from pandas_datareader import data as wb
pg=wb.DataReader('PG',data_source='yahoo',start='2019-1-1')
plt.plot(pg)

All commands ran fine. Whew. I'm closing this thread. Thanks for taking a look in any case @bashtage

**Comment by larikhin** [comment]
I used number "3" after command pip3 and python3 and sudo:
sudo pip3 install pip --upgrade
sudo pip3 install pandas-datareader

**Comment by Cristishor201** [comment]
> 1. Create a new Python 3.7 virtual env
> 2. `pip install pip --upgrade`
> 3. `pip install pandas-datareader`
> 
> Just did this and it 100% works. If this doesn't solve your problem, then you need general Python support since it isn't a pdr issue.

In python 3.8 it doesn't working.

**Comment by ChemFien** [comment]
I managed to install via cmd line but not import this through conda. I get the error below:

Traceback (most recent call last):
  File "/Users/mac/PycharmProjects/Pyhton for Finance/Finance/Finance 1 - Stocks list.py", line 4, in <module>
    import pandas_datareader as web
ModuleNotFoundError: No module named 'pandas_datareader'

**Comment by cartersalna** [comment]
https://www.youtube.com/watch?v=dhQwVAVYy7k
Made a video on the things I did to fix... not a good coder but it got it to work for me.
