### ISSUE TITLE
Travis You have submitted an incorrect Quandl code

### ISSUE THREAD

**Issue by gliptak** [pydata/pandas-datareader#672]
Travis master build https://travis-ci.org/pydata/pandas-datareader/jobs/584354323/ shows:

```
>       raise RemoteDataError(msg)
E       pandas_datareader._utils.RemoteDataError: Unable to read URL: https://www.quandl.com/api/v3/datasets/LSE/RBS.csv?start_date=2007-01-01&end_date=2007-01-05&order=asc&api_key=[secure]
E       Response Text:
E       b'code,message\nQECx02,You have submitted an incorrect Quandl code. Please check your Quandl codes and try again.\n'
```

Can an Admin add/update the Quandl key for Travis?

https://github.com/pydata/pandas-datareader/issues/532
https://github.com/pydata/pandas-datareader/issues/620

**Comment by bashtage** [comment]
I updated the key. Will have to wait to see if it works.
