### ISSUE TITLE
RLS: 0.8.0 Release Tracker

### ISSUE THREAD

**Issue by bashtage** [pydata/pandas-datareader#694]
A list of issues remaining before a 0.8.0 release:

- [x] Finalize what's new
- [x] Default starting dates #607

**Comment by bashtage** [comment]
@addisonlynch @gliptak Any others?

**Comment by gliptak** [comment]
If ```Python 2,7``` is dropped, documentation and ``setup.py``` would need to be updated accordingly.

**Comment by addisonlynch** [comment]
@bashtage I'd like to do some documentation/readme updates that mention api_key change as well as upcoming end of py2 support

**Comment by addisonlynch** [comment]
I can take care of my updates this evening EST time.

**Comment by bashtage** [comment]
This one is still (and final) 2.7.  

I cut the RC but will happily accept changes.

**Comment by gliptak** [comment]
would you like to make updates date handling https://github.com/pydata/pandas-datareader/pull/677#issuecomment-531997861 ?

Also maybe a further refactoring of Travis https://github.com/pydata/pandas-datareader/pull/668#issuecomment-528640859 ?

**Comment by addisonlynch** [comment]
@gliptak I should be able to resolve those later this evening.

**Comment by bashtage** [comment]
Happy to have Travis improvements.  Although check it first as it has
changed a lot in the past 2 days.

**Comment by addisonlynch** [comment]
@bashtage was there a reason we can't update RTD? I remember you commented something about it in the past, but I can't find it. If not, we should probably remove the reference from the readme.

**Comment by addisonlynch** [comment]
If we can wait until early next week for release, that would be good. I would like to make some changes to reader configuration (default dates, auth) and should have time to do so this weekend.

TL:DR we can (and IMO should) make default dates dynamic & implement as a property. For the base reader we can do something like today - 5 years, and then the other readers can override accordingly. This will allow for arbitrary default start dates for readers which are *not* daily data (such as alphavantage intraday) so if you'd like to do the previous 90 days, that can be implemented.

This should reduce the amount of time we spend updating default dates. Will need to check into the various data sources we have for nuances.

**Comment by bashtage** [comment]
Happy to wait until next week.  5 year rolling is fine with me. Maybe sanitize_dates could have a couple of default start options, e.g, a fixed one, which might make sense for Fama French or a relative one which could take a TimeDelta parsable string (.e.g, '1d'), which would work for intraday.

**Comment by bashtage** [comment]
Will release tomorrow if there are no objections.  Can always do a point release if anything crops up.

**Comment by addisonlynch** [comment]
Sounds good

**Comment by bashtage** [comment]
Released.
