### ISSUE TITLE
Obsolete URL in Readme.rst file for development documentation

### ISSUE THREAD

**Issue by rohitjain00** [pydata/pandas-datareader#695]
I am trying to see the development documentation for in the root directory [Readme.rst](https://github.com/pydata/pandas-datareader/blob/master/README.rst) file but this gives me an 404 file not found error.

**Comment by rohitjain00** [comment]
Turns out the link was not obsolete. I think this was some problem with my internet connection. Anyway thanks for closing the issue.

**Comment by bashtage** [comment]
It was not when you opened it, but it is after I fixed it.
