### ISSUE TITLE
REL: 0.2.0

### ISSUE THREAD

**Issue by davidastephens** [pydata/pandas-datareader#70]
Issue to keep track of 0.2.0 release.

Lets do a release with the bug fixes, package structure and additional features that have been added recently.

**Comment by davidastephens** [comment]
@jorisvandenbossche Worth adding a "What's New" section to the docs?

**Comment by jreback** [comment]
what is release timing?

**Comment by davidastephens** [comment]
Doesn't look like anyone has any issue with the whatsnew - I can release it anytime.  

Worth doing it before or at the same time as Pandas 0.17 on Friday?

**Comment by jreback** [comment]
sounds good 2 me!

**Comment by stonebig** [comment]
no RC to try with pandas 0.17rc2 ?

**Comment by davidastephens** [comment]
No, but we are testing against 0.17rc1.  I will update to 0.17rc2.

**Comment by jorisvandenbossche** [comment]
@davidastephens sorry I didn't respond. Adding a whatsnew section is a very good idea I think! 
I don't have time myself to add it, but if you have any questions with the sphinx docs, just ask!

**Comment by davidastephens** [comment]
@jorisvandenbossche No problem.  I added it.

One question.  Do I need to do anything to get the issue tags turned into links to github issues (ie: (:issue:`47`)).  Or does that happen automatically on build?   My local build does not seem to be converting them.

**Comment by jorisvandenbossche** [comment]
That is a sphinx extension, but easily enabled (built-in in sphinx). See https://github.com/pydata/pandas/blob/master/doc/source/conf.py#L308 (and here https://github.com/pydata/pandas/blob/master/doc/source/conf.py#L41 to load it)

**Comment by davidastephens** [comment]
Thanks!  I'll add it.

**Comment by davidastephens** [comment]
Release 0.2.0 good to go.  Will upload to pypi and send email to pydata tomorrow.

**Comment by jreback** [comment]
@davidastephens awesome!

we just released 0.17.0, though going to pypi soon

**Comment by davidastephens** [comment]
I sent an email to pydata, I think its on hold for moderation because I haven't posted to the list before.  Other than that, release 0.2.0 is done, closing this issue.
