### ISSUE TITLE
Using switch statement instead of if-elif statement

### ISSUE THREAD

**Issue by rohitjain00** [pydata/pandas-datareader#702]
In the [data.py ](https://github.com/pydata/pandas-datareader/blob/b74b1e8553991c1fa0280f334584ddf6fce5bab2/pandas_datareader/data.py#L270)file the DataReader method should be using switch statement instead of if-elif statement. 

- Is there any specific reason to do this? 

- Or is this a backlog to improve?

**Comment by bashtage** [comment]
There is no such thing as a switch in python
