### ISSUE TITLE
Deprecate data.py

### ISSUE THREAD

**Issue by davidastephens** [pydata/pandas-datareader#71]
Given the subpackage structure implemented by #69, data.py is really just the api, could move this to the top level so you could import directly from pandas-datareader.

ie:

instead of:

```
from pandas_datareader import data 
data.Options('aapl','yahoo')
```

```
import pandas_datareader as pdr
pdr.Options('aapl','yahoo')
```

**Comment by femtotrader** [comment]
I won't deprecate for now but I would add right now to `__init__.py` this

    from pandas_datareader.data import Options
    from pandas_datareader.data import DataReader

so we will be able to do

    import pandas_datareader as pdr
    pdr.Options('aapl','yahoo')

but also

    import pandas_datareader as pdr
    pdr.DataReader('aapl','yahoo')

but with WorldBank we will still need

    from pandas_datareader import wb

Kind regards

**Comment by bashtage** [comment]
No real point in breaking tons of existing examples.
