### ISSUE TITLE
requirements.txt missing from source 0.8.0 distribution in pypi

### ISSUE THREAD

**Issue by sergiopasra** [pydata/pandas-datareader#712]
The `requirements.txt` file is missing from the source distribution 0.8.0 in pypi:

```
$ python setup.py build
Traceback (most recent call last):
  File "setup.py", line 17, in <module>
    with open("./requirements.txt") as f:
IOError: [Errno 2] No such file or directory: './requirements.txt'
```

**Comment by sergiopasra** [comment]
Seems that `requirements-dev.txt` is required and it's missing too

**Comment by bashtage** [comment]
Yes, I can see that this is a problem.  Not sure requirements-dev is needed though.

**Comment by bashtage** [comment]
Fixed and new sdist/wheel uploaded.
