### ISSUE TITLE
stooq.com - Problem getting data when symbol name ends with ".*"

### ISSUE THREAD

**Issue by kdcro101** [pydata/pandas-datareader#717]
First, thanks for the great module!

When getting data for symbol that ends with .* (CLX19.F)  `.US` is added to symbol, since `f`
is not present in the `["de", "hk", "hu", "jp", "uk", "us"]` array

This works (ohlc timeseries is returned):
`curl "https://stooq.com/q/d/l/?s=CLX19.F&d1=20190101&d2=20190930&i=d"`

This returns `No data`:
`curl "https://stooq.com/q/d/l/?s=CLX19.F.US&d1=20190101&d2=20190930&i=d"`

Workaround would be to add `"f"` in the array where check is being made

https://github.com/pydata/pandas-datareader/blob/48a538c14041bd166a4d138dd3ee372e76f6d2ab/pandas_datareader/stooq.py#L45-L51

I can provide PR with aforementioned workaround.

**Comment by bashtage** [comment]
PRs to fix bugs are always welcome.

**Comment by kdcro101** [comment]
Thanks!
