### ISSUE TITLE
Module not found when using jupyter notebook on Windows

### ISSUE THREAD

**Issue by benega** [pydata/pandas-datareader#728]
My environment:

Windows 10
Python 3.7
Anaconda Navigator 1.9.7

To reproduce the issue:

1. Create a new environment in Anaconda

2. Install pandas and pandas-datareader
conda install -c conda-forge pandas
conda install -c conda-forge pandas-datareader
* I also tried installing using pip instead and got the same error
pip install pandas-datareader 

3. Select the environment and open a terminal 

4. Run the commands "python" and then "from pandas_datareader import data" on the terminal - it works

5. Go back to the terminal and now run "jupyter notebook"

6. On the notebook try the same command "from pandas_datareader import data"
I got the Error: 
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-3-c471ce367d96> in <module>
----> 1 from pandas_datareader import data

ModuleNotFoundError: No module named 'pandas_datareader'

**Comment by bashtage** [comment]
This is some configuration error in your setup since it works from standard python.

What if you use pip to install?

```
pip install -u pandas-datareader
```

**Comment by benega** [comment]
I also tried with pip and got the same error.

It seems like a conflict between Jupyter and pandas_reader because it is working on the terminal.
As I said I created a new environment and fresh installation of pandas and pandas_datareader, any ideas what else I can do?
Is there some command that I can receive an error log when trying to import the package?

Thank you,

**Comment by bashtage** [comment]
You should delete conda and reinstall.  What it probably happening is that
you are running Jupiter from somewhere else.  There are no conflicts with
pdr and jupyter...I use them together regularly.

**Comment by bashtage** [comment]
Closing since not a pdr bug.

**Comment by tinkusoni104a** [comment]
Hi,

Even I was getting the same error. I did the following steps:
1.  conda list (To check all the installed packages)
2. If the pandas-datareader is not present. kindly install it by below command:

     conda install -c conda-forge pandas-datareader

3. Restart your conda and check that package has been installed or not
     conda list 

4. Import the package to your project.
   import pandas as pd
   from pandas_datareader import data, wb
   df=data.DataReader('AAPL','yahoo','2015/1/1','2016/1/1')

If already did, please ignore this.

**Comment by MariaAlaska** [comment]
> Hi,
> 
> Even I was getting the same error. I did the following steps:
> 
> 1. conda list (To check all the installed packages)
> 2. If the pandas-datareader is not present. kindly install it by below command:
>    conda install -c conda-forge pandas-datareader
> 3. Restart your conda and check that package has been installed or not
>    conda list
> 4. Import the package to your project.
>    import pandas as pd
>    from pandas_datareader import data, wb
>    df=data.DataReader('AAPL','yahoo','2015/1/1','2016/1/1')
> 
> If already did, please ignore this.

Thank You, It worked !!

**Comment by vipin7272** [comment]
1 conda list (To check all the installed packages) 
If the pandas-datareader is not present. kindly install it by below command:
 2 conda install -c conda-forge pandas-datareader
 3 Restart your conda and check that package has been installed or not
conda list
Import the package to your project.
import pandas as pd
from pandas_datareader import data, wb

**Comment by Matheusf-Soares** [comment]
> My environment:
> 
> Windows 10 Python 3.7 Anaconda Navigator 1.9.7
> 
> To reproduce the issue:
> 
> 1. Create a new environment in Anaconda
> 2. Install pandas and pandas-datareader
>    conda install -c conda-forge pandas
>    conda install -c conda-forge pandas-datareader
> 
> * I also tried installing using pip instead and got the same error
>   pip install pandas-datareader
> 
> 3. Select the environment and open a terminal
> 4. Run the commands "python" and then "from pandas_datareader import data" on the terminal - it works
> 5. Go back to the terminal and now run "jupyter notebook"
> 6. On the notebook try the same command "from pandas_datareader import data"
>    I got the Error:
>    ModuleNotFoundError                       Traceback (most recent call last)
>     in 
>    ----> 1 from pandas_datareader import data
> 
> ModuleNotFoundError: No module named 'pandas_datareader'

Almost 6 years later and I got the same error, still don't appear to be a solution
