### ISSUE TITLE
Error importing tensorflow

### ISSUE THREAD

**Issue by chisom812** [pydata/pandas-datareader#731]
hello github
i have been having issues importing tensorflow
first i installed the tensorflow==1.31 and i got an error attached below while trying to import tensorflow.
someone suggested i use conda install tensorflow which i did and when trying to import tensorflow my python stops working and my kernel dies.
i was also instructed to upgrade numpy using pip install numpy --upgrade. which i also did. but on trying to import tensorflow again my computer sends a notification of python stops working and kernel dies and restarts again. 
my computer is 4g Ram
please your suggestion will be needed. i am stuck

**Comment by bashtage** [comment]
Wrong repo. You need tensorflow.
