### ISSUE TITLE
MOEX Data Errors

### ISSUE THREAD

**Issue by DennisStoller** [pydata/pandas-datareader#734]
I am getting data errors using pandas_datareader for the Moscow Exchange.  The attached PDF outlines the problem, which seems to have started after changes somewhere around 23 Nov 2019 when different fields started to be returns and the price errors appears.  I am on python 3.7 in the Anaconda distribution's Spyder console.  Prices returned in python do not agree with those shown on the MOEX web site.  This used to work very well until last week.

my python code:

import datetime
import pandas_datareader
sdate = datetime.datetime(2019,10,31)
edate = datetime.datetime.today()
code = 'LSRG'
data = pandas_datareader.DataReader(code, 'moex', start=sdate, end=edate)
print(data[['OPEN', 'HIGH', 'LOW', 'CLOSE']].tail(10))
data[['OPEN', 'HIGH', 'LOW', 'CLOSE']].plot()

output from the console:

TRADEDATE  OPEN    HIGH    LOW   CLOSE
2019-11-18  771.40  926.16  732.8  924.00
2019-11-19  922.32  922.32  731.2  916.80
2019-11-20  913.68  919.44  723.8  919.44
2019-11-21  913.68  913.68  722.8  913.20
2019-11-22  763.40  916.08  725.4  762.00
2019-11-25  767.20  920.64  729.2  764.80
2019-11-26  764.40  917.28  726.0  757.20
2019-11-27  759.80  911.76  722.0  760.60
2019-11-28  907.20  911.76  719.8  911.76
2019-11-29  910.32  910.32  719.4  759.40
￼
![image](https://user-images.githubusercontent.com/33257863/69913199-8cb4d800-142c-11ea-9b1e-7cc084869f34.png)

[MOEX Data Problem.pdf](https://github.com/pydata/pandas-datareader/files/3908118/MOEX.Data.Problem.pdf)

Is this a genuine problem or am I doing something stupid?

**Comment by Whisperes** [comment]
Agreed. API of moex was changed. The output of the  pandas_datareader.DataReader often is empty.

**Comment by DennisStoller** [comment]
For me it is empty sometimes, but not others.

**Comment by addisonlynch** [comment]
cc: @Mottl
