### ISSUE TITLE
econDB ignores session info

### ISSUE THREAD

**Issue by grwoodw** [pydata/pandas-datareader#736]
When using econDB it ignores session info passed to it.
I believe econdb.py line 26:
`results = requests.get(self.url).json()["results"]`
should be:
`results = self.session.get(self.url).json()["results"]`
At least that makes it work for me

**Comment by addisonlynch** [comment]
Thats correct. Thanks...we will repair or PRs are also welcome.

**Comment by grwoodw** [comment]
Done, thank you for your quick response!!

**Comment by grwoodw** [comment]
@addisonlynch, Other than submitting the pull request, is there anything I need to do to get it merged into the master branch?

Thank you!
Greg Woodward
