### ISSUE TITLE
Importing data from NSE

### ISSUE THREAD

**Issue by Amitmoin** [pydata/pandas-datareader#739]
import numpy as np
import pandas as pd
import nsepy as nse
from nsepy import get_history
from datetime import date

NSE=['TCS','INFY']
for x in NSE:
    data=get_history(x,start=date(2019,12,20),end=date(2019,12,20))
after this iam only getting  data for infy only how to import stock data for both

**Comment by Yagniksojitra** [comment]
Data is being received for both stocks, data of TCS is getting overwritten by INFY in "data" variable.

**Comment by bashtage** [comment]
Thanks for answering.
