### ISSUE TITLE
Support new TSP funds in 2020

### ISSUE THREAD

**Issue by walsha2** [pydata/pandas-datareader#740]
Now that it is almost 2020, is work currently being planned to add support for the anticipated new TSP funds? The 2020 fund will be retired and there will be a few new funds added (note they are now 5-year increments)

Reference here for more information: https://www.myfederalretirement.com/5-year-l-fund/

Just trying to put this on the radar so that work is ready as soon as those funds are live and trackable, which I presume to be soon in 2020. If there is no work planned by anyone in particular I can likely take on that task. Doesn't look like it will be difficult at all, just depends on if the tsp.gov API changes. Will probably have to be reactionary to those changes first.

@e2thenegpii you are really the only person on the history log that added any real code. Was this on your radar at all? Committed in 2016 and no functional changes since then... Assuming the code help up that whole time, nice job!

**Comment by e2thenegpii** [comment]
@walsha2 No, this is the first I've heard of this.  I left federal employment years ago and I haven't had any savings with the TSP for some time.

I don't know that there's a lot to do until the funds are implemented.  The TSP adapter posts to a URL and gets back a csv document.  There's not much to do until https://www.tsp.gov/InvestmentFunds/FundPerformance/index.html is updated with the new funds.

I'm glad to hear someone is actually interested in some code I wrote.  I'd be happy to take a look at updating it after tsp.gov has updated their webpage.  If we're lucky it will be a one line change to add the new values to https://github.com/pydata/pandas-datareader/blame/master/pandas_datareader/tsp.py#L32.

If you're interested ping me again when TSP site has been updated with the new L-5 year funds.

**Comment by walsha2** [comment]
Agreed! Ok, ill ping on here again when there is an update on TSP.gov with expected new funds.

**Comment by BryanTheScott** [comment]
For anyone interested, they did update the funds on July 1.  They also released a redesign of the site (I believe) today.

**Comment by walsha2** [comment]
@BryanTheScott the current reader no longer works with the new update. 

A simple solution I threw together can be found below. Feel free to use/star/share/whatever.

Gist URL: https://gist.github.com/walsha2/14718b828e620b942ba6d191f28cd0ef

Raw Code:

```python
import urllib
import pandas as pd

class TSPReader(object):
    """
    A simple Thrift Savings Plan (TSP) share price data reader

    Usage: 

    tsp = TSPReader(start='20200101',end='20200710')
    df = tsp.read()
    """
    def __init__(self,start='', end=''):
        # Construct URL
        self.url = "https://secure.tsp.gov/components/CORS/getSharePrices.html?startdate={0}&enddate={1}&Lfunds=1&InvFunds=1&format=CSV&download=0".format(start,end)

    def read(self):
        """
        Return pandas.DataFrame extracted from HTML table output
        """
        try:
            fp = urllib.request.urlopen(self.url)
        except Exception as e:
            try:
                fp = urllib.request.urlopen(self.url)
            except Exception as e:
                raise e

        mybytes = fp.read()
        html_table_str = mybytes.decode("utf8")
        fp.close()
        return pd.read_html(html_table_str)[0]
```

**Comment by e2thenegpii** [comment]
I updated the TSPReader class, the symbols parameter was changed to update to the new fund names used by the TSP api.

Let me know if you have any issues with the changes.

```git clone https://github.com/e2thenegpii/pandas-datareader.git```
