### ISSUE TITLE
pandas_datareader/yahoo/daily.py should be named differently

### ISSUE THREAD

**Issue by femtotrader** [pydata/pandas-datareader#75]
Hello,

`pandas_datareader/google/daily.py` provide only daily data

but

`pandas_datareader/yahoo/daily.py` use `interval` so it might provide
not only daily data.

```
interval : string, default 'd'
    Time interval code, valid values are 'd' for daily, 'w' for weekly,
    'm' for monthly and 'v' for dividend.
```

So maybe we should name it differently.

Kind regards

**Comment by bashtage** [comment]
Yahoo has been deprecated.
