### ISSUE TITLE
Not able to load stock data from Yahoo in Python (3.7)

### ISSUE THREAD

**Issue by Coo-ckie** [pydata/pandas-datareader#759]
Hi, I am trying to load stock data using pandas_datareader as web, but i am not able to import data in my environment. I get a warning indicating pandas.utils.testing is deprecated, but from what i am reading this should not be the issue. A step-by-step execution reveals the source cannot be loaded. 

I read similar posts on this issue, I checked the version of the package, re-installed it, changed syntax, etc. Nothing worked.  

df = web.data.get_data_yahoo('AAPL',start='2018-01-01',end='2018-01-11')
df.head()

**Comment by zechzhao** [comment]
I guess people cannot help if you don't post your error message nor your import line. `from pandas_datareader import data
start, end = '2018-01-11', '2018-01-11'
aapl = data.DataReader('aapl', start=start,end=end, data_source='yahoo')['Adj Close'])`
should do what you need
