### ISSUE TITLE
Remove Yahoo in _retry_read_url

### ISSUE THREAD

**Issue by femtotrader** [pydata/pandas-datareader#76]
Hi,

I noticed in `utils.py` in `_retry_read_url` this

```
    # Yahoo! Finance sometimes does this awesome thing where they
    # return 2 rows for the most recent business day
    if len(rs) > 2 and rs.index[-1] == rs.index[-2]:  # pragma: no cover
        rs = rs[:-1]
```

as it's Yahoo specific it shouldn't be there.

Kind regards

**Comment by femtotrader** [comment]
That's in https://github.com/pydata/pandas-datareader/blob/master/pandas_datareader/base.py 

    def _read_lines(self, out):
        ...

**Comment by bashtage** [comment]
Yahoo has been deprecated.

**Comment by femtotrader** [comment]
So if it's deprecated is it still required?

https://github.com/pydata/pandas-datareader/blob/c8a087d2f3bbbd07397b93c779f0e1176818567a/pandas_datareader/base.py#L167
