### ISSUE TITLE
Fama-French data starting only in 2015 instead of 1991

### ISSUE THREAD

**Issue by afonsovj** [pydata/pandas-datareader#760]
I was trying to load Developed_5_Factors_Daily Fama-French factors but the df is coming back starting from 2015 instead of 1991 as it is supposed too.

web.DataReader('Developed_5_Factors_Daily', 'famafrench')

**Comment by bashtage** [comment]
Set the start date.

**Comment by bashtage** [comment]
Default start date is 5 years in the past.  Set the date.
