### ISSUE TITLE
Pandas Datareader

### ISSUE THREAD

**Issue by MTM2020** [pydata/pandas-datareader#767]
Hi all-

I'm pretty new to python, but can't seem to find the fix on this one.  
here is my code
import pandas as pd
import pandas_datareader as pdr

This is the error that i receive. Any ideas to import the data reader??
/Users/matt/opt/anaconda3/lib/python3.7/site-packages/pandas_datareader/compat/__init__.py:7: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  from pandas.util.testing import assert_frame_equal

**Comment by Jetsukda** [comment]
Try upgrading the pandas module

**Comment by MTM2020** [comment]
Jetsukda,

Thank you kindly for your reply.  I also found this works.  

import pandas as pd
import datetime
import pandas_datareader.data as web
from pandas import Series, DataFrame

**Comment by bashtage** [comment]
Fixed in master
