### ISSUE TITLE
NotImplementedError: data_source='google' is not implemented

### ISSUE THREAD

**Issue by ashutos-lab** [pydata/pandas-datareader#768]
`from pandas_datareader import data, wb
#from pandas_datareader import data, wb
import pandas as pd
import numpy as np
import datetime
start=datetime.datetime(2006,1,1)
end=datetime.datetime(2016,1,1)
BAC=data.DataReader('BAC','google',start,end)
 print(BAC)`
# Vesion of Pandas_DataReader('0.8.1')

**Comment by Rafaelcvo** [comment]
Hi,
data.DataReader using 'google' was discntinued. Use 'yahoo'.

**Comment by RocqJones** [comment]
> Hi,
> data.DataReader using 'google' was discontinued. Use 'yahoo'.

This worked. Thank you

**Comment by vivekm1972** [comment]
thanks

**Comment by Rishikesh-12** [comment]
### Thank you.

**Comment by nandaniboghara** [comment]
It's work . 
Thank you so much

**Comment by malomodaniels** [comment]
It got solved at the first try, thanks so much!

**Comment by Ivanbox888** [comment]
Thank you!

**Comment by Olarinre** [comment]
WOW! Thanks

**Comment by Ujjal-ENG** [comment]
It worked..thank you so much

**Comment by immartian** [comment]
> data.DataReader using 'google' was discontinued. Use 'yahoo'.

This is what Google does wrong.

**Comment by ikenwaa** [comment]
Thanks a lot for the help. This sounds cliché, but 'yahoo' worked.

**Comment by imduc1011** [comment]
> Hi,
> data.DataReader using 'google' was discontinued. Use 'yahoo'.

it works, thank you so much

**Comment by FiboWang** [comment]
> Hi, data.DataReader using 'google' was discontinued. Use 'yahoo'.

Wow, thank you so much. It really helps me!

**Comment by pechavarria62** [comment]
sorry how do i implement yahoo? cuz im getting an error

**Comment by camrongloudon** [comment]
> sorry how do i implement yahoo? cuz im getting an error

https://pandas-datareader.readthedocs.io/en/latest/remote_data.html#naver-finance-data

Yahoo also is not working. As of now Naver works. 
If it does not work when you are trying, try another provider from the link above.

**Comment by FiboWang** [comment]
Thanks a lot. I will try it latter. Your help means a lot to me.
Best wishes.

从 Windows 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>发送

发件人: ***@***.***>
发送时间: 2023年7月13日 23:43
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [pydata/pandas-datareader] NotImplementedError: data_source='google' is not implemented (#768)


sorry how do i implement yahoo? cuz im getting an error

https://pandas-datareader.readthedocs.io/en/latest/remote_data.html#naver-finance-data

Yahoo also is not working. As of now Naver works.
If it does not work when you are trying, try another provider from the link above.

―
