### ISSUE TITLE
FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.

### ISSUE THREAD

**Issue by fc0712** [pydata/pandas-datareader#775]
```
import pandas as pd 
import pandas_datareader as pdr 
import numpy as np 

```
Reports the following error in the terminal (VS Code)

```
C:\Users\frede\Anaconda3\lib\site-packages\pandas_datareader\compat\__init__.py:7: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  from pandas.util.testing import assert_frame_equal
```

**Comment by marjoscan** [comment]
I have the same problem! I didn´t find solution yet!

**Comment by phantasmKDX** [comment]
same

**Comment by bashtage** [comment]
This is a warning, not an error.

**Comment by saleh-mir** [comment]
Same here. I'm not even using `pandas.util.testing` in my code

**Comment by IloBe** [comment]
same issue without using pandas.util.testing, but only from time to time when the notebook runs (not having changed anything); warnings.filterwarnings("ignore") is set

**Comment by amber1rn14is015** [comment]
I had the same issue. Resolved it.

Just  open in editor
C:\Users\Amber\AppData\Local\Programs\Python\Python37\Lib\site-packages\pandas_datareader\compat\__init__.py

Replace:

`from pandas.util.testing import assert_frame_equal`

with

`from pandas.testing import assert_frame_equal`

**Comment by bashtage** [comment]
Fixed

**Comment by dhruv-vavliya** [comment]
from pandas.util.testing import assert_frame_equal

replace to

from pandas.testing import assert_frame_equal

**Comment by bashtage** [comment]
Fixed in the most recent release so upgrade.

**Comment by XingyanCao** [comment]
import 
pandas._testing
as tm;

**Comment by syjgino** [comment]
> 

For anaconda, the file is 
C:\Users\xxx\Anaconda3\envs\xxx\lib\site-packages\statsmodels\tools\_testing.py

**Comment by mainguyenanhvu** [comment]
I would like to know which version of pandas containing pandas.util.testing? Please help me because I cannot edit the system code, therefore, I only install packages suitable for it.

Thank you very much.

**Comment by gauravdce07** [comment]
In my case there was no such "from pandas.util.testing" in any of the .py files in pandas instillation directory.
Instead what worked for me was to run "pip install --upgrade pandas" in spyder console.
