### ISSUE TITLE
Options Import From Yahoo on DataReader

### ISSUE THREAD

**Issue by holger6311** [pydata/pandas-datareader#776]
from pandas_datareader.data import Options
fb_options = Options('FB', 'yahoo')

ImmediateDeprecationError                 Traceback (most recent call last)
<ipython-input-10-ebb245969de8> in <module>
      1 from pandas_datareader.data import Options
      2 
----> 3 fb_options = Options('FB', 'yahoo')

~\AppData\Local\Continuum\anaconda3\envs\pyfinance\lib\site-packages\pandas_datareader\data.py in Options(symbol, data_source, session)
    677         data_source = "yahoo"
    678     if data_source == "yahoo":
--> 679         raise ImmediateDeprecationError(DEP_ERROR_MSG.format("Yahoo Options"))
    680         return YahooOptions(symbol, session=session)
    681     else:

ImmediateDeprecationError: 
Yahoo Options has been immediately deprecated due to large breaks in the API without the
introduction of a stable replacement. Pull Requests to re-enable these data
connectors are welcome.

**Comment by sebastian021** [comment]
i have this problem and about one week wasted my time to search but nothing had found, at first i wanted to use google but didn't work and i couldnt find anything. someone answer pls, is google API closed? and how we solve this yahoo problem?

**Comment by alecosta80** [comment]
same issue

**Comment by ajayv777** [comment]
I'm facing the same issue.
