### ISSUE TITLE
Removed

### ISSUE THREAD

**Issue by ashita03** [pydata/pandas-datareader#784]
I’ve been trying to code using Jupiter Notebook by launching it using Anaconda but when I use “import pandas_datareader as web”; it shows this particular error. I’m new to this, hence would like some help

**Comment by bashtage** [comment]
Please edit the title and message

**Comment by ashita03** [comment]
> Please edit the title and message

I’m sorry I’m new to this

**Comment by bashtage** [comment]
Click edit next to the title and change the text.
