### ISSUE TITLE
1. Create a new Python 3.7 virtual env

### ISSUE THREAD

**Issue by Ouchhh** [pydata/pandas-datareader#786]
Hello! Please help! I am a newbie.
I tried installing this and got the error below that:
pip install pip --upgrade
pip install pandas-datareader

 File "<ipython-input-7-1054467a3e8d>", line 1
    pip install pip --upgrade
              ^
SyntaxError: invalid syntax

**Comment by nbr23** [comment]
Hi,
These lines:
```
pip install pip --upgrade
pip install pandas-datareader
```
Are to be written in your terminal, not in the python interpreter. They are operating system commands, not python syntax.
