### ISSUE TITLE
Import error for pandas_datareader

### ISSUE THREAD

**Issue by AnupamSaraph** [pydata/pandas-datareader#787]
import pandas_datareader results in the following error:

> ImportError                               Traceback (most recent call last) in 
> ----> 1 import pandas_datareader
> 
> C:\ProgramData\Anaconda3\lib\site-packages\pandas_datareader\__init__.py in 
>       1 from ._version import get_versions
> ----> 2 from .data import (DataReader, Options, get_components_yahoo,
>       3                    get_dailysummary_iex, get_data_enigma, get_data_famafrench,
>       4                    get_data_fred, get_data_google, get_data_moex,
>       5                    get_data_morningstar, get_data_quandl, get_data_stooq,
> 
> C:\ProgramData\Anaconda3\lib\site-packages\pandas_datareader\data.py in 
>       5 import warnings
>       6 
> ----> 7 from pandas_datareader.av.forex import AVForexReader
>       8 from pandas_datareader.av.quotes import AVQuotesReader
>       9 from pandas_datareader.av.sector import AVSectorPerformanceReader
> 
> C:\ProgramData\Anaconda3\lib\site-packages\pandas_datareader\av\__init__.py in 
>       1 import os
>       2 
> ----> 3 from pandas_datareader.base import _BaseReader
>       4 from pandas_datareader._utils import RemoteDataError
>       5 
> 
> C:\ProgramData\Anaconda3\lib\site-packages\pandas_datareader\base.py in 
>       9 from pandas import read_csv, concat
>      10 from pandas.io.common import urlencode
> ---> 11 from pandas.compat import StringIO, bytes_to_str
>      12 
>      13 from pandas_datareader._utils import (RemoteDataError, SymbolWarning,
> 
> ImportError: cannot import name 'StringIO' from 'pandas.compat' (C:\ProgramData\Anaconda3\lib\site-packages\pandas\compat\__init__.py)
>

**Comment by tmnewt** [comment]
This issue has been addressed elsewhere. https://github.com/pydata/pandas-datareader/issues/655#issuecomment-529322341

`pip install pandas-datareader --upgrade` should fix it.
