### ISSUE TITLE
World bank api not working

### ISSUE THREAD

**Issue by zwali-sl** [pydata/pandas-datareader#791]
I am using below code and it was working on Friday.

from pandas_datareader import wb
results = wb.search('NY.GDP.MKTP.CD')

Today I am getting this error about certificate in connection.

 | 2020-06-22T15:08:09.839+01:00 | [ERROR]	2020-06-22T14:08:09.817Z	50c5b612-af4e-42a8-a234-583b883463e6	HTTPSConnectionPool(host='api.worldbank.org', port=443): Max retries exceeded with url: /v2/indicators?per_page=50000&format=json (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076)')))
  | 2020-06-22T15:08:09.839+01:00 | Traceback (most recent call last):
  | 2020-06-22T15:08:09.839+01:00 | File "/opt/python/lib/python3.7/site-packages/urllib3/connectionpool.py", line 677, in urlopen
  | 2020-06-22T15:08:09.839+01:00 | chunked=chunked,
  | 2020-06-22T15:08:09.839+01:00 | File "/opt/python/lib/python3.7/site-packages/urllib3/connectionpool.py", line 381, in _make_request
  | 2020-06-22T15:08:09.839+01:00 | self._validate_conn(conn)
  | 2020-06-22T15:08:09.839+01:00 | File "/opt/python/lib/python3.7/site-packages/urllib3/connectionpool.py", line 976, in _validate_conn
  | 2020-06-22T15:08:09.839+01:00 | conn.connect()
  | 2020-06-22T15:08:09.839+01:00 | File "/opt/python/lib/python3.7/site-packages/urllib3/connection.py", line 370, in connect
  | 2020-06-22T15:08:09.839+01:00 | ssl_context=context,
  | 2020-06-22T15:08:09.839+01:00 | File "/opt/python/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 377, in ssl_wrap_socket
  | 2020-06-22T15:08:09.839+01:00 | return context.wrap_socket(sock, server_hostname=server_hostname)
  | 2020-06-22T15:08:09.839+01:00 | File "/var/lang/lib/python3.7/ssl.py", line 423, in wrap_socket
  | 2020-06-22T15:08:09.839+01:00 | session=session
  | 2020-06-22T15:08:09.839+01:00 | File "/var/lang/lib/python3.7/ssl.py", line 870, in _create
  | 2020-06-22T15:08:09.839+01:00 | self.do_handshake()
  | 2020-06-22T15:08:09.839+01:00 | File "/var/lang/lib/python3.7/ssl.py", line 1139, in do_handshake
  | 2020-06-22T15:08:09.839+01:00 | self._sslobj.do_handshake()
  | 2020-06-22T15:08:09.839+01:00 | ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076)
  | 2020-06-22T15:08:09.839+01:00 | During handling of the above exception, another exception occurred:
  | 2020-06-22T15:08:09.839+01:00 | Traceback (most recent call last):
  | 2020-06-22T15:08:09.839+01:00 | File "/opt/python/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
  | 2020-06-22T15:08:09.839+01:00 | timeout=timeout
  | 2020-06-22T15:08:09.839+01:00 | File "/opt/python/lib/python3.7/site-packages/urllib3/connectionpool.py", line 725, in urlopen
  | 2020-06-22T15:08:09.839+01:00 | method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  | 2020-06-22T15:08:09.839+01:00 | File "/opt/python/lib/python3.7/site-packages/urllib3/util/retry.py", line 439, in increment
  | 2020-06-22T15:08:09.839+01:00 | raise MaxRetryError(_pool, url, error or ResponseError(cause))
  | 2020-06-22T15:08:09.839+01:00 | urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.worldbank.org', port=443): Max retries exceeded with url: /v2/indicators?per_page=50000&format=json (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076)')))
  | 2020-06-22T15:08:09.839+01:00 | During handling of the above exception, another exception occurred:
  | 2020-06-22T15:08:09.839+01:00 | Traceback (most recent call last):
  | 2020-06-22T15:08:09.839+01:00 | File "/var/task/lambda_function.py", line 20, in lambda_handler
  | 2020-06-22T15:08:09.839+01:00 | results = wb.search('NY.GDP.MKTP.CD')
  | 2020-06-22T15:08:09.839+01:00 | File "/opt/python/lib/python3.7/site-packages/pandas_datareader/wb.py", line 938, in search
  | 2020-06-22T15:08:09.839+01:00 | return WorldBankReader(**kwargs).search(string=string, field=field, case=case)
  | 2020-06-22T15:08:09.839+01:00 | File "/opt/python/lib/python3.7/site-packages/pandas_datareader/wb.py", line 809, in search
  | 2020-06-22T15:08:09.839+01:00 | indicators = self.get_indicators()
  | 2020-06-22T15:08:09.839+01:00 | File "/opt/python/lib/python3.7/site-packages/pandas_datareader/wb.py", line 745, in get_indicators
  | 2020-06-22T15:08:09.839+01:00 | resp = self._get_response(url)
  | 2020-06-22T15:08:09.839+01:00 | File "/opt/python/lib/python3.7/site-packages/pandas_datareader/base.py", line 155, in _get_response
  | 2020-06-22T15:08:09.839+01:00 | response = self.session.get(url, params=params, headers=headers)
  | 2020-06-22T15:08:09.839+01:00 | File "/opt/python/lib/python3.7/site-packages/requests/sessions.py", line 543, in get
  | 2020-06-22T15:08:09.839+01:00 | return self.request('GET', url, **kwargs)
  | 2020-06-22T15:08:09.839+01:00 | File "/opt/python/lib/python3.7/site-packages/requests/sessions.py", line 530, in request
  | 2020-06-22T15:08:09.839+01:00 | resp = self.send(prep, **send_kwargs)
  | 2020-06-22T15:08:09.839+01:00 | File "/opt/python/lib/python3.7/site-packages/requests/sessions.py", line 643, in send
  | 2020-06-22T15:08:09.839+01:00 | r = adapter.send(request, **kwargs)
  | 2020-06-22T15:08:09.839+01:00 | File "/opt/python/lib/python3.7/site-packages/requests/adapters.py", line 514, in send
  | 2020-06-22T15:08:09.839+01:00 | raise SSLError(e, request=request)
  | 2020-06-22T15:08:09.839+01:00 | requests.exceptions.SSLError: HTTPSConnectionPool(host='api.worldbank.org', port=443): Max retries exceeded with url: /v2/indicators?per_page=50000&format=json (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1076)')))
  | 2020-06-22T15:08:09.879+01:00 | END RequestId: 50c5b612-af4e-42a8-a234-583b883463e6
 

World bank updated their API certificates on the 18th. That might be causing the break.

**Comment by tokenflow** [comment]
@zwali-sl   Same my issue starting from yesterday night, does it related to wb api new limitation, or ssl issue?

requests.exceptions.SSLError: HTTPSConnectionPool(host='api.worldbank.org', port=443): Max retries exceeded with url: /v2/countries/IND;CHN;SOM;POL;DNK;KAZ;SYR;AGO;TWN;IRL;PHL;AZE;UGA;ROU;SUR;DJI;ETH/indicators/AG.LND.ARBL.ZS?date=2011%3A2016&per_page=25000&format=json (Caused by SSLError(SSLError("bad handshake: Error([('SSL routines', 'tls_process_server_certificate', 'certificate verify failed')],)",),

**Comment by najuzilu** [comment]
I suspect it must have been a WB issue because `wb.download` is now working.

**Comment by zwali-sl** [comment]
Whatever the reason was, it is gone now. Search is working again.
