### ISSUE TITLE
Link to Quandl free dbs is not correct, it should be changed to the following

### ISSUE THREAD

**Issue by nondescript74** [pydata/pandas-datareader#794]
Link to free dbs on Quandl should be changed.

On this page:  https://github.com/pydata/pandas-datareader/blob/master/docs/source/remote_data.rst, the section on Quandl has url: https://blog.quandl.com/free-data-on-quandl, as the location to access free data.  **This is not correct.**  

The correct url for Quandl free dbs is currently at https://www.quandl.com/search?filters=%5B%22Free%22%5D

**Comment by bashtage** [comment]
Fixed in master
