### ISSUE TITLE
Idea - Import and export support for DataPackages

### ISSUE THREAD

**Issue by noelmas** [pydata/pandas-datareader#80]
[DataPackages](http://data.okfn.org/doc/data-package) is a project that offers a standardized and extensible way of packaging up data. There is already a growing community around Data Packages and an increasing number of core datasets which can easily be grabbed from a URL.

It would be great to see easy import and export to and from a Tabular Data Package - see spec here - into a Pandas DataFrame (e.g. pd.from_datapackage(...) & pd.to_datapackage(...)).

Moved from main Pandas repot to here on advice of @TomAugspurger

**Comment by femtotrader** [comment]
That's a very interesting idea

Some sample package can be found here
https://github.com/datasets/

Some code can be found here
https://github.com/okfn/dptools/blob/master/bin/load-postgresql.py
https://github.com/okfn/dptools/blob/master/bin/load-sqlite.py
https://github.com/trickvi/datapackage

**Comment by femtotrader** [comment]
Not a lot of luck with `trickvi/datapackage`

  In [1]: import datapackage

  In [2]: datapkg = datapackage.DataPackage('http://data.okfn.org/data/cpi/')
  ---------------------------------------------------------------------------
  TypeError                                 Traceback (most recent call last)
  <ipython-input-2-21b6afb5084e> in <module>()
  ----> 1 datapkg = datapackage.DataPackage('http://data.okfn.org/data/cpi/')

  //anaconda/lib/python3.4/site-packages/datapackage/datapackage.py in __init__(self, *args, **kwargs)
      100         elif len(args) == 1:
      101             self.base = args[0]
  --> 102             descriptor = self.get_descriptor()
      103             super(DataPackage, self).__init__(**descriptor)
      104         else:

  //anaconda/lib/python3.4/site-packages/datapackage/datapackage.py in get_descriptor(self)
      588         # Load the descriptor json contents
      589         str_descriptor = descriptor.read()
  --> 590         json_descriptor = json.loads(str_descriptor)
      591
      592         # Return the descriptor json contents (as the dict json.load returns

  //anaconda/lib/python3.4/json/__init__.py in loads(s, encoding, cls, object_hook, parse_float, parse_int, parse_constant, object_pairs_hook, **kw)
      310     if not isinstance(s, str):
      311         raise TypeError('the JSON object must be str, not {!r}'.format(
  --> 312                             s.__class__.__name__))
      313     if s.startswith(u'\ufeff'):
      314         raise ValueError("Unexpected UTF-8 BOM (decode using utf-8-sig)")

  TypeError: the JSON object must be str, not 'bytes'

**Comment by noelmas** [comment]
Sorry to hear that @femtotrader - can you post this issue in https://discuss.okfn.org/c/open-knowledge-labs/data-packages ? someone will sort it for you ASAP

**Comment by femtotrader** [comment]
I'm trying to signup with GitHub and get

> Sorry, there was an error authorizing your account. Perhaps you did not approve authorization?

**Comment by femtotrader** [comment]
https://github.com/trickvi/datapackage/issues/44

**Comment by femtotrader** [comment]
odo might be considered https://github.com/trickvi/datapackage/issues/45

**Comment by trickvi** [comment]
@femtotrader I will have a look at this on my and and try to be of as much assistance as I can (both issues). Thanks for reporting. I will keep you updated here in this issue as well.

**Comment by femtotrader** [comment]
trickvi/datapackage is now fixed for Python 3.

It's possible to do


    >> import datapackage
    >>
    >> # Note trailing slash is important for data.okfn.org
    >> datapkg = datapackage.DataPackage('http://data.okfn.org/data/cpi/')
    >>
    >> print(datapkg.title)
    Annual Consumer Price Index (CPI)
    >> print datapkg.description
    Annual Consumer Price Index (CPI) for most countries in the world. Reference year is 2005.
    >> # Weird example just to show how to work with data rows
    >> print(sum([row['CPI'] for row in datapkg.data]))
    405442.60078415077

so converting to a DataFrame can be done using


    df = pd.DataFrame(list(datapkg.data))

but that's probably quite long when processing very long table.

Maybe a method should be add to convert to DataFrame when Pandas is installed

it's now possible to do

    >> df['CPI'].sum()
    405442.60078415077

**Comment by femtotrader** [comment]
A new Python DataPackage client is available at https://github.com/datapackages/datapackage-py

**Comment by danfowler** [comment]
New Python Data Package client: https://github.com/frictionlessdata/datapackage-py 

There is also a plugin for reading Tabular Data Package resources into Pandas data frames: https://github.com/frictionlessdata/jsontableschema-pandas-py

**Comment by bashtage** [comment]
Seems unnecessary given other packages.
