### ISSUE TITLE
Odd test variations based on download source

### ISSUE THREAD

**Issue by sambler** [pydata/pandas-datareader#806]
When 0.9.0 was released I saw some extra test failures compared to rc1. I have since found that the test results from github tag of 0.9.0 are different than the 0.9.0 release available from pypi.

Comparing the tarball from github and pypi, I see `setup.cfg` varies in formatting (spaces/tabs), while `_version.py` has >500 lines different. As the shorter `_version.py` should be output from the repo script, I don't expect either should cause variations in tests.

This is running on FreeBSD 12.1 amd64

[0.9.0-github](http://shaneware.biz/freebsddebugdata/pandas-datareader/pandas-datareader-0.9.0-github.txt)
1 failed, 113 passed, 56 skipped, 3 xfailed, 1 xpassed

[0.9.0-pypi](http://shaneware.biz/freebsddebugdata/pandas-datareader/pandas-datareader-0.9.0-pypi.txt)
1 failed, 109 passed, 56 skipped, 3 xfailed, 1 xpassed, 1 warnings, 4 error

**Comment by bashtage** [comment]
Which tests specifically fail?

**Comment by sambler** [comment]
the two links are log files of the test output.

**Comment by bashtage** [comment]
Seems to be something to do with the [pandas](https://github.com/pandas-dev/pandas/pull/22701) and/or [pytest](https://github.com/pytest-dev/pytest/issues/3692) you are using. There is no version information available for installed packages in the log.

**Comment by sambler** [comment]
pandas-0.24.2 - pytest 4.5.0 so both ports need updating.

But besides the updates, how can the 0.9.0 tarball from github and 0.9.0 from pypi give different results when they are using the same modules?

Between the two tests the pandas-datareader source tarball is the only changing factor.
Do you get the same results from both tarballs? or is it just me?

**Comment by bashtage** [comment]
What is the syntax fo the pytest command is used to involke the test?

**Comment by sambler** [comment]
The cmd used with the logs is `cd $WRKSRC && python3.7 -m pytest pandas_datareader/tests`

**Comment by bashtage** [comment]
And what is $WRKSRC?

**Comment by bashtage** [comment]
I have found the issue; it won't be fixed until 0.9.1.
