### ISSUE TITLE
MOEX: Replace data from all boards to the data from the main board

### ISSUE THREAD

**Issue by GreenArt11** [pydata/pandas-datareader#811]
Loading data for Moscow exchange returns info from all of the boards and trading modes. 
```
import pandas_datareader as pdr
pdr.DataReader('sber', 'moex', '2020-07-02', '2020-07-02')
```
The code returns 9 rows for each board (trading mode) for the same date. 
It seems to be better if pdr could return data from the main board only (for each ticker). It would lead to less misunderstanding the results.

I also would like to try this as my first PR

**Comment by bashtage** [comment]
This doesn't close it. You need to submit a PR to this repo.

**Comment by GreenArt11** [comment]
> This doesn't close it. You need to submit a PR to this repo.

Yes, sorry, my bad. It is my first PR and I didn't know that merging branches in an origin repo with completed text about closing an issue also closes it this issue in an upstream issues list. 
Thank you for reopening the issue.

**Comment by GreenArt11** [comment]
Hi! Is there any information about when will new version be released?
