### ISSUE TITLE
Simple question about documentation

### ISSUE THREAD

**Issue by Psychotechnopath** [pydata/pandas-datareader#817]
Why isn't the yahoo finance API listed in the Data Readers [list](https://pandas-datareader.readthedocs.io/en/latest/readers/index.html), but it is available as get_data_yahoo()? Will the get_data_yahoo() function be deprecated in future versions?

**Comment by bashtage** [comment]
It should be. I think it was never readded after it was removed when it stopped working.  PR welcome.

**Comment by lukashalim** [comment]
First time contributor here. I submitted a merge request.

**Comment by Psychotechnopath** [comment]
I believe it still does not show; check this link: https://pandas-datareader.readthedocs.io/en/latest/readers/index.html
