### ISSUE TITLE
DataReader fails with change of the order of stocks

### ISSUE THREAD

**Issue by TraderMikeS** [pydata/pandas-datareader#829]
I run Webreader with a list of stocks. If I change the order of the symbols in the list, the Webreader fails. The two lists below are identical except I moved some stocks from the bottom of the list to the top.

The first symbols list works okay. The second symbols list failed to read symbols NVDA, LULU ad TAL, replacing with NaN warnings.
start = '2020-04-06'
end = '2020-09-02'
symbols = [] ## see below
web.DataReader(symbols,'yahoo',start,end)

## Symbols list 1##
symbols = [
'NVDA',
'FTNT',
'LULU',
'TAL',
'SEDG',
'PDD',
'TME',
'SQ',
'SHOP',
'CHWY',
'DDOG',
'TTD',
'INMD',
'LVGO',
'GSX',
'CODX',
'DOCU',
'ZM',
'TDOC',
'TEAM',
'NFLX',
'RNG',
'DXCM',
'PAYC',
'CRWD',
'WDAY',
'NOW',
'DBX',
'BABA',
'CARG',
'FND',
'XP',
'ALGN',
'MLNX',
'JD',
'REGN',
'PLMR',
'EDU',
'VEEV',
'AMZN'
]

##Symbols List 2##
symbols = [
 'SEDG',
 'PDD',
 'TME',
 'SQ',
 'SHOP',
 'CHWY',
 'DDOG',
 'TTD',
 'INMD',
 'LVGO',
 'GSX',
 'CODX',
 'DOCU',
 'ZM',
 'TDOC',
 'TEAM',
 'NFLX',
 'RNG',
 'DXCM',
 'PAYC',
 'CRWD',
 'WDAY',
 'NOW',
 'DBX',
 'BABA',
 'CARG',
 'FND',
 'XP',
 'ALGN',
 'MLNX',
 'JD',
 'REGN',
 'PLMR',
 'EDU',
 'VEEV',
 'AMZN',
 'NVDA',
 'FTNT',
 'LULU',
 'TAL'
 ]

Mike Scott

**Comment by datatalking** [comment]
@TraderMikeS What is the use case or reason that you need to change the order of the symbols in the list?

**Comment by TraderMikeS** [comment]
Andrew,
I don't need to change the order. I just need the data reader to work on any arbitrary list of legal symbols. I am trying to point out that the data reader fails with one list that is a re-ordered list that does work.

Mike

Mike Scott
Cloverdale, CA
On 7/17/2021 2:40:39 PM, Andrew Schell ***@***.***> wrote:
@TraderMikeS [https://github.com/TraderMikeS] What is the use case or reason that you need to change the order of the symbols in the list?

**Comment by bashtage** [comment]
Working as expected in 0.10.0
