### ISSUE TITLE
issue with pandas_datareader

### ISSUE THREAD

**Issue by Daurija** [pydata/pandas-datareader#831]
Hi, can someone help with this error:  **No data fetched using 'YahooDailyReader**'
It worked perfectly yesterday, however, today while importing data from Yahoo it shows an error.

**Comment by Athe-kunal** [comment]
Do we need to install a yahoo API to get the financial data?
Or you just did 
df = web.DataReader(symbol,'yahoo',start,end)

**Comment by Daurija** [comment]
I did it the following way, it has been always working, except today:

stocks = ['AMD','AMZN','^BCOM','BNDX','DX-Y.NYB','FEZ','GLD','GVDNY','IGOV','LQD','^MID','NILSY','NVDA','^RUT','TCEHY']
start = dt.datetime(2019, 6, 1)
end = dt.datetime(2020, 6, 1)
data = web.DataReader(stocks,data_source='yahoo',start=start, end= end)['Adj Close']

Really appreciate Your help.

**Comment by bashtage** [comment]
Working as expected now.
