### ISSUE TITLE
Any idea to download the historical gold data(daily)?

### ISSUE THREAD

**Issue by pivdets** [pydata/pandas-datareader#842]
Hi all,

After doing some research, I found there're several ways to download today's gold price, such as:

- https://forex-data-feed.swissquote.com/public-quotes/bboquotes/instrument/XAU/USD
- https://www.alphavantage.co/query?function=CURRENCY_EXCHANGE_RATE&from_currency=XAU&to_currency=USD&apikey=XXX
- https://www.goldapi.io/api/XAU/USD (Should set the `x-access-token` header)

However, it seems that it's hard to download the historical gold data, like, from 1970.

I was wondering if anyone have some hints on this?

**Comment by simaki** [comment]
FRED provides daily gold price from 1968-04-01 to today. Please see [here](https://fred.stlouisfed.org/categories/32217?t=daily%3Bgold%3Bprice).

An example code to fetch it is as follows.
```py
import pandas_datareader

pandas_datareader.DataReader("GOLDAMGBD228NLBM", data_source="fred", start="19000101")
```

**Comment by matsuobasho** [comment]
This no longer works.   I get the following error:
`No data found for this date range, symbol may be delisted`
