### ISSUE TITLE
ModuleNotFoundError: No module named 'pandas_datareader'

### ISSUE THREAD

**Issue by EmadElDinH** [pydata/pandas-datareader#849]
I'm using win10 & python ver. 3.8.7, 64 bit
Although I successfully installed the pandas_datareader module on my virtual environment through the cmd screen using the command:
                   pip install pandas_datareader
I always get the the error:
                    ModuleNotFoundError: No module named 'pandas_datareader'
when I try to import it in python
![image](https://user-images.githubusercontent.com/79036528/107997872-876d8a00-6fec-11eb-98b3-f775938626c7.png)
can you please help!

**Comment by Benjeet-Randhawa** [comment]
Having the same issue. Hopefully it gets resolved quickly.

**Comment by linehammer** [comment]
In most cases this error in Python generally raised:

- You haven't installed Pandas explicitly with pip [install pandas](http://net-informations.com/ds/err/pderr.htm).
- You may have different Python versions on your computer and Pandas is not installed for the particular version you're using.

You can run the following command in your Linux/MacOS/Windows terminal.

`pip install pandas`

To be sure you are not having multiple Python versions that are confusing, you should run following commands:

```
python3 -m pip install pandas
python3 -c 'import pandas'
```
