### ISSUE TITLE
ERROR - JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by BajajAryan310** [pydata/pandas-datareader#872]
I am using the Code:

```
import yfinance as yf
Infosys = yf.Ticker("INFY.BO")
print(Infosys.info.keys())
```
 
Till here I am getting an output. But I am getting an error in the below-mentioned code:

`Infosys.history(period="5mo")
`

Error:

`JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

I am unable to understand it, please help!!

**Comment by gho21** [comment]
I got the same :-(

**Comment by ericsnth** [comment]
#868

**Comment by maxmekiska** [comment]
> I am using the Code:
> 
> ```
> import yfinance as yf
> Infosys = yf.Ticker("INFY.BO")
> print(Infosys.info.keys())
> ```
> 
> Till here I am getting an output. But I am getting an error in the below-mentioned code:
> 
> `Infosys.history(period="5mo") `
> 
> Error:
> 
> `JSONDecodeError: Expecting value: line 1 column 1 (char 0)`
> 
> I am unable to understand it, please help!!


Hey,
Upgrade your yfinance version. It worked for me after that. 

```shell
pip install yfinance --upgrade
```

**Comment by LinuxpowerLudo** [comment]
Same error with python 3.8 and 0.1.63 ... :( simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by andrewdoni** [comment]
same error, but when i deploy my app on heroku its not get error (simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0). I don't know why its different

**Comment by bashtage** [comment]
Consolidating to #867.

**Comment by flutterq2** [comment]
[[Already Solved] JSONDecodeError: Expecting value: line 1 column 1 (char 0) yFinance](https://exerror.com/jsondecodeerror-expecting-value-line-1-column-1-char-0-yfinance/)
