### ISSUE TITLE
get_data_yahoo raise RemoteDataError(msg)!

### ISSUE THREAD

**Issue by waynelee123** [pydata/pandas-datareader#874]
import pandas_datareader as pdr
start=datetime(2019,1,1)
nio=pdr.get_data_yahoo('NIO',start=start)

error：
raise RemoteDataError(msg)
pandas_datareader._utils.RemoteDataError: Unable to read URL: https://finance.yahoo.com/quote/NIO/history?period1=1546333200&period2=1625990399&interval=1d&frequency=1d&filter=history
Response Text:

**Comment by ashkreee** [comment]
Now I'm also getting same issue, pls anyone help us

**Comment by waynelee123** [comment]
Use the following will work:

import pandas_datareader as pdr

import yfinance as yf
yf.pdr_override()

pdr.data.get_data_yahoo('NIO',start='2019-01-01')


Sent from my iPhone

On Jul 11, 2021, at 10:42 AM, ashkreee ***@***.***> wrote:

﻿

Now I'm also getting same issue, pls anyone help us

**Comment by bashtage** [comment]
Consolidating to #867.
