### ISSUE TITLE
Pandas options data not working

### ISSUE THREAD

**Issue by MathTinker** [pydata/pandas-datareader#88]
I am trying to use get_all_data() method to download options data. I am getting following error:
RemoteDataError: Parsed URL 'http://finance.yahoo.com/q/op?s=SPY' has no rootelement
Actual code:
from pandas.io.data import Options
SPYD = Options('spy', 'yahoo')
data = SPYD.get_all_data()

My pandas version is 0.16.2

**Comment by davidastephens** [comment]
Try installing pandas-datareader:
```
pip install pandas-datareader
```
Then use the pandas_datareader version of Options
```
from pandas_datareader.data import Options
SPYD = Options('spy', 'yahoo')
data = SPYD.get_all_data()
```
