### ISSUE TITLE
Fix formatting of description on PyPI

### ISSUE THREAD

**Issue by impredicative** [pydata/pandas-datareader#891]
The [package description on PyPI](https://pypi.org/project/pandas-datareader/#description) is misformatted. It was [previously formatted correctly](https://pypi.org/project/pandas-datareader/0.9.0/) for v0.9.0 of the package.

**Comment by impredicative** [comment]
LOL. It takes a special talent to close a bug without fully resolving it. I am looking at the PyPI page and it's still broken. And no, I don't think this bug should've been closed without a release, otherwise anything is possible.

**Comment by bashtage** [comment]
It won't appear on PyPI until the next release.  The underlying cause was corrected. There is not code change needed, and so the bug is gone.
