### ISSUE TITLE
Fails to Run on Google Collab

### ISSUE THREAD

**Issue by SanJacintoJoe** [pydata/pandas-datareader#892]
I've tried to run the following on google collab.  Note the code runs fine on my Pycharm IDE

`import pandas_datareader.data as web
import pandas as pd
import datetime as dt
import numpy as np
import matplotlib.pyplot as plt
from matplotlib import style

style.use('ggplot')

start = dt.datetime(2017, 1, 3)
end = dt.datetime(2017, 11, 20)
prices = web.DataReader('AAPL', 'yahoo', start, end)['Close']
`
Here's the traceback
`
KeyboardInterrupt                         Traceback (most recent call last)

<ipython-input-45-b76722b62ca8> in <module>()
     14 end = dt.datetime(2017, 11, 20)
     15 
---> 16 prices = web.DataReader('AAPL', 'yahoo', start, end)['Close']
     17 
     18 returns = prices.pct_change()

/usr/local/lib/python3.7/dist-packages/yfinance/multi.py in download(tickers, start, end, actions, threads, group_by, auto_adjust, back_adjust, progress, period, show_errors, interval, prepost, proxy, rounding, **kwargs)
     95                                    rounding=rounding)
     96         while len(shared._DFS) < len(tickers):
---> 97             _time.sleep(0.01)
     98 
     99     # download synchronously
`

**Comment by bashtage** [comment]
You need to make sure pdr has been updated on colab. Something like

```
!pip install pandas-datareader --upgrade
```

**Comment by SanJacintoJoe** [comment]
I tried upgrading. Still fails. I'm getting: ValueError: time data 'yahoo' does not match format '%Y-%m-%d' Which does not make sense to me because I specifically converted date value to date format and also tried entering date as  start='2019-09-10', end='2019-10-09' in the method.

**Comment by bashtage** [comment]
Try uninstalling twice then install once. You should post the full traceback.  It is possible you have other dependencies that have not been upgraded.

**Comment by bashtage** [comment]
Works as expected in a fresh colab.

![image](https://user-images.githubusercontent.com/5585221/126352710-62151bed-92e7-4bb1-8de9-894d4a50f346.png)

**Comment by SanJacintoJoe** [comment]
Ok. I tried your suggestion about uninstalling and re-installing the library.  Didn't work. Here's the full traceback. I'm surprise it worked on new collab. 

![image](https://user-images.githubusercontent.com/61699075/126353806-b8fbe009-da35-444b-ae3d-28584daa3780.png)

**Comment by bashtage** [comment]
Can you use a new colab and do exactly what I have above?  You need to be using Python 3.7+

**Comment by bashtage** [comment]
You are using yfinance, not pandas-datareader. Please ask yfinance questions on the yfinance repo.

**Comment by bashtage** [comment]
To be clear, there is no pandas-datareader in your traceback.

**Comment by SanJacintoJoe** [comment]
I don't understand I'm not importing yfinance. Also, I tried a new collab instance. 
![image](https://user-images.githubusercontent.com/61699075/126357240-b70f11ad-b23c-4851-8052-17a27de1961e.png)

Same issue

**Comment by bashtage** [comment]
Your previous traceback was clearly from yfinance.

This traceback suggests you are not using 0.10.0.

What does

```python
import pandas_datareader as pdr
print(pdf.__version__)
```

return?

**Comment by SanJacintoJoe** [comment]
version 0.9.0

**Comment by bashtage** [comment]
Like I showed in my screenshot, you have to upgrade to 0.10.0.

**Comment by SanJacintoJoe** [comment]
Upgrades version and restarting Runtime resolved the issue. Thanks!!
