### ISSUE TITLE
Question regarding installing and importing

### ISSUE THREAD

**Issue by ZhiliWang** [pydata/pandas-datareader#901]
Hello. This is a great project! I am just wondering what part of your code is enabling you to install and import the package with 2 different names (using "import pandas_datareader" to avoid the syntax error). I did some research about packaging project but still not quite getting it. Thank you!

**Comment by bashtage** [comment]
The package name hyphen is automatically converted to underscore in Pypi. The key reason why the underscore works is the directory structure which uses an underscore.

**Comment by bashtage** [comment]
Closing since no action. Feel free to post if that isn't clear.
