### ISSUE TITLE
 pandas-datareader package is not installing

### ISSUE THREAD

**Issue by ishikkkkaaaa** [pydata/pandas-datareader#902]
i have been trying to install the pandas-datareader package, but its showing this -

`(base) Ishikas-MacBook-Air:Stock-Ticker-Dashboard ishikakesarwani$ conda install pandas_datareader
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
PackagesNotFoundError: The following packages are not available from current channels:
pandas_datareader`

I used this command -> `conda install -c anaconda pandas-datareader`

**Comment by bashtage** [comment]
Use pip or the conda-forge channel.
