### ISSUE TITLE
Free intraday stock data with Barcharts

### ISSUE THREAD

**Issue by femtotrader** [pydata/pandas-datareader#92]
Hello,

http://www.barchart.com/ seems to provide free intraday stock data according
http://www.blackarbs.com/blog/how-to-get-free-intraday-stock-data-with-python-and-barcharts-ondemand-api/9/22/2015
https://gist.github.com/BlackArbsCEO/2394808dcb1f7c1bdd4e#file-free_intraday_stockdata_test_barchart_api_gist-py

It may be worth to add this data source to Pandas DataReader.

@twiecki might be interested

Kind regards

**Comment by twiecki** [comment]
Definitely, looks like a great source.

**Comment by femtotrader** [comment]
I have been working on this as a standalone project (with cache support ;-) )

It's available at
https://github.com/femtotrader/barchart-ondemand-client-python

**Comment by femtotrader** [comment]
Free API access can be ask here http://freemarketdataapi.barchartondemand.com/
