### ISSUE TITLE
pandas_datareader for yahoo

### ISSUE THREAD

**Issue by vick2075** [pydata/pandas-datareader#927]
Hi,

I'm having trouble fetching data from Yahoo recently although my current code worked so well in the past:

import pandas_datareader as web
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import datetime as dt

start = dt.datetime(2010,1,1)
end = dt.datetime.today()

stock12 = ['MMM', 'MO', 'AAPL', 'T', 'BX','AVGO', 'CAT', 'CVX', 'CSCO', 'C','KO', 'CVS','XOM', 'GS', 'HSBC',
          'IBM', 'INTC', 'JPM', 'JNJ', 'KMB','LMT', 'MA', 'MCD', 'MED','MSFT','NKE','NVDA','ORCL','PFE','PG',
          'SPG','SONY','TM','UNH','UPS','VZ','V','WMT','WFC','WPC','FB','NFLX','TSLA','PYPL','BABA','AMZN','GOOG',
          'VNQ','VHT','SNXFX','VWO','BND','DOW','FXAIX','ONEQ','FNCMX','FNILX','RDVY','DJD','QQQ','DGRO','IDV','EFG',
          'XDIV','NOBL','SPGI','SWISX','SWPPX','SWTSX','SCHD','LEAD','DIA','SDY','VFIAX','VFINX','VIG','VYM','VYMI',
          'VOO','VBTLX','VXUS','VTSAX','VTSMX','DEM','DTD','VTI','O','BNDX']

stocks = stock12

ls_key = 'Close'
    
f = web.DataReader(stocks, 'yahoo',start,end)

cleanData = f[ls_key]
data = pd.DataFrame(cleanData)

Can someone please help me out?

Thank you

**Comment by Anchaliya75** [comment]
Upgrade the pandas_datareader 
you can 
**pip install --upgrade pandas_datareader**

**Comment by vick2075** [comment]
Thanks. However, I'm now using yfinance along with pandas_dataframe.
