### ISSUE TITLE
Source request: dbnomics

### ISSUE THREAD

**Issue by hliebert** [pydata/pandas-datareader#950]
Would it be possible to add dbnomics [(https://db.nomics.world/)](https://db.nomics.world/) as a data source?

**Comment by addisonlynch** [comment]
PRs for new data sources are welcome

**Comment by hliebert** [comment]
I’m relatively new to python, if you could give me a pointer on where to begin/what to work from I’ll have a go at implementing it.

**Comment by datatalking** [comment]
@hliebert This is something I was curious about as well. To start we should understand what data db.nomics.world add to what pandas-datareader other data sources does not have?

I'm working on a similar project but it has a built in database and financial planning functions that I need to add data feeds to and pandas-datareader is where I find most support.
