### ISSUE TITLE
'DataFrame' object has no attribute 'append'

### ISSUE THREAD

**Issue by AntonCoon** [pydata/pandas-datareader#966]
This simple example is failing
```puyhon
import pandas_datareader

reader = pandas_datareader.moex.MoexReader("TATN")
reader.read()
```
with following message
```
AttributeError: 'DataFrame' object has no attribute 'append'
```
The main reason is that `DataFrame` no longer support `append` operation. It have to be changed with `concat` method.

**Comment by Pankaj-Str** [comment]
If you're getting the error `'DataFrame' object has no attribute 'append'`, it's possible that you have a very old version of Pandas installed. In more recent versions of Pandas, `append()` is no longer used to add rows to a DataFrame.

You can achieve the same result using the `concat()` method. Here's the corrected code using `concat()`:

Example : 

```python
import pandas as pd

data = {
    'programming': ['python', 'c++', 'java', 'javascript'],
    'topic': ['pandas', 'variable in C', 'interface', 'function'],
    'unit': [101, 102, 103, 104]
}

# Create a DataFrame
df = pd.DataFrame(data)

# Create a dictionary for the new row
new_row = {'programming': 'ruby', 'topic': 'object-oriented programming', 'unit': 105}

# Append the new row to the DataFrame
df = pd.concat([df, pd.DataFrame([new_row])], ignore_index=True)

print(df)
```

This code should work regardless of your Pandas version and will append the new row to the DataFrame correctly.

**Comment by shooroop87** [comment]
is it resolved?

**Comment by Pankaj-Str** [comment]
```python
import pandas_datareader

reader = pandas_datareader.moex.MoexReader("TATN")
data_frame_list = []

# Instead of using append, use concat in a loop
for data_frame in reader.read():
    data_frame_list.append(data_frame)

result_df = pd.concat(data_frame_list, axis=0)



```

**Comment by Egorundel** [comment]
@AntonCoon Hi, did you manage to solve the problem?
